# Anotasi & Pre Processing Data

## Import Library

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm
import pandas as pd
import gdown
import re

## Load Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Load Dataset Scrapping

In [ ]:
PATH = '/content/drive/MyDrive/NER nlp/Scrapping Data/Dataset Scraping'
data_bkl = pd.read_csv(f"{PATH}/dataset_pnBangkalan.csv")
data_spg = pd.read_csv(f"{PATH}/dataset_pnSampang.csv")
data_pmk = pd.read_csv(f"{PATH}/dataset_pnPamekasan.csv")
data_smp = pd.read_csv(f"{PATH}/dataset_pnSumenep.csv")
data = pd.concat([data_bkl, data_spg, data_pmk, data_smp], ignore_index=True)
data.to_csv(f"{PATH}/data_pn_all.csv", index=False)
data = pd.read_csv(f"{PATH}/data_pn_all.csv")
data

,url_page,penuntut_umum,terdakwa,nomor,kata_kunci,tahun,tanggal_register,lembaga_peradilan,hakim_ketua,hakim_anggota,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"DEWI IKA AGUSTINA, SH",TISLAN bin MUKAMAR,48/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: Hosnol Bakri,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa TISLAN BIN MUKA...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,48_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 48/Pid.B/2024/PN Bkl\nDEMI KEAD...
1,https://putusan3.mahkamahagung.go.id/direktori...,"NANDINI PARAHITA YULISANI, S.H.",BEIRI Bin BUNALI,42/Pid.B/2024/PN Bkl,Penganiayaan,2024,5 Maret 2024,PN BANGKALAN,Hakim Ketua Zainal Ahmad,"Br Hakim Anggota Wienda Kresnantyo, Hakim Ang...",Panitera Pengganti: Rr. Koosbandriyah As,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Beiri bin Bunal...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,42_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 42/Pid.B/2024/PN Bkl\nDEMI KEAD...
2,https://putusan3.mahkamahagung.go.id/direktori...,"UMU LATHIEFAH, S.H",FANDI bin SULAIMAN,49/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: Hosnol Bakri,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa FANDI BIN SULAI...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,49_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 49/Pid.B/2024/PN Bkl\nDEMI KEAD...
3,https://putusan3.mahkamahagung.go.id/direktori...,"FAJRINI FAISAH, S.H.",PANDI Bin SIDIK,56/Pid.B/2024/PN Bkl,PenadahanPenerbitandan Pencetakan,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Zainal Ahmad,"Br Hakim Anggota Wienda Kresnantyo, Hakim Ang...",Panitera Pengganti: Naruddin,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: MenyatakanTerdakwaPandi Bin Sidikte...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,56_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 56/Pid.B/2024/PN Bkl\nDEMI KEAD...
4,https://putusan3.mahkamahagung.go.id/direktori...,"FAJRINI FAISAH, S.H.",MUSTOFA al. JARWOT bin HADENAN (Alm),57/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: H. Mohammad Asari,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I Menyatakan Terdakwa Mustofa ...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,57_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 57/Pid.B/2024/PN Bkl\nDEMI KEAD...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,https://putusan3.mahkamahagung.go.id/direktori...,"NUR FAJJRIYAH, SH",ZAIFUL ISLAM Bin MUDIRUN,274/Pid.Sus/2021/PN Smp,Perlindungan Anak,2022,10 Nopember 2021,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Br Hakim Anggota Anjar Kumboro, Hakim Anggota...",Panitera Pengganti Edi Haris Mulyono,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: 1. Menyatakan Terdakwa ZAIFUL ...,20 Januari 2022,20 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,274_Pid.Sus_2021_PN_Smp.pdf,PUTUSAN \nNomor 274/Pid.Sus/2021/PN Smp \n \nD...
745,https://putusan3.mahkamahagung.go.id/direktori...,HARRY ACHMAD DWI MARYONO,ABDUL MUGHNIS Bin JAUHARI,272/Pid.B/2021/PN Smp,Penganiayaan,2022,10 Nopember 2021,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Sugiarto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Abdul Mughnis B...,20 Januari 2022,20 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,272_Pid.B_2021_PN_Smp.pdf,PUTUSAN \nNomor 272/Pid.B/2021/PN Smp \n \nDEM...
746,https://putusan3.mahkamahagung.go.id/direktori...,"NUR FAJJRIYAH, SH",SUKRAWI Bin SUPATMO,220/Pid.Sus/2021/PN Smp,Perlindungan Anak,2022,2 September 2021,PN SUMENEP,Hakim Ketua Yuniar Yudha Himawan,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti Sugiarto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan terdakwa Sukrawi Bin Supa...,4 Januari 2022,4 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,220_Pid.Sus_2021_PN_Smp.pdf,PUTUSAN \nNomor 220/Pid.Sus/2021/PN Smp \n \nD...
747,https://putusan3.mahkamahagung.go.id/direktori...,"R. TEDDY ROOMIUS, SH",1.ASNAWI BIN SYAFI I 2.HORMAH BIN SAMLI,293/Pid.B/2021/PN Smp,Kejahatan Perjudian,2022,26 Nopember 2021,PN SUMENEP,Hakim Ketua Yuniar Yudha Himawan,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti Nani Irianingsih,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI1. Menyatakan terdakwa I.Asnawi Bin S...,4 Januari 2022,4 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,293_Pid.B_2021_PN_Smp.pdf,PUTUSAN \nNomor 293/Pid.B/2021/PN Smp \n \nDEM...
748,https://putusan3.mahkamahagung.go.id/direktori...,"SURYA RIZAL HERTADY, SH",LUTPI Bin MOH.DULLA,254/Pid.B/2021/PN Smp,PenadahanPenerbitandan Pencetakan,2021,13 Oktober 2021,PN SUMENEP,Hakim Ketua Arie Andhika Adikresna,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Suraji,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI:1. Menyatakan Terdakwa LUTPI Bin MOH...,27 Desember 2021,27 Desember 2021,https://putusan3.mahkamahagung.go.id/direktori...,254_Pid.B_2021_PN_Smp.pdf,PUTUSAN \nNomor 254/Pid.B/2021 /PN Smp \n \nDE...

In [ ]:
data_bkl

### Cek Kolom Data

In [ ]:
data.columns

Index(['url_page', 'penuntut_umum', 'terdakwa', 'nomor', 'kata_kunci', 'tahun',
       'tanggal_register', 'lembaga_peradilan', 'hakim_ketua', 'hakim_anggota',
       'panitera', 'amar', 'amar_lainnya', 'catatan_amar',
       'tanggal_musyawarah', 'tanggal_dibacakan', 'url_pdf', 'nama_file',
       'content'],
      dtype='object')

### Melengkapi Entitas

Membuat column baru untuk entitas yang dicari secara manual

In [ ]:
# data['tindak_pidana'] = ''
# data['pelanggaran_kuhp'] = ''
# data['putusan_hukuman'] = ''
# data['tuntutan_hukuman'] = ''
# data[['nama_file', 'penuntut_umum', 'terdakwa', 'nomor', 'tanggal_musyawarah', 'hakim_ketua',
#        'hakim_anggota', 'panitera', 'tindak_pidana', 'tuntutan_hukuman', 'pelanggaran_kuhp', 'putusan_hukuman']].to_excel("entity_pn_all.xlsx", index=False)

In [ ]:
# entities = pd.read_excel(f"entity_pn_all.xlsx")
# entities

Import Entitas yang telah di labeli secara manual

In [ ]:
entities = pd.read_excel(f"/content/drive/MyDrive/NER nlp/Dataset/Dataset Fix/Dataentity_pn_all.xlsx")
# entities = entities.applymap(str)
entities

,nama_file,penuntut_umum,terdakwa,nomor,tanggal_musyawarah,hakim_ketua,hakim_anggota,panitera,tindak_pidana,tuntutan_hukuman,pelanggaran_kuhp,putusan_hukuman
0,48_Pid.B_2024_PN_Bkl,"DEWI IKA AGUSTINA, SH",TISLAN bin MUKAMAR,48/Pid.B/2024/PN Bkl,2 Mei 2024,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: Hosnol Bakri,Pencurian Dalam Keadaan Memberatkan,2 (dua) tahun 2 (dua) bulan,Pasal 363 ayat (2) KUHP,1 (satu) Tahun dan 10 (sepuluh) bulan
1,42_Pid.B_2024_PN_Bkl,"NANDINI PARAHITA YULISANI, S.H.",BEIRI Bin BUNALI,42/Pid.B/2024/PN Bkl,2 Mei 2024,Hakim Ketua Zainal Ahmad,"Br Hakim Anggota Wienda Kresnantyo, Hakim Ang...",Panitera Pengganti: Rr. Koosbandriyah A .S,Secara Melawan Hukum Memaksa Orang Lain Supaya...,6 (enam) bulan,Pasal 335 ayat (1) Kitab Undang-Undang Hukum P...,5 (lima) bulan
2,49_Pid.B_2024_PN_Bkl,"UMU LATHIEFAH, S.H",FANDI bin SULAIMAN,49/Pid.B/2024/PN Bkl,2 Mei 2024,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: Hosnol Bakri,Pencurian Dalam Keadaan Memberatkan,2 (Dua) Tahun 2 (Dua) Bulan,Pasal 363 ayat (2) KUHP,1 (satu) Tahun dan 10 (sepuluh) bulan
3,56_Pid.B_2024_PN_Bkl,"FAJRINI FAISAH, S.H.",PANDI Bin SIDIK,56/Pid.B/2024/PN Bkl,2 Mei 2024,Hakim Ketua Zainal Ahmad,"Br Hakim Anggota Wienda Kresnantyo, Hakim Ang...",Panitera Pengganti: Naruddin,penadahan,6 (enam) bulan,Pasal 480 ke-1 Kitab Undang-Undang Hukum Pidana,4 (empat) Bulan 15 (lima belas) Hari
4,57_Pid.B_2024_PN_Bkl,"FAJRINI FAISAH, S.H.",MUSTOFA al. JARWOT bin HADENAN (Alm),57/Pid.B/2024/PN Bkl,2 Mei 2024,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: H. Mohammad Asari,pencurian dalam keadaan memberatkan,2 (dua) tahun dan 5 (lima) bulan,Pasal 363 ayat (1) ke-3 dan ke-4 KUHP,2 (dua) tahum
...,...,...,...,...,...,...,...,...,...,...,...,...
744,274_Pid.Sus_2021_PN_Smp,"Nur Fajjriy ah, S.H",ZAIFUL ISLAM Bin MUDIRUN,274/Pid.Sus/2021/PN Smp,20 Januari 2022,Hakim Ketua Yahya Wahyudi,"Br Hakim Anggota Anjar Kumboro, Hakim Anggota...",Panitera Pengganti Edi Haris Mulyono,dengan sengaja membujuk anak melakukan Persetu...,7 (Tujuh) Tahun,Pasal 81 ayat (2) Undang - Undang Republik Ind...,"5 (LIMA) Tahun,"
745,272_Pid.B_2021_PN_Smp,HARRY ACHMAD DWI MARYONO,ABDUL MUGHNIS Bin JAUHARI,272/Pid.B/2021/PN Smp,13 Januari 2022,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Sugiarto,Penganiayaan,5 (lima) Bulan,Pasal 351 ayat (1) Kitab Undang -Undang Hukum ...,3 (tiga) bulan dan 5 (lima) hari
746,220_Pid.Sus_2021_PN_Smp,"NUR FAJJRIYAH, SH",SUKRAWI Bin SUPATMO,220/Pid.Sus/2021/PN Smp,4 Januari 2022,Hakim Ketua Yuniar Yudha Himawan,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti Sugiarto,Dengan sengaja melakukan tipu muslihat memaksa...,9 (sembilan) Tahun,Pasal 82 ayat (2) U ndang - Undang Republik In...,6 (enam) tahun
747,293_Pid.B_2021_PN_Smp,"R.Tedy Roomius ,S.H.",1.ASNAWI BIN SYAFI I 2.HORMAH BIN SAMLI,293/Pid.B/2021/PN Smp,4 Januari 2022,Hakim Ketua Yuniar Yudha Himawan,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti Nani Irianingsih,Perjudian,4 (empat) bulan,Pasal 303 Ayat (l) ke.2 KUHP,3 (tiga) bulan
748,254_Pid.B_2021_PN_Smp,Surya Rizal,LUTPI Bin MOH. DULLA,254/Pid.B/2021/PN Smp,27 Desember 2021,Hakim Ketua Arie Andhika Adikresna,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Suraji,penadahan,7 (Tujuh),Pasal 480 ayat (1) KUHP,5 (lima) bulan

Menggabungkan Entitas dengan label otomatis dan manual

In [ ]:
# entities['tindak_pidana'] = entities['tindak_pidana'].fillna(entities_lengkap['tindak_pidana'])
# entities['pelanggaran_kuhp'] = entities['pelanggaran_kuhp'].fillna(entities_lengkap['pelanggaran_kuhp'])
# entities['putusan_hukuman'] = entities['putusan_hukuman'].fillna(entities_lengkap['putusan_hukuman'])
# entities['tuntutan_hukuman'] = entities['tuntutan_hukuman'].fillna(entities_lengkap['tuntutan_hukuman'])
# entities

### Processing Missing Value

Cek Missing value pada data

In [ ]:
# entities.fillna('', inplace=True)
missing_values = entities.isnull().sum()
missing_values

nama_file               0
penuntut_umum         123
terdakwa                1
nomor                   0
tanggal_musyawarah      0
hakim_ketua             0
hakim_anggota           0
panitera                0
tindak_pidana           6
tuntutan_hukuman       13
pelanggaran_kuhp        9
putusan_hukuman        17
dtype: int64

Cek missing value ada pada baris ke berapa

hapus data jika terdapat missing value

In [ ]:
entities = entities.dropna()
entities = entities.applymap(str)

In [ ]:
idx_na = entities.index[entities.isna().any(axis=1)].tolist()
idx_na

[]

Menyesuaikan ukuran data scrapping dan data yang telah di beri label

In [ ]:
data = data.loc[entities.index]
data

,url_page,penuntut_umum,terdakwa,nomor,kata_kunci,tahun,tanggal_register,lembaga_peradilan,hakim_ketua,hakim_anggota,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"DEWI IKA AGUSTINA, SH",TISLAN bin MUKAMAR,48/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: Hosnol Bakri,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa TISLAN BIN MUKA...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,48_Pid.B_2024_PN_Bkl.pdf,putusan nomor 48/pid.b/2024/pn bkl demi keadil...
1,https://putusan3.mahkamahagung.go.id/direktori...,"NANDINI PARAHITA YULISANI, S.H.",BEIRI Bin BUNALI,42/Pid.B/2024/PN Bkl,Penganiayaan,2024,5 Maret 2024,PN BANGKALAN,Hakim Ketua Zainal Ahmad,"Br Hakim Anggota Wienda Kresnantyo, Hakim Ang...",Panitera Pengganti: Rr. Koosbandriyah As,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Beiri bin Bunal...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,42_Pid.B_2024_PN_Bkl.pdf,putusan nomor 42/pid.b/2024/pn bkl demi keadil...
2,https://putusan3.mahkamahagung.go.id/direktori...,"UMU LATHIEFAH, S.H",FANDI bin SULAIMAN,49/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: Hosnol Bakri,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa FANDI BIN SULAI...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,49_Pid.B_2024_PN_Bkl.pdf,putusan nomor 49/pid.b/2024/pn bkl demi keadil...
3,https://putusan3.mahkamahagung.go.id/direktori...,"FAJRINI FAISAH, S.H.",PANDI Bin SIDIK,56/Pid.B/2024/PN Bkl,PenadahanPenerbitandan Pencetakan,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Zainal Ahmad,"Br Hakim Anggota Wienda Kresnantyo, Hakim Ang...",Panitera Pengganti: Naruddin,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: MenyatakanTerdakwaPandi Bin Sidikte...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,56_Pid.B_2024_PN_Bkl.pdf,putusan nomor 56/pid.b/2024/pn bkl demi keadil...
4,https://putusan3.mahkamahagung.go.id/direktori...,"FAJRINI FAISAH, S.H.",MUSTOFA al. JARWOT bin HADENAN (Alm),57/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: H. Mohammad Asari,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I Menyatakan Terdakwa Mustofa ...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,57_Pid.B_2024_PN_Bkl.pdf,putusan nomor 57/pid.b/2024/pn bkl demi keadil...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,https://putusan3.mahkamahagung.go.id/direktori...,"NUR FAJJRIYAH, SH",ZAIFUL ISLAM Bin MUDIRUN,274/Pid.Sus/2021/PN Smp,Perlindungan Anak,2022,10 Nopember 2021,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Br Hakim Anggota Anjar Kumboro, Hakim Anggota...",Panitera Pengganti Edi Haris Mulyono,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: 1. Menyatakan Terdakwa ZAIFUL ...,20 Januari 2022,20 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,274_Pid.Sus_2021_PN_Smp.pdf,putusan nomor 274/pid.sus/2021/pn smp demi kea...
745,https://putusan3.mahkamahagung.go.id/direktori...,HARRY ACHMAD DWI MARYONO,ABDUL MUGHNIS Bin JAUHARI,272/Pid.B/2021/PN Smp,Penganiayaan,2022,10 Nopember 2021,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Sugiarto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Abdul Mughnis B...,20 Januari 2022,20 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,272_Pid.B_2021_PN_Smp.pdf,putusan nomor 272/pid.b/2021/pn smp demi keadi...
746,https://putusan3.mahkamahagung.go.id/direktori...,"NUR FAJJRIYAH, SH",SUKRAWI Bin SUPATMO,220/Pid.Sus/2021/PN Smp,Perlindungan Anak,2022,2 September 2021,PN SUMENEP,Hakim Ketua Yuniar Yudha Himawan,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti Sugiarto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan terdakwa Sukrawi Bin Supa...,4 Januari 2022,4 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,220_Pid.Sus_2021_PN_Smp.pdf,putusan nomor 220/pid.sus/2021/pn smp demi kea...
747,https://putusan3.mahkamahagung.go.id/direktori...,"R. TEDDY ROOMIUS, SH",1.ASNAWI BIN SYAFI I 2.HORMAH BIN SAMLI,293/Pid.B/2021/PN Smp,Kejahatan Perjudian,2022,26 Nopember 2021,PN SUMENEP,Hakim Ketua Yuniar Yudha Himawan,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti Nani Irianingsih,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI1. Menyatakan terdakwa I.Asnawi Bin S...,4 Januari 2022,4 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,293_Pid.B_2021_PN_Smp.pdf,putusan nomor 293/pid.b/2021/pn smp demi keadi...
748,https://putusan3.mahkamahagung.go.id/direktori...,"SURYA RIZAL HERTADY, SH",LUTPI Bin MOH.DULLA,254/Pid.B/2021/PN Smp,PenadahanPenerbitandan Pencetakan,2021,13 Oktober 2021,PN SUMENEP,Hakim Ketua Arie Andhika Adikresna,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Suraji,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI:1. Menyatakan Terdakwa LUTPI Bin MOH...,27 Desember 2021,27 Desember 2021,https://putusan3.mahkamahagung.go.id/direktori...,254_Pid.B_2021_PN_Smp.pdf,putusan nomor 254/pid.b/2021/pn smp demi keadi...

## Membuat format entitas

Format Data secara otomatis

In [ ]:
# def format_penuntut_umum(penuntut_umum):
#     penuntut_umum = re.sub(r'\b(S\.H\.?|M\.H\.?|SH|MH)\b', '', penuntut_umum).replace(',', '')
#     if any(char.isdigit() for char in penuntut_umum):
#         penuntut_umum = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', penuntut_umum.lower())
#     else:
#         penuntut_umum = [penuntut_umum.lower().strip()]

#     penuntut_umum = [name.rstrip('.') for name in penuntut_umum]
#     penuntut_umum = [re.sub(r'\s*\.\s*$', '', name).strip() for name in penuntut_umum]
#     return penuntut_umum

# def format_terdakwa(terdakwa):
#     if any(char.isdigit() for char in terdakwa):
#         terdakwa = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', terdakwa.lower())
#     else:
#         terdakwa = [terdakwa.lower().strip()]
#     return terdakwa

# entities_formated = entities.copy()
# entities_formated["penuntut_umum"] = entities_formated["penuntut_umum"].apply(lambda x: format_penuntut_umum(x))
# entities_formated["terdakwa"] = entities_formated["terdakwa"].apply(lambda x: format_terdakwa(x))
# entities_formated["nomor"] = entities_formated["nomor"].apply(lambda x: x.lower().strip())
# entities_formated["tanggal_musyawarah"] = entities_formated["tanggal_musyawarah"].apply(lambda x: re.sub(r'\b0+(\d+)', r'\1', x.lower().replace('nopember', 'november').strip()))
# entities_formated["hakim_ketua"] = entities_formated["hakim_ketua"].apply(lambda x: x.lower().replace("hakim ketua", '').replace("hakim tunggal", '').strip())
# entities_formated["hakim_anggota"] = entities_formated["hakim_anggota"].apply(lambda x: x.lower().replace("hakim anggota", '').replace("hakim tunggal", '').replace("br", '').strip().split(','))
# entities_formated["panitera"] = entities_formated["panitera"].apply(lambda x: x.lower().replace("panitera pengganti", "").replace(":", "").strip())
# entities_formated["tindak_pidana"] = data["catatan_amar"].apply(lambda x: ', '.join([re.sub(r'[?,]', '', item.strip()) for item in re.findall(r'tindak pidana[:\s]\s*(.*?)(?:\s+sebagaimana|;|$)', ' '.join([item.strip() for item in x.lower().replace("\n", ' ').split(';')]))]))
# entities_formated["putusan_hukuman"] = data["catatan_amar"].apply(lambda x: ', '.join(re.findall(r'selama\s+(.*?)(?:\s+menetapkan|menyatakan|;|$)',  ' '.join([item.strip() for item in x.lower().replace("\n", ' ').split(';')]))))
# entities_formated["pelanggaran_kuhp"] = data["content"].apply(lambda x: ', '.join(re.findall(r'memperhatikan,\s+(.*?)(?:\s+dan)',  ' '.join([item.strip() for item in x.lower().replace("\n", ' ').split(';')]))))
# entities_formated["tuntutan_hukuman"] = data["content"].apply(lambda x: re.findall(r'selama\s+(.*?)(?:\s+penjara|dikurangi|dikurangkan|dengan)', ' '.join([item.strip() for item in x.lower().replace("\n", ' ').split(';')]))[0] if re.findall(r'pidana penjara selama\s+(.*?)(?:\s+penjara|dikurangi|dikurangkan|dengan)', ' '.join([item.strip() for item in x.lower().replace("\n", ' ').split(';')])) else '')

# entities_formated

Format data secara manual dan otomatis

In [ ]:
def format_penuntut_umum(penuntut_umum):
    penuntut_umum = re.sub(r'\b(S\.H\.?|M\.H\.?|SH|MH)\b', '', penuntut_umum).replace(',', '')
    if any(char.isdigit() for char in penuntut_umum):
        penuntut_umum = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', penuntut_umum.lower())
    else:
        penuntut_umum = [penuntut_umum.lower().strip()]

    penuntut_umum = [name.rstrip('.') for name in penuntut_umum]
    penuntut_umum = [re.sub(r'\s*\.\s*$', '', name).strip() for name in penuntut_umum]
    return penuntut_umum

def format_terdakwa(terdakwa):
    if any(char.isdigit() for char in terdakwa):
        terdakwa = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', terdakwa.lower())
    else:
        terdakwa = [terdakwa.lower().strip()]
    return terdakwa

def format_tuntutan(tuntutan):
    tuntutan_list = tuntutan.lower().split(';')
    tuntutan_list = [tuntutan.strip() for tuntutan in tuntutan_list]
    return tuntutan_list

def format_putusan(putusan):
    putusan_list = putusan.lower().split(';')
    putusan_list = [putusan.strip() for putusan in putusan_list]
    return putusan_list

entities_formated = entities.copy()
entities_formated["penuntut_umum"] = entities_formated["penuntut_umum"].apply(lambda x: format_penuntut_umum(x))
entities_formated["terdakwa"] = entities_formated["terdakwa"].apply(lambda x: format_terdakwa(x))
entities_formated["nomor"] = entities_formated["nomor"].apply(lambda x: x.lower().strip())
entities_formated["tanggal_musyawarah"] = entities_formated["tanggal_musyawarah"].apply(lambda x: re.sub(r'\b0+(\d+)', r'\1', x.lower().replace('nopember', 'november').strip()))
entities_formated["hakim_ketua"] = entities_formated["hakim_ketua"].apply(lambda x: x.lower().replace("hakim ketua", '').replace("hakim tunggal", '').strip())
# entities_formated["hakim_anggota"] = entities_formated["hakim_anggota"].apply(lambda x: x.lower().replace("hakim anggota", '').replace("hakim tunggal", '').replace("br", '').strip().split(','))
entities_formated["hakim_anggota"] = entities_formated["hakim_anggota"].apply(lambda x: re.sub(r'\bbr\b', '', x.lower().replace("hakim anggota", '').replace("hakim tunggal", '')).strip().split(','))
entities_formated["panitera"] = entities_formated["panitera"].apply(lambda x: x.lower().replace("panitera pengganti", "").replace(":", "").strip())
entities_formated["tindak_pidana"] = entities_formated["tindak_pidana"].apply(lambda x: str(x).lower().strip() if isinstance(x, str) else x)
entities_formated["tuntutan_hukuman"] = entities_formated["tuntutan_hukuman"].apply(lambda x: format_tuntutan(str(x)) if isinstance(x, str) else x)
entities_formated["pelanggaran_kuhp"] = entities_formated["pelanggaran_kuhp"].apply(lambda x: str(x).lower().strip() if isinstance(x, str) else x)
entities_formated["putusan_hukuman"] = entities_formated["putusan_hukuman"].apply(lambda x: format_putusan(str(x)) if isinstance(x, str) else x)

entities_formated

,nama_file,penuntut_umum,terdakwa,nomor,tanggal_musyawarah,hakim_ketua,hakim_anggota,panitera,tindak_pidana,tuntutan_hukuman,pelanggaran_kuhp,putusan_hukuman
0,48_Pid.B_2024_PN_Bkl,[dewi ika agustina],[tislan bin mukamar],48/pid.b/2024/pn bkl,2 mei 2024,ernila widikartikawati,"[wahyu eko suryowati, satrio budiono]",hosnol bakri,pencurian dalam keadaan memberatkan,[2 (dua) tahun 2 (dua) bulan],pasal 363 ayat (2) kuhp,[1 (satu) tahun dan 10 (sepuluh) bulan]
1,42_Pid.B_2024_PN_Bkl,[nandini parahita yulisani],[beiri bin bunali],42/pid.b/2024/pn bkl,2 mei 2024,zainal ahmad,"[wienda kresnantyo, kadek dwi krisna ananda]",rr. koosbandriyah a .s,secara melawan hukum memaksa orang lain supaya...,[6 (enam) bulan],pasal 335 ayat (1) kitab undang-undang hukum p...,[5 (lima) bulan]
2,49_Pid.B_2024_PN_Bkl,[umu lathiefah],[fandi bin sulaiman],49/pid.b/2024/pn bkl,2 mei 2024,ernila widikartikawati,"[wahyu eko suryowati, satrio budiono]",hosnol bakri,pencurian dalam keadaan memberatkan,[2 (dua) tahun 2 (dua) bulan],pasal 363 ayat (2) kuhp,[1 (satu) tahun dan 10 (sepuluh) bulan]
3,56_Pid.B_2024_PN_Bkl,[fajrini faisah],[pandi bin sidik],56/pid.b/2024/pn bkl,2 mei 2024,zainal ahmad,"[wienda kresnantyo, kadek dwi krisna ananda]",naruddin,penadahan,[6 (enam) bulan],pasal 480 ke-1 kitab undang-undang hukum pidana,[4 (empat) bulan 15 (lima belas) hari]
4,57_Pid.B_2024_PN_Bkl,[fajrini faisah],[mustofa al. jarwot bin hadenan (alm)],57/pid.b/2024/pn bkl,2 mei 2024,ernila widikartikawati,"[wahyu eko suryowati, satrio budiono]",h. mohammad asari,pencurian dalam keadaan memberatkan,[2 (dua) tahun dan 5 (lima) bulan],pasal 363 ayat (1) ke-3 dan ke-4 kuhp,[2 (dua) tahum]
...,...,...,...,...,...,...,...,...,...,...,...,...
744,274_Pid.Sus_2021_PN_Smp,[nur fajjriy ah],[zaiful islam bin mudirun],274/pid.sus/2021/pn smp,20 januari 2022,yahya wahyudi,"[anjar kumboro, muhammad arief fatony]",edi haris mulyono,dengan sengaja membujuk anak melakukan persetu...,[7 (tujuh) tahun],pasal 81 ayat (2) undang - undang republik ind...,"[5 (lima) tahun,]"
745,272_Pid.B_2021_PN_Smp,[harry achmad dwi maryono],[abdul mughnis bin jauhari],272/pid.b/2021/pn smp,13 januari 2022,yahya wahyudi,"[muhammad arief fatony, anjar kumboro]",sugiarto,penganiayaan,[5 (lima) bulan],pasal 351 ayat (1) kitab undang -undang hukum ...,[3 (tiga) bulan dan 5 (lima) hari]
746,220_Pid.Sus_2021_PN_Smp,[nur fajjriyah],[sukrawi bin supatmo],220/pid.sus/2021/pn smp,4 januari 2022,yuniar yudha himawan,"[yahya wahyudi, anjar kumboro]",sugiarto,dengan sengaja melakukan tipu muslihat memaksa...,[9 (sembilan) tahun],pasal 82 ayat (2) u ndang - undang republik in...,[6 (enam) tahun]
747,293_Pid.B_2021_PN_Smp,[r.tedy roomius],"[asnawi bin syafi i, hormah bin samli]",293/pid.b/2021/pn smp,4 januari 2022,yuniar yudha himawan,"[yahya wahyudi, anjar kumboro]",nani irianingsih,perjudian,[4 (empat) bulan],pasal 303 ayat (l) ke.2 kuhp,[3 (tiga) bulan]
748,254_Pid.B_2021_PN_Smp,[surya rizal],[lutpi bin moh. dulla],254/pid.b/2021/pn smp,27 desember 2021,arie andhika adikresna,"[muhammad arief fatony, iksandiaji yuris f...",suraji,penadahan,[7 (tujuh)],pasal 480 ayat (1) kuhp,[5 (lima) bulan]

## Cleaning Kolom content

In [ ]:
def clean_text(text):
    text = text.replace('P U T U S A N', 'PUTUSAN').replace('T erdakwa', 'Terdakwa').replace('T empat', 'Tempat').replace('T ahun', 'Tahun')
    text = text.replace('P  E  N  E  T  A  P  A  N', 'PENETAPAN').replace('J u m l a h', 'Jumlah').replace('M E N G A D I L I', 'MENGADILI')
    text = re.sub(r'(Hal\.\s*\S+(?:\s*\S+)?\.?\s*)|(Halaman \d+(?:\.\d+)?\s*)|Putusan Nomor \S+\s*', '', text)
    # text = re.sub(r'\b0+(\d+)', r'\1', text)
    text = text.replace('\uf0d8', '').replace('\uf0b7', '').replace('\n', ' ')
    text = re.sub(r'([“”"])', r' \1 ', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'halaman\s*\d+\s*dari\s*\d+\s*', '', text)
    text = re.sub(r'^\s*dari\s+\d+\s+bkl\s+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'^\s*dari\s+\d+\s+smp\s+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\s+/PN', '/PN', text)
    text = re.sub(r'(?i)(nomor)(\d+)', r'\1 \2', text)
    text = re.sub(r'\(\s*(.*?)\s*\)', r'(\1)', text)
    text = re.sub(r':\s*(\S)', r': \1', text)
    text = re.sub(r',\s*(sh)', r' ,\1', text, flags=re.IGNORECASE)
    text = re.sub(r',\s*(s)', r' ,\1', text, flags=re.IGNORECASE)
    text = re.sub(r'(\d)\s*\((.*?)\)', r'\1 (\2)', text)
    text = re.sub(r'(\d+)\s*/pid', r'\1/pid', text)
    text = re.sub(r'(\d+)\s*/\s*(pid\.\w+)\s*/\s*(\d{4})\s*/\s*(pn)', r'\1/\2/\3/\4', text, flags=re.IGNORECASE)

    return text.lower().strip()

def multiple_replace(text, replacements):
    regex = re.compile('|'.join(re.escape(key) for key in replacements.keys()))

    def replace(match):
        return replacements[match.group(0)]

    return regex.sub(replace, text)

replacements = {
    '1 0 (sepuluh)': '10 (sepuluh)', 'Nopember': 'November','Pebruari': 'Februari', 'Halaman1dari13Putusan' : 'Putusan', ':ABDUL' : 'ABDUL', 'A STUTI' :'ASTUTI', "SA'AT" : 'SA’AT', "Rifa'i" : 'Rifa’i',
    'N omor': 'Nomor', 'K itab': 'Kitab', 'Hakmelakukan': 'Hak melakukan', '20 20': '2020', 'ke manfatan': 'kemanfatan', '2 7' : '27', 'A gustus' : 'Agustus', 'September2023,' : 'September 2023,',
    '( 2)': '(2)', '.,': ' .,', ',S': ' ,S', 'PN.Pmk': 'PN Pmk', 'Pencuriandalam': 'Pencurian dalam', 'B in' : 'bin', 'Aapril' : 'April', 'Ja nuari' : 'Januari', 'Ted dy' : 'Teddy', 'Ro omius,' : 'Roomius,',
    'Pembunuhanberencana': 'Pembunuhan berencana', 'h ukum': 'hukum', 'PNPmk': 'PN Pmk', '//PN': '/PN','R .B.': 'R. B.', '2022oleh' : '2022', 'olehFajrini' : 'oleh Fajrini', 'Alimuddi n,' : 'Alimuddin,',
    '202 3/PN': '2023/PN', 'Perkos aan': 'Perkosaan', 'memberatka n': 'memberatkan', 'p idana': 'pidana', 'sebag aimana': 'sebagaimana', '1 0' : '10','bulan;' : 'bulan', '2 23' : '2023',
    'Ram dhani': 'Ramdhani', 'H ADY': 'HADY', '2 023': '2023','2 022': '2022', 'f isik': 'fisik', 'be rsalah': 'bersalah', '(sepuluh )': '(sepuluh)', 'M U A R I' : 'MUARI', 'Bulan;' : 'Bulan', 'Ap ril' : 'April',
    '(enam )': '(enam)', 'No mor': 'Nomor', '( 3)': '(3)', 'Nomo r': 'Nomor', 'an ak': 'anak', 'tuj uh': 'tujuh', 'hu bungan': 'hubungan', 'KADIR;' : 'KADIR', 'selam a1 (satu)' : 'selama 1 (satu)',
    '(empat )' : '(empat)', "PA'I" : 'PA’I', 'S eptember' : 'September',
    'Keadaa n' : 'Keadaan', '27Januari' : '27 Januari', 'Nomor265/Pid.B/2021/PN' : 'Nomor 265/Pid.B/2021/PN', 'Bulan;3.Menetapkan' : 'Bulan 3.Menetapkan','bulan;3.Menetapkan' : 'bulan 3.Menetapkan', 'Januari,2023' : 'Januari 2023',
    '202 2' : '2022','202 4' : '2024', '202 3' : '2023','2023//' : '2023', '20 22' : '2022','20 21' : '2021','202 1' : '2021', '27januari' : '27 januari', 'januari,2023' : 'januari 2023', 'sepember' : 'september',
    'Bk l' : 'Bkl', 'bk l' : 'bkl','pm k' : 'pmk', 'bki' : 'bkl',  'pid.b /' : 'pid.b/', 'pn.' : 'pn ', 'pid. b' : 'pid.b', 'pnpmk' : 'pn pmk', '2023pn' : '2023 pn', 'smp.' : 'smp',
    '(al m)' : '(alm)', 'Al m' : 'Alm', "'" : '’', 'b in' : 'bin', 'bu lan' : 'bulan', 'kuhpdan' : 'kuhp dan',
    'pencuriandalam' : 'pencurian dalam', 'keadaa n' : 'keadaan', 'pembunuhanberencana' : 'pembunuhan berencana', 'bulan3.menetapkan' : 'bulan 3.menetapkan', 'bulan3.menyatakan' :  'bulan 3.menyatakan',
    't aufik' : 'taufik', 'olehhaidir' : 'oleh haidir','olehfajrini' : 'oleh fajrini', 'janurai' : 'januari', 'nopember': 'november','pebruari': 'februari','a gustus' : 'agustus', 'september2023,' : 'september 2023,','aapril' : 'april', 'ja nuari' : 'januari',
    'no mor': 'nomor', ',serta' : ', serta', 'agussyamsul' : 'agus syamsul', 'a stuti' : 'astuti'
}

data['content'] = data["content"].apply(clean_text).apply(lambda x: multiple_replace(x, replacements))

Penggabungan data label dengan kolom content

In [ ]:
new_data = pd.concat([entities_formated.drop(idx_na), data.drop(idx_na)['content']], axis=1)
new_data.reset_index(drop=True, inplace=True)
len(new_data)

602

In [ ]:
new_data = pd.concat([entities_formated, data['content']], axis=1)

In [ ]:
new_data

,nama_file,penuntut_umum,terdakwa,nomor,tanggal_musyawarah,hakim_ketua,hakim_anggota,panitera,tindak_pidana,tuntutan_hukuman,pelanggaran_kuhp,putusan_hukuman,content
0,48_Pid.B_2024_PN_Bkl,[dewi ika agustina],[tislan bin mukamar],48/pid.b/2024/pn bkl,2 mei 2024,ernila widikartikawati,"[wahyu eko suryowati, satrio budiono]",hosnol bakri,pencurian dalam keadaan memberatkan,[2 (dua) tahun 2 (dua) bulan],pasal 363 ayat (2) kuhp,[1 (satu) tahun dan 10 (sepuluh) bulan],putusan nomor 48/pid.b/2024/pn bkl demi keadil...
1,42_Pid.B_2024_PN_Bkl,[nandini parahita yulisani],[beiri bin bunali],42/pid.b/2024/pn bkl,2 mei 2024,zainal ahmad,"[wienda kresnantyo, kadek dwi krisna ananda]",rr. koosbandriyah a .s,secara melawan hukum memaksa orang lain supaya...,[6 (enam) bulan],pasal 335 ayat (1) kitab undang-undang hukum p...,[5 (lima) bulan],putusan nomor 42/pid.b/2024/pn bkl demi keadil...
2,49_Pid.B_2024_PN_Bkl,[umu lathiefah],[fandi bin sulaiman],49/pid.b/2024/pn bkl,2 mei 2024,ernila widikartikawati,"[wahyu eko suryowati, satrio budiono]",hosnol bakri,pencurian dalam keadaan memberatkan,[2 (dua) tahun 2 (dua) bulan],pasal 363 ayat (2) kuhp,[1 (satu) tahun dan 10 (sepuluh) bulan],putusan nomor 49/pid.b/2024/pn bkl demi keadil...
3,56_Pid.B_2024_PN_Bkl,[fajrini faisah],[pandi bin sidik],56/pid.b/2024/pn bkl,2 mei 2024,zainal ahmad,"[wienda kresnantyo, kadek dwi krisna ananda]",naruddin,penadahan,[6 (enam) bulan],pasal 480 ke-1 kitab undang-undang hukum pidana,[4 (empat) bulan 15 (lima belas) hari],putusan nomor 56/pid.b/2024/pn bkl demi keadil...
4,57_Pid.B_2024_PN_Bkl,[fajrini faisah],[mustofa al. jarwot bin hadenan (alm)],57/pid.b/2024/pn bkl,2 mei 2024,ernila widikartikawati,"[wahyu eko suryowati, satrio budiono]",h. mohammad asari,pencurian dalam keadaan memberatkan,[2 (dua) tahun dan 5 (lima) bulan],pasal 363 ayat (1) ke-3 dan ke-4 kuhp,[2 (dua) tahum],putusan nomor 57/pid.b/2024/pn bkl demi keadil...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,274_Pid.Sus_2021_PN_Smp,[nur fajjriy ah],[zaiful islam bin mudirun],274/pid.sus/2021/pn smp,20 januari 2022,yahya wahyudi,"[anjar kumboro, muhammad arief fatony]",edi haris mulyono,dengan sengaja membujuk anak melakukan persetu...,[7 (tujuh) tahun],pasal 81 ayat (2) undang - undang republik ind...,"[5 (lima) tahun,]",putusan nomor 274/pid.sus/2021/pn smp demi kea...
745,272_Pid.B_2021_PN_Smp,[harry achmad dwi maryono],[abdul mughnis bin jauhari],272/pid.b/2021/pn smp,13 januari 2022,yahya wahyudi,"[muhammad arief fatony, anjar kumboro]",sugiarto,penganiayaan,[5 (lima) bulan],pasal 351 ayat (1) kitab undang -undang hukum ...,[3 (tiga) bulan dan 5 (lima) hari],putusan nomor 272/pid.b/2021/pn smp demi keadi...
746,220_Pid.Sus_2021_PN_Smp,[nur fajjriyah],[sukrawi bin supatmo],220/pid.sus/2021/pn smp,4 januari 2022,yuniar yudha himawan,"[yahya wahyudi, anjar kumboro]",sugiarto,dengan sengaja melakukan tipu muslihat memaksa...,[9 (sembilan) tahun],pasal 82 ayat (2) u ndang - undang republik in...,[6 (enam) tahun],putusan nomor 220/pid.sus/2021/pn smp demi kea...
747,293_Pid.B_2021_PN_Smp,[r.tedy roomius],"[asnawi bin syafi i, hormah bin samli]",293/pid.b/2021/pn smp,4 januari 2022,yuniar yudha himawan,"[yahya wahyudi, anjar kumboro]",nani irianingsih,perjudian,[4 (empat) bulan],pasal 303 ayat (l) ke.2 kuhp,[3 (tiga) bulan],putusan nomor 293/pid.b/2021/pn smp demi keadi...
748,254_Pid.B_2021_PN_Smp,[surya rizal],[lutpi bin moh. dulla],254/pid.b/2021/pn smp,27 desember 2021,arie andhika adikresna,"[muhammad arief fatony, iksandiaji yuris f...",suraji,penadahan,[7 (tujuh)],pasal 480 ayat (1) kuhp,[5 (lima) bulan],putusan nomor 254/pid.b/2021/pn smp demi keadi...

In [ ]:
# entities_formated.to_excel(f"entities_formated_all.xlsx", index=False)

Membuat file txt dari content

In [ ]:
# import pandas as pd
# import zipfile
# import os

# def save_contents_to_txt_and_zip(dataframe, content_column, output_zip, file_name_column):
#     # Membuat direktori sementara untuk menyimpan file teks
#     temp_dir = "temp_txt_files"
#     os.makedirs(temp_dir, exist_ok=True)

#     try:
#         # Menyimpan setiap baris dari kolom 'content' sebagai file teks terpisah
#         for idx, row in dataframe.iterrows():
#             # Menggunakan nilai dari kolom 'file_name_column' untuk nama file
#             file_name = str(row[file_name_column]).replace('.pdf','')
#             file_name = os.path.join(temp_dir, f'{file_name}.txt')

#             with open(file_name, 'w', encoding='utf-8') as file:
#                 file.write(row[content_column])

#         # Membuat file ZIP dan menambahkan file teks ke dalamnya
#         with zipfile.ZipFile(output_zip, 'w') as zipf:
#             for root, _, files in os.walk(temp_dir):
#                 for file in files:
#                     file_path = os.path.join(root, file)
#                     zipf.write(file_path, os.path.relpath(file_path, temp_dir))
#     finally:
#         # Menghapus file teks sementara
#         for root, _, files in os.walk(temp_dir):
#             for file in files:
#                 os.remove(os.path.join(root, file))
#         os.rmdir(temp_dir)

# save_contents_to_txt_and_zip(data, 'content', 'data_txt.zip', 'nama_file')

## Anotasi Data

In [ ]:
def generate_label(entities):
  label = {}

  def update_label(entity_list, label, label_value):
    if entity_list:  # Periksa apakah entity_list tidak kosong
        if len(entity_list) > 1:
            label.update({pg.strip(): label_value for pg in entity_list})
        else:
            if (entity_list[0]) == '':
              pass
            else:
              label[entity_list[0].strip()] = label_value

  # Periksa dan perbarui kamus label untuk setiap entitas
  if 'penuntut_umum' in entities and entities['penuntut_umum']:
      update_label(entities['penuntut_umum'], label, "B_PROS")

  if 'terdakwa' in entities and entities['terdakwa']:
      update_label(entities['terdakwa'], label, "B_DEFN")

  if 'hakim_anggota' in entities and entities['hakim_anggota']:
      update_label(entities['hakim_anggota'], label, "B_JUG")

  if 'putusan_hukuman' in entities and entities['putusan_hukuman']:
      update_label(entities['putusan_hukuman'], label, "B_PUNI")

  if 'tuntutan_hukuman' in entities and entities['tuntutan_hukuman']:
      update_label(entities['tuntutan_hukuman'], label, "B_PENA")

  label[entities['nomor']] = "B_VERN"
  label[entities['tanggal_musyawarah']] = "B_TIMV"
  label[entities['hakim_ketua']] = "B_JUDP"
  label[entities['panitera']] = "B_REGI"
  label[entities['tindak_pidana']] = "B_CRIA"
  label[entities['pelanggaran_kuhp']] = "B_ARTV"
  # label[entities['putusan_hukuman']] = "B_PUNI"
  # label[entities['tuntutan_hukuman']] = "B_PENA"

  return label

def labeling_token(text, label_dict):
    tokens = text.lower().split()
    labeled_tokens = ['O'] * len(tokens)
    find_label = dict()

    for key, value in label_dict.items():
        if key:  # Pastikan kunci tidak kosong
            words = key.split()
            current_dict = find_label
            for word in words[:-1]:
                word = re.sub(r'[.,;"]', '', word)
                current_dict = current_dict.setdefault(word, {})
            if words:
                last_word = re.sub(r'[.,;"]', '', words[-1])
                current_dict[last_word] = {'label': value}

    temp_idx_token = []
    find_label_selected = find_label
    for i, token in enumerate(tokens):
        clean_token = re.sub(r'[.,;"]', '', token)
        if clean_token in find_label_selected:
            find_label_selected = find_label_selected[clean_token]
            temp_idx_token.append(i)
            if 'label' in find_label_selected:
                tag = find_label_selected['label']
                new_label = [tag if ind == 0 else tag.replace('B', 'I') for ind in range(len(temp_idx_token))]
                labeled_tokens[temp_idx_token[0]:temp_idx_token[0] + len(new_label)] = new_label
                temp_idx_token = []
                find_label_selected = find_label
        else:
            temp_idx_token = []
            find_label_selected = find_label

    return labeled_tokens

def handleDuplicatePena(sequences):
    countPena = 0

    for sequence in sequences:
        for i, label in enumerate(sequence):
            if label == 'B_PENA':
                countPena += 1
                if countPena > 1:
                    sequence[i] = 'B_PUNI'
            elif label == 'I_PENA':
                if countPena > 1:
                    sequence[i] = 'I_PUNI'

    return sequences

def anotasi(data):
    content_results = pd.DataFrame(columns=["doc", "text", "label"])
    count_label = {}
    labels = []

    for doc_idx, (_, row) in tqdm(enumerate(data.iterrows()), total=len(data), desc="Annotating"):
        temp_results = {"doc": [], "text": [], "label": []}

        label = generate_label(row)
        labels.append(label)
        content = row["content"]

        labeled_tokens = labeling_token(content, label)

        doc_str = f"doc:{doc_idx}"

        temp_results["doc"].append(doc_str)
        temp_results["text"].append(content.split())
        temp_results["label"].append(labeled_tokens)

        temp_results['label'] = handleDuplicatePena(temp_results['label'])
        temp_data = pd.DataFrame(temp_results)
        count_label.update(countLabel(f"{doc_idx}", temp_data, set(label.values())))
        content_results = pd.concat([content_results, temp_data], ignore_index=True)

    return content_results, count_label, labels

def countLabel(doc_idx, data, label_ori):
    result = {}
    label_found = set()
    label_list = set(['B_ARTV', 'B_DEFN', 'B_PROS', 'B_CRIA', 'B_JUDP', 'B_VERN', 'B_PUNI', 'B_JUG', 'B_REGI', 'B_TIMV', 'B_PENA'])
    for i, row in data.iterrows():
      for t, l in zip(row["text"], row["label"]):
        if l != 'O' and l.replace('I_', 'B_') not in label_found:
          label_found.add(l.replace('I_', 'B_'))
    label_missing = label_list - label_found  #mencari label  hilang dari 11 label

    result[f"Dokumen Ke-{doc_idx}"] = (len(label_found), len(label_ori), label_missing, label_found)

    return result

def accuracy(result):
  sum_label = 0
  label_in = 0
  for key, value in result.items():
    print(f"{key} => Data Terlebel : {value[0]} ; Total Label : {value[1]} ; Label Hilang : {value[2]} ; Label Ditemukan: {value[3]}")
    sum_label+= value[1]
    label_in += value[0]

  return f"Accuracy : {label_in/sum_label * 100}"

new_df, count_label, labels = anotasi(new_data)

Annotating: 100%|██████████| 602/602 [00:06<00:00, 90.16it/s]

Data Ter Anotasi

In [ ]:
new_df

,doc,text,label
0,doc:0,"[putusan, nomor, 48/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
1,doc:1,"[putusan, nomor, 42/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
2,doc:2,"[putusan, nomor, 49/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
3,doc:3,"[putusan, nomor, 56/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
4,doc:4,"[putusan, nomor, 57/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
...,...,...,...
597,doc:597,"[putusan, nomor, 274/pid.sus/2021/pn, smp, dem...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
598,doc:598,"[putusan, nomor, 272/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
599,doc:599,"[putusan, nomor, 220/pid.sus/2021/pn, smp, dem...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
600,doc:600,"[putusan, nomor, 293/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
601,doc:601,"[putusan, nomor, 254/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."

Menyimpan hasil anotasi per dokumen

In [ ]:
def missing(result):
  missing = []
  for key, value in result.items():
    if(value[0] != 11):
      missing.append(f"{key} => Data Terlebel : {value[0]} ; Total Label : {value[1]} ; Label Hilang : {value[2]} ; Label Ditemukan: {value[3]}")
  return missing

def missing(result, filename="missing.txt"):
    with open(filename, 'w') as file:
        for key, value in result.items():
          if(value[0] != 11):
            line = f"{key} => Data Terlebel : {value[0]} ; Total Label : {value[1]} ; Label Hilang : {value[2]} ; Label Ditemukan: {value[3]}\n"
            file.write(line)

missing(count_label)

In [ ]:
def save_accuracy(result, filename="accuracy_results.txt"):
    sum_label = 0
    label_in = 0

    with open(filename, 'w') as file:
        for key, value in result.items():
            line = f"{key} => Data Terlebel : {value[0]} ; Total Label : {value[1]} ; Label Hilang : {value[2]} ; Label Ditemukan: {value[3]}\n"
            file.write(line)
            sum_label += value[1]
            label_in += value[0]

        # Optionally, you can also write the summary (sum_label and label_in) to the file
        summary = f"\nTotal Data Terlebel: {label_in}\nTotal Label: {sum_label}\n"
        file.write(summary)

save_accuracy(count_label)

In [ ]:
id = 595
label = "PENA"
selected_doc = new_df[new_df["doc"] == f"doc:{id}"]
dict_label = labels[id]

def getEntity(d, value):
    for k, v in d.items():
        if v == value:
            return k
    return False

start_index = None
end_index = None
target_words = getEntity(dict_label, f"B_{label}")
print(target_words)

if not target_words:
    user_input = input(f"Label 'B_{label}' tidak ditemukan. Masukkan entitas untuk label tersebut: ")
    target_words = user_input

target_words = "9 (sembilan) tahun"
target_words = target_words.lower().split()
print(target_words)

for i, row in selected_doc.iterrows():
    text_lower = [word.lower() for word in row['text']]
    for j in range(len(row['text']) - len(target_words) + 1):
        if text_lower[j:j+len(target_words)] == target_words:
            start_index = (i, j)
            end_index = (i, j + len(target_words) - 1)
            break

if start_index is not None:
    for i in range(start_index[1], end_index[1]+1):
        if i == start_index[1]:
            new_df.at[start_index[0], 'label'][i] = f'B_{label}'
        else:
            new_df.at[start_index[0], 'label'][i] = f'I_{label}'

if start_index is not None:
    print(f"Kata-kata ditemukan pada index {start_index} sampai {end_index}.")
else:
    print(f"Kata-kata tidak ditemukan.")

print(new_df['text'][start_index[0]])
print(new_df['label'][start_index[0]])

9 ( sembilan) tahun
['9', '(sembilan)', 'tahun']
Kata-kata ditemukan pada index (595, 706) sampai (595, 708).

In [ ]:
labels[595]

{'harry achmad dwi maryono': 'B_PROS',
 'junaidi bin ahwardi': 'B_DEFN',
 'moh. roisyi als. quroisyi bin ahmad zalih': 'B_DEFN',
 'yahya wahyudi': 'B_JUG',
 'anjar kumboro': 'B_JUG',
 '4 (empat tahun dan 6 (enam) bulan': 'B_PUNI',
 '9 ( sembilan) tahun': 'B_PENA',
 '238/pid.b/2021/pn smp': 'B_VERN',
 '27 januari 2022': 'B_TIMV',
 'yuniar yudha himawan': 'B_JUDP',
 'sugiarto': 'B_REGI',
 'dengan terang - terangan dan dengan tenaga bersama menggunakan kekerasan terhadap orang jika kekerasa n menyebabkan maut': 'B_CRIA',
 'pasal 170 ayat (2) ke -3 kuhp': 'B_ARTV'}

In [ ]:
accuracy(count_label)

Dokumen Ke-0 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-1 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-2 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-3 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-4 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-5 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-6 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-7 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-8 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-9 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-10 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-11 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-12 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-13 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-14 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-15 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-16 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-17 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-18 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-19 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-20 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-21 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-22 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-23 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-24 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-25 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-26 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-27 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-28 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-29 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-30 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-31 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-32 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-33 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-34 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-35 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-36 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-37 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-38 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-39 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-40 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-41 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-42 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-43 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-44 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-45 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-46 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-47 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-48 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-49 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-50 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-51 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-52 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-53 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-54 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-55 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-56 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-57 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-58 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-59 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-60 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-61 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-62 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-63 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-64 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-65 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-66 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_REGI', 'B_ARTV', 'B_JUDP', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-67 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-68 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-69 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-70 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-71 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-72 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-73 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-74 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_REGI', 'B_ARTV', 'B_JUDP', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-75 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-76 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-77 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-78 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-79 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-80 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-81 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-82 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-83 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-84 => Data Terlebel : 10 ; Total Label : 11 ; Label Hilang : {'B_PENA'} ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-85 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-86 => Data Terlebel : 11 ; Total Label : 10 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-87 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-88 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-89 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-90 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-91 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-92 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-93 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-94 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-95 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}
Dokumen Ke-96 => Data Terlebel : 11 ; Total Label : 11 ; Label Hilang : set() ; Label Ditemukan: {'B_JUG', 'B_PUNI', 'B_PENA', 'B_JUDP', 'B_ARTV', 'B_REGI', 'B_CRIA', 'B_PROS', 'B_VERN', 'B_DEFN', 'B_TIMV'}

'Accuracy : 98.47467968273338'

### Cek anotasi pada satu dokumen

In [ ]:
# idx = 22
# new_data[idx:idx+1]

In [ ]:
# entities[idx:idx+1] 21 255 259

In [ ]:
labels[597]

{'nur fajjriy ah': 'B_PROS',
 'zaiful islam bin mudirun': 'B_DEFN',
 'anjar kumboro': 'B_JUG',
 'muhammad arief fatony': 'B_JUG',
 '5 (lima) tahun,': 'B_PUNI',
 '7 (tujuh) tahun': 'B_PENA',
 '274/pid.sus/2021/pn smp': 'B_VERN',
 '20 januari 2022': 'B_TIMV',
 'yahya wahyudi': 'B_JUDP',
 'edi haris mulyono': 'B_REGI',
 'dengan sengaja membujuk anak melakukan persetubuhan dengannya': 'B_CRIA',
 'pasal 81 ayat (2) undang - undang republik indonesia nomor 17 tahun 2016 tentang perubahan undang - undang republik indonesia nomor 35 tahun 2014, tentang perl indungan anak,': 'B_ARTV'}

In [ ]:
filtered_rows = new_df.loc[new_df['doc'] == f'doc:{568}']
text_example = []
for sentence_tokens in filtered_rows['text']:
    text_example.extend(sentence_tokens)
label_example = []
for sentence_tokens in filtered_rows['label']:
    label_example.extend(sentence_tokens)
print(text_example)
print(label_example)

['putusan', 'nomor', '33/pid.b/2022/pn', 'smp', 'demi', 'keadilan', 'berdasarkan', 'ketuhanan', 'yang', 'maha', 'esa', 'pengadilan', 'negeri', 'sumenep', 'yang', 'mengadili', 'perkara', 'pidana', 'dengan', 'acara', 'pemeri', 'ksaan', 'biasa', 'dalam', 'tingkat', 'pertama', 'menjatuhkan', 'putusan', 'sebagai', 'berikut', 'dalam', 'perkara', 'terdakwa', ':', '1.', 'nama', 'lengkap', ':', 'sutipno', 'bin', 'abdullah', ';', '2.', 'tempat', 'lahir', ':', 'kabupaten', 'sumenep', ';', '3.', 'umur/tanggal', 'lahir', ':', '41', 'tahun', '/1', 'februari', '1981', '4.', 'jenis', 'kelamin', ':', 'laki', '-laki', ';', '5.', 'kebangsaan', ':', 'indonesia', ';', '6.', 'tempat', 'tinggal', ':', 'dusun', 'janjang', 'desa', 'bulla', '’an,', 'kecamatan', 'batuputih', ',', 'kabupaten', 'sumenep', ';', '7.', 'agama', ':', 'islam', ';', '8.', 'pekerjaan', ':', 'petani/pekebun', ';', 'terdakwa', 'ditangkap', 'pada', 'tanggal', '25', 'oktober', '2021', 'dan', 'ditahan', 'dalam', 'tahanan', 'rutan', 'oleh:', '1.', 'penyidik', 'sejak', 'tanggal', '26', 'oktober', '2021', 'sampai', 'dengan', 'tanggal', '14', 'november', '2021', ';', '2.', 'penyidik', 'perpanjangan', 'oleh', 'penuntut', 'umum', 'sejak', 'tanggal', '15', 'november', '2021', 'sampai', 'dengan', 'tanggal', '24', 'desember', '2021;', '3.', 'penyidik', 'perpanj', 'angan', 'pertama', 'oleh', 'ketua', 'pengadilan', 'negeri', 'sejak', 'tanggal', '25', 'desember', '2021', 'sampai', 'dengan', 'tanggal', '23', 'januari', '2022', ';', '4.', 'penuntut', 'umum', 'sejak', 'tanggal', '20', 'januari', '2022', 'sampai', 'dengan', 'tanggal', '8', 'februari', '2022', ';', '5.', 'hakim', 'pengadilan', 'negeri', 'sejak', 'tanggal', '3', 'februari', '2', '22', 'sampai', 'dengan', 'tanggal', '4', 'maret', '2022', ';', '6.', 'hakim', 'pengadilan', 'negeri', 'perpanjangan', 'pertama', 'oleh', 'ketua', 'pengadilan', 'negeri', 'sejak', 'tanggal', '5', 'maret', '2022', 'sampai', 'dengan', 'tanggal', '3', 'mei', '2022', ';', 'terdakwa', 'menghadap', 'sendiri', 'tanpa', 'didampingi', 'oleh', 'penasihat', 'hukum', ';', 'pengadilan', 'negeri', 'tersebut', ';', 'setelah', 'membaca', ':', 'pid.i.a.3', '-', 'penetapan', 'ketua', 'pengadilan', 'negeri', 'sumenep', 'nomor', '33/pid.b/2022/pn', 'smp', 'tanggal', '3', 'februari', '2022', 'tentang', 'penunjukan', 'majelis', 'hakim', ';', '-', 'penetapan', 'majelis', 'hakim', 'nomor', '33/pid.b/2022/pn', 'smp', 'tanggal', '3', 'februari', '2022', 'tentang', 'penetapan', 'hari', 'sidang', ';', '-', 'berkas', 'perkara', 'dan', 'sur', 'at-surat', 'lain', 'yang', 'bersangkutan', ';', 'setelah', 'mendengar', 'keterangan', 'saksi-saksi,', 'dan', 'terdakwa', 'serta', 'memperhatikan', 'barang', 'bukti', 'yang', 'diajukan', 'di', 'persidangan', ';', 'setelah', 'mendengar', 'pembacaan', 'tuntutan', 'pidana', 'yang', 'diajukan', 'oleh', 'penuntut', 'umum', 'yang', 'pada', 'pokoknya', 'sebagai', 'berikut', ':', '1.', 'menyatakan', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'terbukti', 'secara', 'sah', 'dan', 'meyakinkan', 'melakukan', 'tindak', 'pidana', 'pencurian', 'dengan', 'pemberatan', 'sebagaimana', 'pasal', '363', 'ayat', '(1)', 'ke', '3', 'kuhp.', '2.', 'menjatuhkan', 'pidana', 'atas', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'pidana', 'penjara', 'selama', '2', '(dua)', 'tahun', 'dan', '6', '(enam)', 'bula', 'n.', '3.', 'menetapkan', 'agar', 'barang', 'bukti', 'berupa', ':', '4.', '1', 'buah', 'dompet', 'warna', 'coklat,', '1', 'unit', 'ha', 'd', 'pone', 'merek', 'vivo', '12', 'dan', '1', 'unit', 'hand', 'pone', 'merek', 'samsung', 'j1', 'prime', 'dikembalikan', 'ke', 'saksi', 'kisrowiyah', 'sedangkan', '3', 'buah', 'bonsai', 'dan', 'satu', 'bu', 'ah', 'cangkul', 'dirampas', 'untuk', '5', '5.', 'menetapkan', 'agar', 'terdakwa', 'juga', 'dibebani', 'untuk', 'membayar', 'biaya', 'perkara', 'sebesar', 'rp', '5000.', '-', '(lima', 'ribu', 'rupiah).', 'setelah', 'mendengar', 'permohonan', 'terdakwa', 'yang', 'pada', 'pokoknya', 'menyatakan', 'memohon', 'keringanan', 'hukuman', 'karena', 'terdakwa', 'merupakan', 'tulang', 'punggung', 'keluarga', 'ser', 'ta', 'menyesal', 'dan', 'berjanji', 'tidak', 'akan', 'mengulangi', 'perbuatannya', 'lagi;', 'setelah', 'mendengar', 'tanggapan', 'penuntut', 'umum', 'terhadap', 'permohonan', 'terdakwa', 'yang', 'pada', 'pokoknya', 'tetap', 'pada', 'tuntutannya;', 'setelah', 'mendengar', 'tanggapan', 'terdakwa', 'terhadap', 'tanggapan', 'penuntut', 'umum', 'yang', 'pada', 'pokoknya', 'tetap', 'pada', 'permohonannya;', 'menimbang,', 'bahwa', 'terdakwa', 'diajukan', 'ke', 'persidangan', 'oleh', 'penuntut', 'umum', 'didakwa', 'berdasarkan', 'surat', 'dakwaan', 'sebagai', 'berikut:', 'dakwaan', 'bahwa', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'pada', 'hari', 'selasa', 'tanggal', '7', 'september', '2021', 'sekira', 'jam', ':', '20.0', 'wib', 'atau', 'setidak', '-tidaknya', 'pada', 'suatu', 'waktu', 'dalam', 'bulan', 'september', '2021', ',', 'atau', 'setidak', '-tidaknya', 'pada', 'suatu', 'waktu', 'dalam', 'tahun', '2021', 'bertempat', 'rumah', 'saksi', 'kisrowiya', 'didusun', 'kacceng', 'desa', 'semaan', 'kab.', 'sumenep', ',', 'atau', 'setidak', '-tidak', 'nya', 'disuatu', 'tempat', 'lain', 'yang', 'masih', 'termasuk', 'dalam', 'daerah', 'hukum', 'pengadilan', 'negeri', 'sumenep,', 'mengambil', 'barang', 'sesuatu', 'berupa', ':', '3', 'unit', 'hand', 'pone', ',yang', 'sebagian', 'at', 'au', 'seluruhnya', 'kepunyaan', 'orang', 'lain,', 'dengan', 'maksud', 'dimiliki', 'dengan', 'melawan', 'hukum', ',', 'dilakukan', 'pada', 'malam', 'hari', 'dalam', 'sebuah', 'rumah', 'yang', 'tertutup', ',untuk', 'masuk', 'kedalam', 'dilakukan', 'dengan', 'merusak', '.', 'perbuatan', 'tersebut', 'dilakukan', 'oleh', 'terdakwa', 'dengan', 'cara', '-', 'cara', 'seb', 'agai', 'berikut', ':', 'berawal', 'ia', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'pada', 'hari', 'selasa', 'tanggal', '7', 'september', '2021', 'sekira', 'jam', ':', '20.0', 'wibingin', 'melakukan', 'pencurian', ',', 'lalu', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'melihat', 'rumah', 'milik', 'saksi', 'kisrowiya', 'didusun', 'kacceng', 'desa', 'semaan', 'kab.', 'sum', 'enep', 'dalam', 'keadaan', 'sepi', '.', 'selanjutnya', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'masuk', 'kehalaman', 'rumah', 'tersebut,lalu', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'mengambil', 'sebuah', 'cangkul', 'kecil', 'yang', 'ada', 'dibelakang', 'rumah', 'tersebut,', 'lalu', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'mencongkel', 'jendela', 'd', 'engan', 'menggunakan', 'sebuah', 'cangkul.', 'setelah', 'terbuka', 'jendela', ',lalu', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'masuk', 'kedalam', 'kamar', 'rumah', ',lalu', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'melihat', 'dan', 'mengambil', '1', '(satu)', 'unit', 'hand', 'pone', 'j2', 'prime', 'warna', 'putih', ',lalu', 'terdakwa', 'menuju', 'keruang', 'ta', 'mu', 'ada', '4', 'orang', 'yang', 'sedang', 'tidur', 'dan', 'terdakwa', 'mengambil', '2', 'unit', 'hand', 'pone', 'masing', '-masing', '1', 'unit', 'hand', 'pone', 'merk', 'vivo', 'y12', 'warna', 'biru,', 'hand', 'pone', 'samsung', 'b310', 'warna', 'dongker', 'dan', 'dompet', 'warna', 'coklat', 'yang', 'ditafsir', '3', 'unit', 'hanpoe', 'tersebut', 'keseluruhan', 'seharga', 'rp.', '4.10.0,', '-', '(emopat', 'juta', 'seratus', 'ribu', 'rupiah),terdakwa', 'yang', 'mengambil', '3', 'unit', 'hand', 'pone', 'tanpa', 'seijin', 'pemeliknya', 'antara', 'lain', 'saksi', 'kisrowiya', 'pulang', 'kerum', 'ahnya.', 'kemudian', 'pada', 'hari,', 'tanggal', 'yang', 'tidak', 'diingat', 'lagi', 'dengan', 'pasti', 'bulan', 'september', '2021', 'sekira', 'jam', ':', '9.0', 'wib', 'saksi', 'm.', 'lasmino', 'bin', 'sulaiman', 'didatangi', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'untuk', 'menawarkan', '2', 'unit', 'hand', 'pone', 'masing', '-masing', '1', 'unit', 'hand', 'pone', 'merk', 'vivo', '12', 'dan', '1', 'unit', 'hand', 'pone', 'merk', 'samsung', 'j2', 'prime', 'yang', 'diperoleh', 'dari', 'hasil', 'kejatan', 'dan', 'saksi', 'sutipn', 'o', 'butuh', 'sekali', 'karena', 'akan', 'membayar', '/mengirim', 'kepada', 'anaknya', 'yang', 'sedang', 'mondok', 'meminta', 'tolong', 'kepada', 'saksi', 'm.', 'lasmino', 'bin', 'sulaiman', 'seharga', 'rp.', '800.0,', '-', '(delapan', 'ratus', 'ribu', 'rupiah)', 'perbuatan', 'terdakwa', 'tersebut', 'diatur', 'dan', 'dianca', 'm', 'pidana', 'dalam', 'pasal', '363', 'ay', 'at', '(1)', 'ke.', '3,4', 'kuhp', 'menimbang,', 'bahwa', 'terhadap', 'dakwa', 'an', 'penuntut', 'umum,', 'terdakwa', 'tidak', 'mengajukan', 'keberatan', ';', 'menimbang,', 'bahwa', 'untuk', 'membuktikan', 'dakwaannya', 'penuntut', 'umum', 'telah', 'mengaju', 'kan', 'saksi-saksi', 'yang', 'sebelum', 'memberikan', 'keterangan', 'disumpah', 'dan', 'menerangkan', 'pada', 'pokoknya', 'sebagai', 'berikut', ':', '1.', 'saksi', 'kisrowiya:', '-', 'bahwa', 'saksi', 'dihadirkan', 'di', 'persidangan', 'karena', 'hilangnya', 'barang', 'milik', 'saksi;', '-', 'bahwa', 'barang', 'yang', 'hilang', 'adalah', '3', '(tiga)', 'buah', 'handphone,', 'uang', 'sejumlah', 'rp.1.0.0,', '-', '(satu', 'juta', 'rupiah)', 'dan', 'sebuah', 'dompet', 'yang', 'berisi', 'uang', 'sejumlah', 'rp.', '12.0,', '-', '(dua', 'belas', 'ribu', 'rupiah);', '-', 'bahwa', 'bahwa', 'barng', 'milik', 'saksi', 'hilang', 'pada', 'hari', 'rabu', 'tanggal', '8', 'septe', 'mber', '2021', 'sekira', 'pukul', '1.0', 'wib', 'bertempat', 'di', 'dalam', 'rumah', 'yang', 'beralamat', 'di', 'dusun', 'kacceng,', 'desa', 'semaan,', 'kecamatan', 'dasuk,', 'kabupaten', 'sumenep;', '-', 'bahwa', 'setahu', 'saksi,', 'orang', 'yang', 'mengambil', 'masuk', 'melalui', 'jendela', 'dengan', 'cara', 'mencongkel', 'dengan', 'cangkul', 'kecil;', '-', 'bahw', 'a', 'barang', 'bukti', 'yang', 'diajukan', 'di', 'persidangan', 'adalah', 'handphone', 'milik', 'saksi', 'yang', 'hilang;', '-', 'terhadap', 'keterangan', 'saksi', 'terdakwa', 'membenarkan', 'dan', 'tidak', 'mengajukan', 'keberatan', ';', '2.', 'saksi', 'm.', 'lasmino', 'bin', 'sulaiman', ':', '-', 'bahwa', 'saksi', 'dihadirkan', 'di', 'persidangan', 'karena', 'telah', 'd', 'itangkap', 'oleh', 'petugas', 'kepolisian;', '-', 'bahwa', 'saksi', 'ditangkap', 'karena', 'telah', 'menjualkan', '2', '(dua)', 'buah', 'hp', 'milik', 'terdakwa;', '-', 'bahwa', 'saksi', 'ditangkap', 'pada', 'hari', 'senin', 'tanggal', '25', 'oktober', '2021', 'sekitar', 'pukul', '18.30', 'di', 'rumah', 'saksi', 'yang', 'beralamat', 'di', 'dusun', 'daja,', 'desa', 'bates,', 'kecamatan', 'dasuk,', 'kabupaten', 'sumenep;', '-', 'bahwa', 'awalnya', 'sekitar', 'bulan', 'september', '2021', 'terdakwa', 'datang', 'ke', 'rumah', 'saksi', 'menawarkan', 'hanphone', 'kepada', 'saksi', 'akan', 'tetapi', 'saksi', 'tidak', 'mau', 'karena', 'terdakwa', 'mengatakan', 'jika', 'handphone', 'tersebut', 'merupakan', 'hasil', 'curian;', '-', 'bahwa', 'menurut', 'terdakwa', 'sedang', 'membutuhkan', 'uang', 'untuk', 'mengirim', 'uang', 'anaknya', 'yang', 'berada', 'di', 'pondok;', '-', 'bahwa', 'selanjutnya', 'terdakwa', 'meminjam', 'uang', 'kepada', 'saksi', 'sejumlah', 'rp.800.0,', '-', '(delapan', 'ratus', 'ribu', 'rupiah)', 'dan', 'saksi', 'memberikan', 'pinjaman;', '-', 'bahwa', 'ketika', 'saksi', 'menagi', 'h', 'terdakwa', 'hanya', 'berjanji', 'saja', 'kemudian', 'terdakwa', 'menyerahkan', '2', '(dua)', 'buah', 'handphone', 'tersebut', 'kepada', 'saksi', 'dan', 'saksi', 'menerimanya', 'karena', 'menurut', 'terdakwa', 'sudah', 'aman;', '-', 'bahwa', 'oleh', 'saksi', 'handphone', 'samsung', 'j2', 'prime', 'dijual', 'dan', 'laku', 'seharga', 'rp.', '900.0,', '-', '(sembila', 'n', 'ratus', 'ribu', 'rupiah);', '-', 'bahwa', 'oleh', 'saksi', 'handphone', 'vivo', 'y12', 'dijual', 'kepada', 'laksono,', 'dan', 'karena', 'laksono', 'hanya', 'mempunyai', 'uang', 'rp.', '600.0,', '-', '(enam', 'ratus', 'ribu', 'rupiah)', 'maka', 'saksi', 'lasmino', 'mengambil', 'bonsai', 'milik', 'laksono;', '-', 'bahwa', 'terhadap', 'foto', 'barang', 'bukti', 'yang', 'dit', 'unjukkan', 'di', 'persidangan', 'saksi', 'membenarkan;', '-', 'terhadap', 'keterangan', 'saksi,', 'terdakwa', 'membenarkan', 'dan', 'tidak', 'mengajukan', 'keberatan;', '3.', 'saksi', 'eko', 'budi', 'santoso;', '-', 'bahwa', 'saksi', 'dihadirkan', 'di', 'pers', 'idangan', 'karena', 'telah', 'melakukan', 'penangkapan', 'terhadap', 'terdakwa', 'dan', 'saksi', 'lasmino;', '-', 'bahwa', 'saksi', 'melakukan', 'penangkapan', 'bersama', 'dengan', 'aipda', 'didik', 'abdurrahman', 'dan', 'anggota', 'dari', 'unit', 'resmob', 'polres', 'sumenep', 'pada', 'hari', 'senin', 'tanggal', '25', 'oktober', '2021', 'sekira', 'pukul', '18.3', '0', 'di', 'rumah', 'terdakwa', 'yang', 'beralamat', 'di', 'dusun', 'daja,', 'desa', 'bates,', 'kecamatan', 'dasuk,', 'kabupaten', 'sumenep', ';', '-', 'bahwa', 'awalnya', 'ada', 'laporan', 'dari', 'warga', 'yang', 'bernama', 'kisrowiya', 'jika', 'ada', 'kejadian', 'pencurian', 'di', 'rumahnya', 'dan', 'kehilangan', '3', '(tiga)', 'buah', 'handphone,', 'uang', 'sejumlah', 'r', 'p.1.0.0,', '-', '(satu', 'juta', 'rupiah)', 'dan', 'sebuah', 'dompet', 'yang', 'berisi', 'uang', 'sejumlah', 'rp.', '12.0,', '-', '(dua', 'belas', 'ribu', 'rupiah);', '-', 'bahwa', 'selanjutnya', 'dilakukan', 'penyelidikan', 'dan', 'diketahui', 'jika', 'yang', 'melakukan', 'pencurian', 'di', 'rumah', 'kisrowiya', 'adalah', 'terdakwa', 'karena', 'berdasarkan', 'informasi', 'dari', 'matrasek', 'teman', 'saksi,', 'jika', 'terdakwa', 'telah', 'meminjam', 'uang', 'dan', 'handphone', 'b310', 'digunakan', 'sebagai', 'jaminan;', '-', 'bahwa', 'berdasarkan', 'informasi', 'laksono', 'kenalan', 'dari', 'saksi', 'jika', 'handphone', 'vivo', 'y2', 'warna', 'biru', 'dibeli', 'dari', 'saksi', 'lasmino', 'dengan', 'harga', 'rp.', '600.0', '0,-', '(enam', 'ratus', 'ribu', 'rupiah)', 'dan', '3', '(tiga)', 'buah', 'bonsai;', '-', 'bahwa', 'ber', 'dasarkan', 'keterangan', 'dari', 'saksi', 'lasmino', ',', 'terdakwa', 'selain', 'memberikan', 'handphone', 'vivo', 'y12', 'warna', 'biru', 'juga', 'memberikan', 'handphone', 'j2', 'prime', 'kepada', 'saksi', 'lasmino', 'yang', 'kemudian', 'dijual', 'oleh', 'saksi', 'lasmi', 'no', 'seharga', 'rp.', '1.0.0,', '-', '(satu', 'juta', 'rupiah);', '-', 'bahwa', 'terdakwa', 'pernah', 'dihukum', 'karena', 'perkara', 'pencurian', 'sepeda', 'motor;', '-', 'terhadap', 'keterangan', 's', 'aksi,', 'terdakwa', 'membenarkan', 'dan', 'tidak', 'mengajukan', 'keberatan;', '4.', 'saksi', 'didik', 'abdurrahman', ';', '-', 'bahwa', 'saksi', 'dihadirkan', 'di', 'persidangan', 'karena', 'telah', 'melakukan', 'penangkapan', 'terhadap', 'terdakwa', 'dan', 'saksi', 'sutipno;', '-', 'bahwa', 'saksi', 'melakukan', 'penangkapan', 'bersama', 'dengan', 'aipda', 'eko', 'budi', 'santoso', 'dan', 'anggota', 'dari', 'unit', 'resmob', 'polres', 'sumenep', 'pada', 'hari', 'senin', 'tanggal', '25', 'oktober', '2021', 'sekira', 'puk', 'ul', '18.30', 'di', 'rumah', 'terdakwa', 'yang', 'beralamat', 'di', 'dusun', 'daja,', 'desa', 'bates,', 'kecamatan', 'dasuk,', 'kabupaten', 'sumenep', ';', '-', 'bahwa', 'awalnya', 'ada', 'laporan', 'dari', 'warga', 'yang', 'bernama', 'kisrowiya', 'jika', 'ada', 'kejadian', 'pencurian', 'di', 'rumahnya', 'dan', 'kehilangan', '3', '(tiga)', 'buah', 'handphone,', 'uang', 'sej', 'umlah', 'rp.1.0.0,', '-', '(satu', 'juta', 'rupiah)', 'dan', 'sebuah', 'dompet', 'yang', 'berisi', 'uang', 'sejumlah', 'rp.', '12.0,', '-', '(dua', 'belas', 'ribu', 'rupiah);', '-', 'bahwa', 'selanjutnya', 'dilakukan', 'penyelidikan', 'dan', 'diketahui', 'jika', 'yang', 'melakukan', 'pencurian', 'di', 'rumah', 'kisrowiya', 'adalah', 'terdakwa', 'karena', 'berda', 'sarkan', 'informasi', 'dari', 'matrasek', 'teman', 'saksi', 'eko', 'budi', 'santoso,', 'terdakwa', 'telah', 'meminjam', 'ua', 'ng', 'dan', 'handphone', 'b310', 'digunakan', 'sebagai', 'jaminan;', '-', 'bahwa', 'berdasarkan', 'informasi', 'laksono', 'kenalan', 'dari', 'saksi', 'eko', 'budi', 'santoso', 'jika', 'handphone', 'vivo', 'y2', 'warna', 'biru', 'dibeli', 'dari', 'saksi', 'lasmino', 'dengan', 'harga', 'rp.', '600.0,', '-', '(enam', 'ratus', 'ribu', 'rupiah)', 'dan', '3', '(tiga)', 'buah', 'bonsai;', '-', 'bahwa', 'selanjutnya', 'saksi', 'melakukan', 'penangkapan', 'terhadap', 'saksi', 'lasmino', ';', '-', 'bahwa', 'dari', 'keterangan', 'dari', 'saksi', 'lasmino', 'jika', 'memperoleh', 'barang', 'bukti', 'tersebut', 'dari', 'terdak', 'wa;', '-', 'bahwa', 'terdakwa', 'pernah', 'dihukum', 'karena', 'perkara', 'pencurian', 'sepeda', 'motor;', '-', 'terhadap', 'keterangan', 's', 'aksi,', 'terdakwa', 'membenarkan', 'dan', 'tidak', 'mengajukan', 'keberatan;', 'menimbang,', 'bahwa', 'terdakwa', 'sutipno', 'bin', 'abdullah', 'di', 'persidangan', 'telah', 'memberikan', 'keterangan', 'yang', 'pada', 'pokoknya', 'sebagai', 'berikut:', '-', 'bahwa', 'terdakwa', 'dihadapkan', 'di', 'persidangan', 'karena', 'telah', 'mengambil', 'barang', 'milik', 'orang', 'lain;', '-', 'bahwa', 'barang', 'yang', 'diambil', 'adalah', '3', '(tiga)', 'buah', 'handphone,', 'uang', 'sejumlah', 'rp.1.0.0', ',-', '(satu', 'juta', 'rupiah)', 'dan', 'sebuah', 'dompet', 'yang', 'berisi', 'uang', 'sejumlah', 'rp.', '12.0,', '-', '(dua', 'belas', 'ribu', 'rupiah);', '-', 'bahawa', 'terdakwa', 'mengambil', 'handphone', 'dan', 'uang', 'tersebut', 'pada', 'hari', 'rabu', 'tanggal', '8', 'september', '2021', 'sekira', 'pukul', '1.0', 'wib', 'bertempat', 'di', 'dalam', 'rumah', 'yang', 'ber', 'alamat', 'di', 'dusun', 'kacceng,', 'desa', 'semaan,', 'kecamatan', 'dasuk,', 'kabupaten', 'sumenep;', '-', 'bahwa', 'saksi', 'mengambil', 'dengan', 'cara', 'masuk', 'ke', 'dalam', 'rumah', 'sebelumnya', 'mencungkil', 'jendela', 'dengan', 'cangkul', 'kecil', 'kemudian', 'masuk', 'dan', 'mengambil', '3', '(tiga)', 'buah', 'handphone,', 'uang', 'sejumlah', 'rp.1.0', '0.0,', '-', '(satu', 'juta', 'rupiah)', 'dan', 'sebuah', 'dompet', 'yang', 'berisi', 'uang', 'sejumlah', 'rp.', '12.0,', '-', '(dua', 'belas', 'ribu', 'rupiah);', '-', 'bahwa', 'kemudian', 'karena', 'terdakwa', 'membutuhkan', 'uang', 'selanjutnya', 'terdakwa', 'menyerahkan', '2', '(dua)', 'buah', 'handphone', 'tersebut', 'kepada', 'saksi', 'lasmino', 'untuk', 'dijualkan', ';', '-', 'bahwa', 'terdakwa', 'mengatakan', 'kepada', 'saksi', 'lasmino', 'jika', 'handphone', 'tersebut', 'diperoleh', 'terdakwa', 'dengan', 'cara', 'milik', 'orang', 'lain', 'akan', 'tetapi', 'saksi', 'lasmino', 'tidak', 'mau', 'menj', 'ualkan', 'lalu', 'terdakwa', 'meminjam', 'uang', 'kepada', 'saksi', 'lasmino', 'sejumlah', 'rp.', '500.0,', '-', '(lima', 'ratus', 'ribu', 'rupiah);', '-', 'bahwa', 'terdakwa', 'ketika', 'mengambil', '3', '(tiga)', 'buah', 'handphone,', 'uang', 'sejumlah', 'rp.1.0.0,', '-', '(satu', 'juta', 'rupiah)', 'dan', 'sebuah', 'dompet', 'yang', 'berisi', 'uang', 'sejumlah', 'rp.', '12.0,', '-', '(dua', 'belas', 'ribu', 'rupiah)', 'tidak', 'meminta', 'ijin', 'kepada', 'pemiliknya', ';', '-', 'bahwa', 'berdasarkan', 'keterangan', 'dari', 'saksi', 'lasmino,', 'terdakwa', 'menyerahkan', 'handphone', 'vivo', 'y12', 'warna', 'biru', 'dan', 'handphone', 'j2', 'prime', 'dari', 'terdakwa', 'yang', 'kemudian', 'dijual', 'seharga', 'rp.', '1.0.0,', '-', '(satu', 'juta', 'rupiah);', '-', 'bahwa', 'ketika', 'saksi', 'menagih', 'terd', 'akwa', 'hanya', 'berjanji', 'saja', 'kemudian', 'terdakwa', 'menyerahkan', '2', '(dua)', 'buah', 'handphone', 'tersebut', 'kepada', 'saksi', 'dan', 'saksi', 'menerimanya', 'karena', 'menurut', 'terdakwa', 'sudah', 'aman;', '-', 'bahwa', 'ketika', 'saksi', 'lasmino', 'menagih', 'terdakwa', 'hanya', 'berjanji', 'saja', 'kemudian', 'terdakwa', 'menyerahkan', '2', '(dua)', 'buah', 'handphone', 'tersebut', 'kepada', 'saksi', 'lasmino', 'dan', 'saksi', 'lasmino', 'menerimanya', 'karena', 'menurut', 'terdakwa', 'sudah', 'aman', 'selanjutnya', 'saksi', 'lasmino', 'menjual', 'hanphone', 'tersebut', 'dengan', 'harga', 'rp.', '900.0,', '-', '(sembilan', 'ratus', 'ribu', 'rupiah);', '-', 'bahwa', 'terdakwa', 'menyesal', 'dan', 'b', 'erjanji', 'tidak', 'akan', 'mengulangi', 'perbuatannya', 'lagi;', 'menimbang,', 'bahwa', 'terdakwa', 'tidak', 'mengajukan', 'saksi', 'yang', 'meringankan', '(a', 'de',

In [ ]:
for token, label in zip(text_example, label_example):
  if label != 'O' or token == ' ':
    print(f"Token Text : {token} => {label}")

Token Text : 58/pid.sus/2022/pn => B_VERN
Token Text : pmk => I_VERN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : 58/pid.sus/2022/pn => B_VERN
Token Text : pmk, => I_VERN
Token Text : 58/pid.sus/2022/pn => B_VERN
Token Text : pmk => I_VERN
Token Text : 58/pid.sus/2022/pn => B_VERN
Token Text : pmk => I_VERN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : pasal => B_ARTV
Token Text : 112 => I_ARTV
Token Text : ayat => I_ARTV
Token Text : (1) => I_ARTV
Token Text : uu => I_ARTV
Token Text : ri => I_ARTV
Token Text : no.35 => I_ARTV
Token Text : tahun => I_ARTV
Token Text : 2009 => I_ARTV
Token Text : rudi => B_DEFN
Token Text : mulyanto => I_DEFN
Token Text : bin => I_DEFN
Token Text : aswin => I_DEFN
Token Text : melawan => B_CRIA
Token Text : hukum => I_CRIA
Token Text : memilik => I_CRIA
Token Text : dan => I_CRIA
Token Text : menguasai => I_CRIA
Token Text : narkotika => I_CRIA
Token Text : golongan => I_CRIA
Token Text : i => I_CRIA
Token Text : bukan => I_CRIA
Token Text : tanaman => I_CRIA
Token Text : 6 => B_PENA
Token Text : (enam) => I_PENA
Token Text : tahun => I_PENA
Token Text : , => I_PENA
Token Text : yuklayushi => B_JUDP
Token Text : ,saiful => B_JUG
Token Text : brow => I_JUG
Token Text : anastasia => B_JUG
Token Text : irene => I_JUG
Token Text : 11 => B_TIMV
Token Text : mei => I_TIMV
Token Text : 2022 => I_TIMV
Token Text : m. => B_REGI
Token Text : syaiful => I_REGI
Token Text : rachem, => I_REGI
Token Text : yurike => B_PROS
Token Text : adriana => I_PROS
Token Text : arief => I_PROS
Token Text : ,saiful => B_JUG
Token Text : brow => I_JUG
Token Text : yuklayushi => B_JUDP
Token Text : anastasia => B_JUG
Token Text : irene => I_JUG
Token Text : m. => B_REGI
Token Text : syaiful => I_REGI
Token Text : rachem => I_REGI

In [ ]:
looked_doc = new_df[new_df["doc"] == f"doc:{405}"]
unique_labels = set(label for sublist in looked_doc['label'] for label in sublist)
unique_labels

{'B_ARTV',
 'B_CRIA',
 'B_DEFN',
 'B_JUDP',
 'B_JUG',
 'B_PROS',
 'B_PUNI',
 'B_REGI',
 'B_TIMV',
 'B_VERN',
 'I_ARTV',
 'I_CRIA',
 'I_DEFN',
 'I_JUG',
 'I_PENA',
 'I_PROS',
 'I_PUNI',
 'I_REGI',
 'I_TIMV',
 'I_VERN',
 'O'}

In [ ]:
# new_df = new_df.iloc[0:500]
new_df

,doc,text,label
0,doc:0,"[putusan, nomor, 48/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
1,doc:1,"[putusan, nomor, 42/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
2,doc:2,"[putusan, nomor, 49/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
3,doc:3,"[putusan, nomor, 56/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
4,doc:4,"[putusan, nomor, 57/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
...,...,...,...
597,doc:597,"[putusan, nomor, 274/pid.sus/2021/pn, smp, dem...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
598,doc:598,"[putusan, nomor, 272/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
599,doc:599,"[putusan, nomor, 220/pid.sus/2021/pn, smp, dem...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
600,doc:600,"[putusan, nomor, 293/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
601,doc:601,"[putusan, nomor, 254/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."

In [ ]:
import tqdm
def cleaning_text(dataset):
  for i, row in tqdm.tqdm(dataset.iterrows(), total=len(dataset), desc="Cleaning text"):
    dataset.at[i, "text"] = [word.replace("\ufeff", "") for word in row["text"]]
    data_text, data_tag = zip(*[(token, label) for token, label in zip(row["text"], row["label"]) if token.strip() != ''])
    dataset.at[i, "text"] = list(data_text)
    dataset.at[i, "label"] = list(data_tag)

  return dataset

cleaning_text(new_df)

Cleaning text: 100%|██████████| 602/602 [00:24<00:00, 24.79it/s]

,doc,text,label
0,doc:0,"[putusan, nomor, 48/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
1,doc:1,"[putusan, nomor, 42/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
2,doc:2,"[putusan, nomor, 49/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
3,doc:3,"[putusan, nomor, 56/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
4,doc:4,"[putusan, nomor, 57/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
...,...,...,...
597,doc:597,"[putusan, nomor, 274/pid.sus/2021/pn, smp, dem...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
598,doc:598,"[putusan, nomor, 272/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
599,doc:599,"[putusan, nomor, 220/pid.sus/2021/pn, smp, dem...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
600,doc:600,"[putusan, nomor, 293/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
601,doc:601,"[putusan, nomor, 254/pid.b/2021/pn, smp, demi,...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."

### Split dokumen data per kata

In [ ]:
def split_token(dataset):
  for i, row in tqdm.tqdm(dataset.iterrows(), total=len(dataset), desc="Processing rows"):
    for index, (text, tag) in enumerate(zip(row["text"], row["label"])):
      if tag != "O":
        token = re.findall(r'[^\/,\.():;]+|[\/\.,():;]', text)
        add_label = []
        for i in range(len(token)):
          if 'B' in tag and not add_label:
            add_label.append(tag)
          else:
            if token[i] != ';':
              add_label.append(tag.replace('B', 'I'))
            else:
              add_label.append('O')

        del row["text"][index]
        del row["label"][index]
        row["text"][index:index] = token
        row["label"][index:index] = add_label
      else:
        token = re.findall(r'[^\/,\.():;]+|[\/\.,():;]', text)
        add_label = []
        for i in range(len(token)):
          add_label.append('O')

        del row["text"][index]
        del row["label"][index]
        row["text"][index:index] = token
        row["label"][index:index] = add_label
  return dataset

split_token(new_df)

Processing rows: 100%|██████████| 602/602 [01:17<00:00,  7.80it/s]

,doc,text,label
0,doc:0,"[putusan, nomor, 48, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
1,doc:1,"[putusan, nomor, 42, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
2,doc:2,"[putusan, nomor, 49, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
3,doc:3,"[putusan, nomor, 56, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
4,doc:4,"[putusan, nomor, 57, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
...,...,...,...
597,doc:597,"[putusan, nomor, 274, /, pid, ., sus, /, 2021,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
598,doc:598,"[putusan, nomor, 272, /, pid, ., b, /, 2021, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
599,doc:599,"[putusan, nomor, 220, /, pid, ., sus, /, 2021,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
600,doc:600,"[putusan, nomor, 293, /, pid, ., b, /, 2021, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
601,doc:601,"[putusan, nomor, 254, /, pid, ., b, /, 2021, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."

### Membagi Data kolom Sentence

In [ ]:
new_rows = []
for index, row in new_df.iterrows():
    sentences = []
    tags = []
    sentence = []
    tag = []
    for word, tag_word in zip(row['text'], row['label']):
      if word != ';':
          sentence.append(word)
          tag.append(tag_word)
      else:
          if sentence:
              sentences.append(sentence)
              tags.append(tag)
          sentence = []
          tag = []
    if sentence:
      sentences.append(sentence)
      tags.append(tag)
    for sentence, tag in zip(sentences, tags):
      new_rows.append({
          'text': sentence,
          'label': tag,
          'doc': row['doc']
      })
new_df = pd.DataFrame(new_rows)
new_df

,text,label,doc
0,"[putusan, nomor, 48, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc:0
1,"[pengadilan, negeri, tersebut]","[O, O, O]",doc:0
2,"[setelah, membaca, :, -penetapan, ketua, penga...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_...",doc:0
3,"[-penetapan, majelis, hakim, nomor, 48, /, pid...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I...",doc:0
4,"[-berkas, perkara, dan, surat-surat, lain, yan...","[O, O, O, O, O, O, O]",doc:0
...,...,...,...
78257,"[3, ., menetapkan, masa, penangkapan, dan, pen...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc:601
78258,"[4, ., menetapkan, terdakwa, tetap, ditahan]","[O, O, O, O, O, O]",doc:601
78259,"[5, ., menetapkan, barang, bukti, berupa, :, -...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc:601
78260,"[6, ., membebankan, kepada, terdakwa, membayar...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc:601
78261,"[demikian, diputuskan, dalam, sidang, permusya...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc:601

In [ ]:
new_df['sentence'] = new_df.index.map(lambda x: f'sentence: {x + 1:06}')
new_df

,text,label,doc,sentence
0,"[putusan, nomor, 48, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc:0,sentence: 000001
1,"[pengadilan, negeri, tersebut]","[O, O, O]",doc:0,sentence: 000002
2,"[setelah, membaca, :, -penetapan, ketua, penga...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_...",doc:0,sentence: 000003
3,"[-penetapan, majelis, hakim, nomor, 48, /, pid...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I...",doc:0,sentence: 000004
4,"[-berkas, perkara, dan, surat-surat, lain, yan...","[O, O, O, O, O, O, O]",doc:0,sentence: 000005
...,...,...,...,...
78257,"[3, ., menetapkan, masa, penangkapan, dan, pen...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc:601,sentence: 078258
78258,"[4, ., menetapkan, terdakwa, tetap, ditahan]","[O, O, O, O, O, O]",doc:601,sentence: 078259
78259,"[5, ., menetapkan, barang, bukti, berupa, :, -...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc:601,sentence: 078260
78260,"[6, ., membebankan, kepada, terdakwa, membayar...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc:601,sentence: 078261
78261,"[demikian, diputuskan, dalam, sidang, permusya...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc:601,sentence: 078262

### Tokenisasi menjadi per kata

In [ ]:
tokens = []
tags = []
docs = []
sentences = []
for i, row in new_df.iterrows():
    for token, tag in zip(row['text'], row['label']):
        tokens.append(token)
        tags.append(tag)
        docs.append(row['doc'])
        sentences.append(row['sentence'])
tokenized_df = pd.DataFrame({
    'text': tokens,
    'label': tags,
    'doc': docs,
    'sentence': sentences
})
tokenized_df

              text   label      doc          sentence
0          putusan       O    doc:0  sentence: 000001
1            nomor       O    doc:0  sentence: 000001
2               48  B_VERN    doc:0  sentence: 000001
3                /  I_VERN    doc:0  sentence: 000001
4              pid  I_VERN    doc:0  sentence: 000001
...            ...     ...      ...               ...
4082187   panitera       O  doc:601  sentence: 078262
4082188  pengganti       O  doc:601  sentence: 078262
4082189          ,       O  doc:601  sentence: 078262
4082190        ttd       O  doc:601  sentence: 078262
4082191     suraji  B_REGI  doc:601  sentence: 078262

[4082192 rows x 4 columns]

### Menambahkan Kolom Prev dan Next

In [ ]:
tokenized_df['prev'] = tokenized_df['text'].shift(1)
tokenized_df['next'] = tokenized_df['text'].shift(-1)
tokenized_df['prev'].fillna('.', inplace=True)
tokenized_df['next'].fillna('.', inplace=True)

In [ ]:
tokenized_df

              text   label      doc          sentence       prev       next
0          putusan       O    doc:0  sentence: 000001          .      nomor
1            nomor       O    doc:0  sentence: 000001    putusan         48
2               48  B_VERN    doc:0  sentence: 000001      nomor          /
3                /  I_VERN    doc:0  sentence: 000001         48        pid
4              pid  I_VERN    doc:0  sentence: 000001          /          .
...            ...     ...      ...               ...        ...        ...
4082187   panitera       O  doc:601  sentence: 078262          .  pengganti
4082188  pengganti       O  doc:601  sentence: 078262   panitera          ,
4082189          ,       O  doc:601  sentence: 078262  pengganti        ttd
4082190        ttd       O  doc:601  sentence: 078262          ,     suraji
4082191     suraji  B_REGI  doc:601  sentence: 078262        ttd          .

[4082192 rows x 6 columns]

In [ ]:
proces_data = tokenized_df.rename(columns={'text': 'word', 'label': 'tag'}).reindex(columns=['doc','sentence', 'word', 'prev', 'next', 'tag'])
proces_data

             doc          sentence       word       prev       next     tag
0          doc:0  sentence: 000001    putusan          .      nomor       O
1          doc:0  sentence: 000001      nomor    putusan         48       O
2          doc:0  sentence: 000001         48      nomor          /  B_VERN
3          doc:0  sentence: 000001          /         48        pid  I_VERN
4          doc:0  sentence: 000001        pid          /          .  I_VERN
...          ...               ...        ...        ...        ...     ...
4082187  doc:601  sentence: 078262   panitera          .  pengganti       O
4082188  doc:601  sentence: 078262  pengganti   panitera          ,       O
4082189  doc:601  sentence: 078262          ,  pengganti        ttd       O
4082190  doc:601  sentence: 078262        ttd          ,     suraji       O
4082191  doc:601  sentence: 078262     suraji        ttd          .  B_REGI

[4082192 rows x 6 columns]

### Save hasil anotasi

In [ ]:
proces_data.to_csv('Dataset-500PidanaPolBGTNITerbaru.csv', index=False)