In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm
import pandas as pd
import gdown
import re

In [2]:
gdown.download(f'https://drive.google.com/uc?id=1Qsv_YV5WcRSgX8OQoH7R3Rp2n_CFY--2', "Dataset Perdata Melawan Hukum 240.csv", quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1Qsv_YV5WcRSgX8OQoH7R3Rp2n_CFY--2
To: /content/Dataset Perdata Melawan Hukum 240.csv
100%|██████████| 18.1M/18.1M [00:00<00:00, 36.6MB/s]

'Dataset Perdata Melawan Hukum 240.csv'

In [3]:
df = pd.read_csv("Dataset Perdata Melawan Hukum 240.csv")
df

,url_page,penggugat,tergugat,turut_tergugat,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,...,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,abstrak,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"Amirul Muchtar, SE",1.Ketua Umum DPP Partai NasDem. Bpk Surya Palo...,NaN,698/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,17 Nopember 2021,...,Lain-lain,PENGADILAN TIDAK BERWENANG,1. Mengabulkan eksepsi kompetensi absolut para...,9 Agustus 2022,9 Agustus 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,698_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 698/Pdt.G/2021/PN Jkt.Pst . DEMI...
1,https://putusan3.mahkamahagung.go.id/direktori...,Henri Kusuma,"1.Erman Umar,SH 2.ZEESHA FATMA DEFAGA, SH 3.PR...",Dewan Pimpinan Pusat Kongres Advokat Indonesia,306/Pdt.G/2022/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,8 Juni 2022,...,Lain-lain,DICABUT,M E N E T A P K A N: Mengabulkan permohonan pe...,4 Agustus 2022,4 Agustus 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,306_Pdt.G_2022_PN_Jkt.Pst.pdf,PENETAPAN Nomor 306/Pdt.G/2022/PN.Jkt.Pst DEMI...
2,https://putusan3.mahkamahagung.go.id/direktori...,Chris Inderayanto,PT. Bank Negara Indonesia (persero) Tbk,Pemerintah Republik Indonesia Cq Kementrian Ke...,643/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,22 Oktober 2021,...,Lain-lain,DITOLAK,M E N G A D I L I DALAM EKSEPSI. Menolak Eksep...,8 Agustus 2022,8 Agustus 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,643_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 643/Pdt.G/2022/PN. Jkt Pst DEMI ...
3,https://putusan3.mahkamahagung.go.id/direktori...,H. RAYAN NURACHMAN,ISLAMIATI LEDIANA,"1.PT. BANK RAKYAT INDONESIA Tbk., 2.KEPALA KAN...",534/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,7 September 2021,...,Lain-lain,MENGABULKAN EKSEPSI,MengadiliDALAM EKSEPSI1. Mengabulkan Eksepsi P...,19 Juli 2022,19 Juli 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,534_Pdt.G_2021_PN_Jkt.Pst.pdf,I.PUTUSAN Nomor 534/Pdt.G/2020/PN Jkt Pst II.D...
4,https://putusan3.mahkamahagung.go.id/direktori...,1.Binaresti Dewi 2.Mulyono Sucitro 3.Chintya S...,1.PT Asuransi Jiwasraya (Persero) 2.Otoritas J...,NaN,818/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,30 Desember 2021,...,Lain-lain,MENGABULKAN EKSEPSI,MENGADILI: Mengabulkan eksepsi Tergugat I dan ...,11 Agustus 2022,11 Agustus 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,818_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 818/Pdt.G/2021/PN Jkt.Pst DEMI K...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,https://putusan3.mahkamahagung.go.id/direktori...,Tjeng Whie Bien,Moch. Usman,"1.Notaris Dian Silviyana Khusnarini, S.H. 2.Ka...",625/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,22 Juni 2023,...,Lain-lain,DICABUT,M E N E T A P K A N Mengabulkan permohonan pen...,13 Juli 2023,13 Juli 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,625_Pdt.G_2023_PN_Sby.pdf,PENETAPAN Nomor 625/Pdt.G/2023/PN.Sby. DEMI KE...
236,https://putusan3.mahkamahagung.go.id/direktori...,"1.H.PUGUH SANTOSO, SE 2.Hj SYOFIA, Dra 3.INTAN...",1.PT.BANK RAKYAT INDONESIA TBK 2.KPKNL KABUPAT...,NaN,1070/Pdt.G/2022/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,30 September 2022,...,Lain-lain,DITOLAK,MENGADILI:Dalam Eksepsi Menolak eksepsi Para T...,12 Juli 2023,12 Juli 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,1070_Pdt.G_2022_PN_Sby.pdf,PUTUSAN Nomor 1070/Pdt.G/2022/PN Sby DEMI KEAD...
237,https://putusan3.mahkamahagung.go.id/direktori...,Heriyani Santoso,1.Hianto Sulistio 2.Mianto Sulistio 3.Winarto ...,Kantor Pertanahan Kota Surabaya II,455/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,15 Mei 2023,...,Lain-lain,DICABUT,Menyatakan Gugatan Penggugat dicabut ; Menyata...,12 Juli 2023,12 Juli 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,455_Pdt.G_2023_PN_Sby.pdf,P E N E T A P A N Nomor 455/Pdt.G/2023/PN.Sby ...
238,https://putusan3.mahkamahagung.go.id/direktori...,HARI BOEDI ROESTANTO,1.PT. PERTAMINA (Persero) 2.KANTOR AGRARIA DAN...,NaN,928/Pdt.G/2022/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,29 Agustus 2022,...,Lain-lain,PENGADILAN TIDAK BERWENANG,M E N G A D I L I : 1. Menyatakan Pengadilan N...,12 Juli 2023,12 Juli 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,928_Pdt.G_2022_PN_Sby.pdf,PUTUSAN Nomor 928/Pdt.G/2022/PN.Sby. DEMI KEAD...
239,https://putusan3.mahkamahagung.go.id/direktori...,SUSAN TAMIN,"1.PT. BANK UOB INDONESIA, TBK 2.DANIEL CHRISTI...",NaN,960/Pdt.G/2022/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,6 September 2022,...,Lain-lain,DIKABULKAN SEBAGIAN,MENGADILI:Dalam Eksepsi : Menolak eksepsi Terg...,4 Mei 2023,4 Mei 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,960_Pdt.G_2022_PN_Sby.pdf,Halaman 1 Putusan Nomor 960/Pdt.G/ 2022 /PN Sb...

In [4]:
df_200 = df.iloc[0:200]
df_200

,url_page,penggugat,tergugat,turut_tergugat,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,...,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,abstrak,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"Amirul Muchtar, SE",1.Ketua Umum DPP Partai NasDem. Bpk Surya Palo...,NaN,698/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,17 Nopember 2021,...,Lain-lain,PENGADILAN TIDAK BERWENANG,1. Mengabulkan eksepsi kompetensi absolut para...,9 Agustus 2022,9 Agustus 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,698_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 698/Pdt.G/2021/PN Jkt.Pst . DEMI...
1,https://putusan3.mahkamahagung.go.id/direktori...,Henri Kusuma,"1.Erman Umar,SH 2.ZEESHA FATMA DEFAGA, SH 3.PR...",Dewan Pimpinan Pusat Kongres Advokat Indonesia,306/Pdt.G/2022/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,8 Juni 2022,...,Lain-lain,DICABUT,M E N E T A P K A N: Mengabulkan permohonan pe...,4 Agustus 2022,4 Agustus 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,306_Pdt.G_2022_PN_Jkt.Pst.pdf,PENETAPAN Nomor 306/Pdt.G/2022/PN.Jkt.Pst DEMI...
2,https://putusan3.mahkamahagung.go.id/direktori...,Chris Inderayanto,PT. Bank Negara Indonesia (persero) Tbk,Pemerintah Republik Indonesia Cq Kementrian Ke...,643/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,22 Oktober 2021,...,Lain-lain,DITOLAK,M E N G A D I L I DALAM EKSEPSI. Menolak Eksep...,8 Agustus 2022,8 Agustus 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,643_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 643/Pdt.G/2022/PN. Jkt Pst DEMI ...
3,https://putusan3.mahkamahagung.go.id/direktori...,H. RAYAN NURACHMAN,ISLAMIATI LEDIANA,"1.PT. BANK RAKYAT INDONESIA Tbk., 2.KEPALA KAN...",534/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,7 September 2021,...,Lain-lain,MENGABULKAN EKSEPSI,MengadiliDALAM EKSEPSI1. Mengabulkan Eksepsi P...,19 Juli 2022,19 Juli 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,534_Pdt.G_2021_PN_Jkt.Pst.pdf,I.PUTUSAN Nomor 534/Pdt.G/2020/PN Jkt Pst II.D...
4,https://putusan3.mahkamahagung.go.id/direktori...,1.Binaresti Dewi 2.Mulyono Sucitro 3.Chintya S...,1.PT Asuransi Jiwasraya (Persero) 2.Otoritas J...,NaN,818/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,30 Desember 2021,...,Lain-lain,MENGABULKAN EKSEPSI,MENGADILI: Mengabulkan eksepsi Tergugat I dan ...,11 Agustus 2022,11 Agustus 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,818_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 818/Pdt.G/2021/PN Jkt.Pst DEMI K...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://putusan3.mahkamahagung.go.id/direktori...,DONI SUSILO,PT MANDIRI TUNAS FINANCE cq. PT MANDIRI TUNAS ...,NaN,787/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,7 Agustus 2023,...,Lain-lain,DICABUT,M E N E T A P K A N : Mengabulkan permohonan p...,6 September 2023,6 September 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,787_Pdt.G_2023_PN_Sby.pdf,PENETAPAN Nomor. 787/Pdt.G/2023/PN. Sby. “DEMI...
196,https://putusan3.mahkamahagung.go.id/direktori...,PT. Granting Jaya,PT. Bahagia Bersama Jaya,1.ALI SAMSUNI 2.ABDUL HALIM 3.IWAN BUANA 4.ZAI...,190/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,17 Februari 2023,...,Lain-lain,MENGABULKAN EKSEPSI,Mengabulkan Eksepsi Turut Tergugat XII; Menyat...,6 September 2023,6 September 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,190_Pdt.G_2023_PN_Sby.pdf,PUTUSAN SELA Nomor 190/Pdt.G/2023/PN.Sby. DEMI...
197,https://putusan3.mahkamahagung.go.id/direktori...,ANUGRAH YUDO WITJAKSONO,1.PT. PRIMA MASTER BANK (PRIMA BANK) 2.AGUS TR...,2.OTORITAS JASA KEUANGAN (OJK) 3.IR. DANIEL SU...,52/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,16 Januari 2023,...,Lain-lain,DITOLAK,MENGADILI: Menolak gugatan Penggugat seluruhny...,4 September 2023,4 September 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,52_Pdt.G_2023_PN_Sby.pdf,PUTUSAN Nomor 52/Pdt G/2023/PN Sby DEMI KEADIL...
198,https://putusan3.mahkamahagung.go.id/direktori...,Sylvia Kumala Saridewi,1.PT. Bank Commonwealth 2.Kepala Kantor Pelaya...,NaN,680/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,10 Juli 2023,...,Lain-lain,DICABUT,M E N E T A P K A N Menyatakan gugatan yang di...,31 Agustus 2023,31 Agustus 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,680_Pdt.G_2023_PN_Sby.pdf,P E N E T A P A N Nomor 680/Pdt.G/2023/PN Sby....
199,https://putusan3.mahkamahagung.go.id/direktori...,SANTOSO RYANTO,1.PT. BANK SAHABAT SAMPOERNA CABANG SURABAYA 2...,KEMENTERIAN AGRARIA DAN TATA RUANG/BADAN PERTA...,143/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,6 Februari 2023,...,Lain-lain,DITOLAK,Dalam Provisi : -Menolak tuntutan Provisi Peng...,31 Agustus 2023,31 Agustus 2023,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,143_Pdt.G_2023_PN_Sby.pdf,PUTUSAN Nomor 143/Pdt.G/2023/PN Sby DEMI KEADI...

In [5]:
df_200.isnull().sum()

url_page                     0
penggugat                    0
tergugat                     0
turut_tergugat             106
nomor                        0
tingkat_proses               0
klasifikasi                  0
kata_kunci                   0
tahun                        0
tanggal_register             0
lembaga_peradilan            0
jenis_lembaga_peradilan      0
hakim_ketua                  0
hakim_anggota                0
panitera                     0
amar                         0
amar_lainnya                 0
catatan_amar                 0
tanggal_musyawarah           0
tanggal_dibacakan            0
kaidah                       0
abstrak                    200
url_pdf                      0
nama_file                    0
content                      0
dtype: int64

In [6]:
df_200['nomor']

0      698/Pdt.G/2021/PN Jkt.Pst
1      306/Pdt.G/2022/PN Jkt.Pst
2      643/Pdt.G/2021/PN Jkt.Pst
3      534/Pdt.G/2021/PN Jkt.Pst
4      818/Pdt.G/2021/PN Jkt.Pst
                 ...
195        787/Pdt.G/2023/PN Sby
196        190/Pdt.G/2023/PN Sby
197         52/Pdt.G/2023/PN Sby
198        680/Pdt.G/2023/PN Sby
199        143/Pdt.G/2023/PN Sby
Name: nomor, Length: 200, dtype: object

In [7]:
df_200 = df_200.drop(["abstrak"], axis=1)

In [8]:
df_200

,url_page,penggugat,tergugat,turut_tergugat,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,...,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"Amirul Muchtar, SE",1.Ketua Umum DPP Partai NasDem. Bpk Surya Palo...,NaN,698/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,17 Nopember 2021,...,Panitera Pengganti Friska Silitonga,Lain-lain,PENGADILAN TIDAK BERWENANG,1. Mengabulkan eksepsi kompetensi absolut para...,9 Agustus 2022,9 Agustus 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,698_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 698/Pdt.G/2021/PN Jkt.Pst . DEMI...
1,https://putusan3.mahkamahagung.go.id/direktori...,Henri Kusuma,"1.Erman Umar,SH 2.ZEESHA FATMA DEFAGA, SH 3.PR...",Dewan Pimpinan Pusat Kongres Advokat Indonesia,306/Pdt.G/2022/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,8 Juni 2022,...,Panitera Pengganti: Tambat Akbar,Lain-lain,DICABUT,M E N E T A P K A N: Mengabulkan permohonan pe...,4 Agustus 2022,4 Agustus 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,306_Pdt.G_2022_PN_Jkt.Pst.pdf,PENETAPAN Nomor 306/Pdt.G/2022/PN.Jkt.Pst DEMI...
2,https://putusan3.mahkamahagung.go.id/direktori...,Chris Inderayanto,PT. Bank Negara Indonesia (persero) Tbk,Pemerintah Republik Indonesia Cq Kementrian Ke...,643/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,22 Oktober 2021,...,Panitera Pengganti: Mufid Talib,Lain-lain,DITOLAK,M E N G A D I L I DALAM EKSEPSI. Menolak Eksep...,8 Agustus 2022,8 Agustus 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,643_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 643/Pdt.G/2022/PN. Jkt Pst DEMI ...
3,https://putusan3.mahkamahagung.go.id/direktori...,H. RAYAN NURACHMAN,ISLAMIATI LEDIANA,"1.PT. BANK RAKYAT INDONESIA Tbk., 2.KEPALA KAN...",534/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,7 September 2021,...,Panitera Pengganti Widi Astuti,Lain-lain,MENGABULKAN EKSEPSI,MengadiliDALAM EKSEPSI1. Mengabulkan Eksepsi P...,19 Juli 2022,19 Juli 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,534_Pdt.G_2021_PN_Jkt.Pst.pdf,I.PUTUSAN Nomor 534/Pdt.G/2020/PN Jkt Pst II.D...
4,https://putusan3.mahkamahagung.go.id/direktori...,1.Binaresti Dewi 2.Mulyono Sucitro 3.Chintya S...,1.PT Asuransi Jiwasraya (Persero) 2.Otoritas J...,NaN,818/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,30 Desember 2021,...,Panitera Pengganti Suroyo,Lain-lain,MENGABULKAN EKSEPSI,MENGADILI: Mengabulkan eksepsi Tergugat I dan ...,11 Agustus 2022,11 Agustus 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,818_Pdt.G_2021_PN_Jkt.Pst.pdf,PUTUSAN Nomor 818/Pdt.G/2021/PN Jkt.Pst DEMI K...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://putusan3.mahkamahagung.go.id/direktori...,DONI SUSILO,PT MANDIRI TUNAS FINANCE cq. PT MANDIRI TUNAS ...,NaN,787/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,7 Agustus 2023,...,Panitera Pengganti: Sjahrizal,Lain-lain,DICABUT,M E N E T A P K A N : Mengabulkan permohonan p...,6 September 2023,6 September 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,787_Pdt.G_2023_PN_Sby.pdf,PENETAPAN Nomor. 787/Pdt.G/2023/PN. Sby. “DEMI...
196,https://putusan3.mahkamahagung.go.id/direktori...,PT. Granting Jaya,PT. Bahagia Bersama Jaya,1.ALI SAMSUNI 2.ABDUL HALIM 3.IWAN BUANA 4.ZAI...,190/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,17 Februari 2023,...,Panitera Pengganti Tri Prasetyo Budi,Lain-lain,MENGABULKAN EKSEPSI,Mengabulkan Eksepsi Turut Tergugat XII; Menyat...,6 September 2023,6 September 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,190_Pdt.G_2023_PN_Sby.pdf,PUTUSAN SELA Nomor 190/Pdt.G/2023/PN.Sby. DEMI...
197,https://putusan3.mahkamahagung.go.id/direktori...,ANUGRAH YUDO WITJAKSONO,1.PT. PRIMA MASTER BANK (PRIMA BANK) 2.AGUS TR...,2.OTORITAS JASA KEUANGAN (OJK) 3.IR. DANIEL SU...,52/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,16 Januari 2023,...,Panitera Pengganti: Asep Priyatno,Lain-lain,DITOLAK,MENGADILI: Menolak gugatan Penggugat seluruhny...,4 September 2023,4 September 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,52_Pdt.G_2023_PN_Sby.pdf,PUTUSAN Nomor 52/Pdt G/2023/PN Sby DEMI KEADIL...
198,https://putusan3.mahkamahagung.go.id/direktori...,Sylvia Kumala Saridewi,1.PT. Bank Commonwealth 2.Kepala Kantor Pelaya...,NaN,680/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,10 Juli 2023,...,Panitera Pengganti: Siswanto,Lain-lain,DICABUT,M E N E T A P K A N Menyatakan gugatan yang di...,31 Agustus 2023,31 Agustus 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,680_Pdt.G_2023_PN_Sby.pdf,P E N E T A P A N Nomor 680/Pdt.G/2023/PN Sby....
199,https://putusan3.mahkamahagung.go.id/direktori...,SANTOSO RYANTO,1.PT. BANK SAHABAT SAMPOERNA CABANG SURABAYA 2...,KEMENTERIAN AGRARIA DAN TATA RUANG/BADAN PERTA...,143/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,6 Februari 2023,...,Panitera Pengganti Tri Prasetyo Budi,Lain-lain,DITOLAK,Dalam Provisi : -Menolak tuntutan Provisi Peng...,31 Agustus 2023,31 Agustus 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,143_Pdt.G_2023_PN_Sby.pdf,PUTUSAN Nomor 143/Pdt.G/2023/PN Sby DEMI KEADI...

In [9]:
def clean_text(text):
  text = text.replace("\n", " ")
  text = text.replace("P U T U S A N", "PUTUSAN").replace("P E N E T A P A N", "PENETAPAN")
  text = text.replace('\uf0d8', '')
  text = re.sub(r'\b(\w)\s*\b', r'\1', text)
  text = re.sub(r'(Hal\.\s*\S+(?:\s*\S+)?\.?\s*)|(Halaman \d+(?:\.\d+)?\s*)|Putusan Nomor \S+\s*', '', text)
  text = re.sub(r'^[A-Za-z]+\.\s*', '', text)
  text = re.sub(r'-+', '', text)
  text = re.sub(r'\s+', ' ', text)
  text = re.sub(r'(pn)\.', r'\1 ', text) # Memperbaiki nomor putusan mengganti titik setelah PN dengan spasi
  text = re.sub(r'(\d+)\s*([a-zA-Z]+)\s*(\d+)', r'\1 \2 \3', text) # Memperbaiki format tanggal jika 1 angka di kasih 0
  text = re.sub(r'(\b\d\b)', lambda x: f'0{x.group(1)}', text)
  text = re.sub(r"(\d+)\.(\w)", r"\1. \2", text)
  text = re.sub(r'\b(jkt) (pst)\b', r'\1.\2', text)
  return text.lower()

df_200['content'] = df_200["content"].apply(clean_text)

In [10]:
df_200

,url_page,penggugat,tergugat,turut_tergugat,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,...,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"Amirul Muchtar, SE",1.Ketua Umum DPP Partai NasDem. Bpk Surya Palo...,NaN,698/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,17 Nopember 2021,...,Panitera Pengganti Friska Silitonga,Lain-lain,PENGADILAN TIDAK BERWENANG,1. Mengabulkan eksepsi kompetensi absolut para...,9 Agustus 2022,9 Agustus 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,698_Pdt.G_2021_PN_Jkt.Pst.pdf,putusan nomor 698/pdt.g/2021/pn jkt.pst . demi...
1,https://putusan3.mahkamahagung.go.id/direktori...,Henri Kusuma,"1.Erman Umar,SH 2.ZEESHA FATMA DEFAGA, SH 3.PR...",Dewan Pimpinan Pusat Kongres Advokat Indonesia,306/Pdt.G/2022/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,8 Juni 2022,...,Panitera Pengganti: Tambat Akbar,Lain-lain,DICABUT,M E N E T A P K A N: Mengabulkan permohonan pe...,4 Agustus 2022,4 Agustus 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,306_Pdt.G_2022_PN_Jkt.Pst.pdf,penetapan nomor 306/pdt.g/2022/pn.jkt.pst demi...
2,https://putusan3.mahkamahagung.go.id/direktori...,Chris Inderayanto,PT. Bank Negara Indonesia (persero) Tbk,Pemerintah Republik Indonesia Cq Kementrian Ke...,643/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,22 Oktober 2021,...,Panitera Pengganti: Mufid Talib,Lain-lain,DITOLAK,M E N G A D I L I DALAM EKSEPSI. Menolak Eksep...,8 Agustus 2022,8 Agustus 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,643_Pdt.G_2021_PN_Jkt.Pst.pdf,putusan nomor 643/pdt.g/2022/pn. jkt pst demi ...
3,https://putusan3.mahkamahagung.go.id/direktori...,H. RAYAN NURACHMAN,ISLAMIATI LEDIANA,"1.PT. BANK RAKYAT INDONESIA Tbk., 2.KEPALA KAN...",534/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,7 September 2021,...,Panitera Pengganti Widi Astuti,Lain-lain,MENGABULKAN EKSEPSI,MengadiliDALAM EKSEPSI1. Mengabulkan Eksepsi P...,19 Juli 2022,19 Juli 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,534_Pdt.G_2021_PN_Jkt.Pst.pdf,putusan nomor 534/pdt.g/2020/pn jkt pst ii.dem...
4,https://putusan3.mahkamahagung.go.id/direktori...,1.Binaresti Dewi 2.Mulyono Sucitro 3.Chintya S...,1.PT Asuransi Jiwasraya (Persero) 2.Otoritas J...,NaN,818/Pdt.G/2021/PN Jkt.Pst,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2022,30 Desember 2021,...,Panitera Pengganti Suroyo,Lain-lain,MENGABULKAN EKSEPSI,MENGADILI: Mengabulkan eksepsi Tergugat I dan ...,11 Agustus 2022,11 Agustus 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,818_Pdt.G_2021_PN_Jkt.Pst.pdf,putusan nomor 818/pdt.g/2021/pn jkt.pst demi k...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://putusan3.mahkamahagung.go.id/direktori...,DONI SUSILO,PT MANDIRI TUNAS FINANCE cq. PT MANDIRI TUNAS ...,NaN,787/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,7 Agustus 2023,...,Panitera Pengganti: Sjahrizal,Lain-lain,DICABUT,M E N E T A P K A N : Mengabulkan permohonan p...,6 September 2023,6 September 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,787_Pdt.G_2023_PN_Sby.pdf,penetapan nomor. 787/pdt.g/2023/pn. sby. “demi...
196,https://putusan3.mahkamahagung.go.id/direktori...,PT. Granting Jaya,PT. Bahagia Bersama Jaya,1.ALI SAMSUNI 2.ABDUL HALIM 3.IWAN BUANA 4.ZAI...,190/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,17 Februari 2023,...,Panitera Pengganti Tri Prasetyo Budi,Lain-lain,MENGABULKAN EKSEPSI,Mengabulkan Eksepsi Turut Tergugat XII; Menyat...,6 September 2023,6 September 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,190_Pdt.G_2023_PN_Sby.pdf,putusan sela nomor 190/pdt.g/2023/pn.sby. demi...
197,https://putusan3.mahkamahagung.go.id/direktori...,ANUGRAH YUDO WITJAKSONO,1.PT. PRIMA MASTER BANK (PRIMA BANK) 2.AGUS TR...,2.OTORITAS JASA KEUANGAN (OJK) 3.IR. DANIEL SU...,52/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,16 Januari 2023,...,Panitera Pengganti: Asep Priyatno,Lain-lain,DITOLAK,MENGADILI: Menolak gugatan Penggugat seluruhny...,4 September 2023,4 September 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,52_Pdt.G_2023_PN_Sby.pdf,putusan nomor 52/pdt g/2023/pn sby demi keadil...
198,https://putusan3.mahkamahagung.go.id/direktori...,Sylvia Kumala Saridewi,1.PT. Bank Commonwealth 2.Kepala Kantor Pelaya...,NaN,680/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,10 Juli 2023,...,Panitera Pengganti: Siswanto,Lain-lain,DICABUT,M E N E T A P K A N Menyatakan gugatan yang di...,31 Agustus 2023,31 Agustus 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,680_Pdt.G_2023_PN_Sby.pdf,penetapan nomor 680/pdt.g/2023/pn sby. demi ke...
199,https://putusan3.mahkamahagung.go.id/direktori...,SANTOSO RYANTO,1.PT. BANK SAHABAT SAMPOERNA CABANG SURABAYA 2...,KEMENTERIAN AGRARIA DAN TATA RUANG/BADAN PERTA...,143/Pdt.G/2023/PN Sby,Pertama,Perdata \n Perdata Perbuatan Melawan Hukum,Perbuatan Melawan Hukum,2023,6 Februari 2023,...,Panitera Pengganti Tri Prasetyo Budi,Lain-lain,DITOLAK,Dalam Provisi : -Menolak tuntutan Provisi Peng...,31 Agustus 2023,31 Agustus 2023,—,https://putusan3.mahkamahagung.go.id/direktori...,143_Pdt.G_2023_PN_Sby.pdf,putusan nomor 143/pdt.g/2023/pn sby demi keadi...

In [11]:
def find_similar_sentence(text, target_sentence):
  sentences = text.split(';')  # Pisahkan teks menjadi kalimat-kalimat
  if len(target_sentence.split()) > 1:
    # Gunakan TF-IDF untuk mewakili teks
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform(sentences + [target_sentence])

    # Hitung cosine similarity antara vektor target dan vektor kalimat
    similarity_scores = cosine_similarity(vectors[-1], vectors[:-1])[0]

    # Temukan kalimat dengan similarity tertinggi
    max_similarity_index = similarity_scores.argmax()

    if similarity_scores[max_similarity_index] > 0.0:  # Ubah ambang batas sesuai kebutuhan
        return sentences[max_similarity_index].strip()
    else:
        return None
  else:
    return target_sentence

In [ ]:
  # nomor_putusan = data["nomor"].lower()
  # terdakwa =  data["terdakwa"].lower().replace("(alm)", '')
  # jenis_dakwaan = data["kata_kunci"].lower()
  # tuntutan_gugatan = re.sub(r'\d+\.', '', find_similar_sentence(data['content'], 'dikurang selama')).strip()
  # pasal = re.sub(r'\d+\.', '', find_similar_sentence(data['content'], 'melanggar pasal')).strip()
  # tgl_putusan = re.sub(r'(\b\d\b)', lambda x: f'0{x.group(1)}', data["tanggal_dibacakan"].lower())
  # hakim_ketua = data["hakim_ketua"].lower().replace("hakim ketua", '').strip()
  # hakim_anggota = data["hakim_anggota"].lower().replace("hakim anggota", '').replace("br", '').strip().split(',')
  # penuntut =  re.sub(r'\d+\.','',data["penuntut_umum"].lower().replace("s.h.", ''))
  # panitera = data["panitera"].lower().replace("panitera pengganti", "").replace(":", "").strip()
  # # penuntut_umum = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', data["penuntut_umum"].lower())
  # amar_lainnya = data["amar_lainnya"].lower()
  # catatan_amar = re.sub(r'(\w+)\s*(\d+\.)', r'\1 \2', re.sub(r'(pn)\.', r'\1 ', data["catatan_amar"].lower()))
  # #putusan hukum
  # hasil_gugatan = amar_lainnya if re.search(amar_lainnya, data["content"]) else re.sub(r'\d+\.', '', find_similar_sentence(catatan_amar, amar_lainnya)).strip()
  # turut_tergugat = data["terdakwa"].lower().replace("(alm)", '')

In [12]:
def generate_label(data):
  label = {}
  nomor_putusan = data["nomor"].lower()
  tgl_putusan = re.sub(r'(\b\d\b)', lambda x: f'0{x.group(1)}', data["tanggal_dibacakan"].lower())
  hakim_ketua = data["hakim_ketua"].lower().replace("hakim ketua", '').strip()
  hakim_anggota = data["hakim_anggota"].lower().replace("hakim anggota", '').replace("br", '').strip().split(',')
  panitera = data["panitera"].lower().replace("panitera pengganti", "").replace(":", "").strip()
  penggugat = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', data["penggugat"].lower())
  tergugat = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', data["tergugat"].lower())
  turut_tergugat = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', data["turut_tergugat"].lower()) if str(data["turut_tergugat"]) != 'nan' else None
  amar_lainnya = data["amar_lainnya"].lower()
  catatan_amar = re.sub(r'(\w+)\s*(\d+\.)', r'\1 \2', re.sub(r'(pn)\.', r'\1 ', data["catatan_amar"].lower()))
  hasil_gugatan = amar_lainnya if re.search(amar_lainnya, data["content"]) else re.sub(r'\d+\.', '', find_similar_sentence(catatan_amar, amar_lainnya)).strip()
  putusan_gugatan = [i.strip() for i in re.sub(r'(pn)\.', r'\1 ', data["catatan_amar"].lower()).split(';') if re.search('menyatakan|dalam pokok perkara|menghukum para|menghukum kedua', i.strip())]
  # print(label[nomor_putusan])
  label[nomor_putusan] = "B_VERN"
  label[tgl_putusan] = "B_TIMV"
  label[hakim_ketua] = "B_JUDP"
  label[panitera] = "B_REGI"
  label[hasil_gugatan] = "B_LSWR"

  if putusan_gugatan:
    if len(putusan_gugatan) > 1:
      label.update({pg.strip() : "B_LSWV" for pg in putusan_gugatan})
    else:
      label[putusan_gugatan[0]] = "B_LSWV"

  if not hakim_anggota:
    label[data["hakim_anggota"].lower()] = "B_PLAN"
  else:
    label.update({anggota.strip() : "B_JUG" for anggota in hakim_anggota})

  if not penggugat:
    label[data["penggugat"].lower()] = "B_PLAN"
  else:
    label.update({i.strip() : "B_PLAN" for i in penggugat})

  if not tergugat:
    label[data["tergugat"].lower()] = "B_DENN"
  else:
    label.update({i.strip() : "B_DENN" for i in tergugat if i})

  if turut_tergugat != None and not turut_tergugat:
    label[data["turut_tergugat"].lower() if re.search(data["turut_tergugat"].lower(), data["content"]) else re.sub(r'\d+\.', '', find_similar_sentence(data["content"], data["turut_tergugat"].lower())).strip()] = "B_PLAO"
  if turut_tergugat:
    label.update({i.strip() : "B_PLAO" for i in turut_tergugat if i})

  return label

def labeling_token(text, label_dict):
  tokens = text.split()
  labeled_tokens = ['O'] * len(tokens)
  find_label = dict()
  for key, value in label_dict.items():
      words = key.split()
      # print(words, value)
      current_dict = find_label
      for word in words[:-1]:
          word = re.sub(r'[.,;]', '', word)
          current_dict = current_dict.setdefault(word, {})
      last_word = re.sub(r'[.,;]', '', words[-1])
      current_dict[last_word] = {'label': value}
  # print(find_label)

  temp_idx_token = []
  find_label_selected = find_label
  for i, token in enumerate(tokens):
    clean_token = re.sub(r'[.,;]', '', token)
    # print(clean_token)
    if clean_token in find_label_selected:
      find_label_selected = find_label_selected[clean_token]
      temp_idx_token.append(i)
      # print(clean_token)
      # print(find_label_selected)
      if 'label' in find_label_selected:
        tag = find_label_selected['label']
        # print(clean_token, tag, temp_idx_token)
        new_label = [tag if ind == 0 else tag.replace('B', 'I') for ind in range(len(temp_idx_token))]
        labeled_tokens[temp_idx_token[0]:temp_idx_token[0] + len(new_label)] = new_label
        temp_idx_token = []
        find_label_selected = find_label
    else:
      temp_idx_token = []
      find_label_selected = find_label

  return labeled_tokens
def countLabel(result, label_ori):
  label_found = {}
  temp = []
  for i, row in result.iterrows():
    for t, l in zip(row["text"], row["label"]):
      if l != 'O' and l.replace('I_', 'B_') not in temp:
        temp.append(l.replace('I_', 'B_'))

  label_found[f"Dokumen Ke-{i+1}"] = (len(temp), label_ori, temp)

  return label_found

def accuracy(result):
  sum_label = 0
  label_in = 0
  for key, value in result.items():
    print(f"{key} => Data Terlebel : {value[0]} ; Total Label : {value[1]} ; Label : {value[2]}")
    sum_label+= value[1]
    label_in += value[0]
  print("Accuracy : {label_in/sum_label * 100}")

  return f"Accuracy : {label_in/sum_label * 100}"

def anotasi(data):
  new_data = pd.DataFrame([], columns=['doc','text', 'label'])
  start = 0
  end = 0
  count_label = {}
  for i, row in tqdm(data.iterrows(), total=len(data), desc="Annotating"):
    label = generate_label(row)

    labeled_tokens = labeling_token(row["content"], label)
    new_data = pd.concat([new_data, pd.DataFrame({"doc": [row["nama_file"].split()],"text": [row["content"].split()], "label": [labeled_tokens]})], ignore_index=True)
    new_data = new_data.explode('doc').reset_index(drop=True)
    count_label.update(countLabel(new_data.loc[i:i], len(set(label.values()))))

  return (new_data, count_label)


angka = 47
angka1 = 47
angka2 = 100
new_df, count_label = anotasi(df_200)
df.loc[angka1:angka2].apply(generate_label, axis=1)[angka]
# generate_label(df_1)

Annotating: 100%|██████████| 200/200 [00:06<00:00, 30.07it/s]

{'375/pdt.g/2023/pn jkt.pst': 'B_VERN',
 '20 nopember 2023': 'B_TIMV',
 'fahzal hendri.': 'B_JUDP',
 'andre': 'B_REGI',
 'menyatakan pengadilan negeri tidak berwenang mengadili perkara ini karena merupakan kewenangan pada pengadilan niaga pada pengadilan negeri jakarta pusat': 'B_LSWV',
 'rianto adam pontoh': 'B_JUG',
 'panji surono': 'B_JUG',
 'bintoro iduansjah': 'B_PLAN',
 'the budi tedjo prawiro': 'B_PLAN',
 'pt. solusi pandu virtua': 'B_DENN',
 'pt. pada idi': 'B_DENN',
 'edward suharjo wiryomartani, s.h., m.kn.': 'B_DENN',
 'jimmy masrin': 'B_DENN',
 'pt. tunas laju investama': 'B_DENN',
 'pt. petro energy (dalam pailit)': 'B_DENN',
 'pt. mitrada selaras (dahulu pt. mitrada sinergi)': 'B_DENN',
 'pt. caturkarsa megatunggal': 'B_DENN'}

In [17]:
generate_label(df_200.iloc[199])

{'143/pdt.g/2023/pn sby': 'B_VERN',
 '31 agustus 2023': 'B_TIMV',
 'arlandi triyogo': 'B_JUDP',
 'tri prasetyo budi': 'B_REGI',
 'ditolak': 'B_LSWR',
 'dalam pokok perkara : menolak gugatan penggugat untuk seluruhnya': 'B_LSWV',
 'i made subagia astawa': 'B_JUG',
 'r. yoes hartyarso': 'B_JUG',
 'santoso ryanto': 'B_PLAN',
 'pt. bank sahabat sampoerna cabang surabaya': 'B_DENN',
 'pt. balai lelang mahkota': 'B_DENN',
 'kementerian keuangan ri, cq. direktur jenderal kekayaan negara di jakarta, cq. kantor wilayah direktur jenderal kekayaan negara jawa timur, cq. kantor pelayanan kekayaan negara dan lelang surabaya': 'B_DENN',
 'kementerian agraria dan tata ruang/badan pertanahan nasional, cq. badan pertanahan nasional republik indonesia, cq. kantor wilayah badan pertanahan nasional jawa timur, cq. kantor pertanahan kota surabaya i': 'B_PLAO'}

In [20]:
new_df.iloc[199]

doc                              143_Pdt.G_2023_PN_Sby.pdf
text     [putusan, nomor, 143/pdt.g/2023/pn, sby, demi,...
label    [O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,...
Name: 199, dtype: object

In [14]:
new_df.iloc[0]

doc                          698_Pdt.G_2021_PN_Jkt.Pst.pdf
text     [putusan, nomor, 698/pdt.g/2021/pn, jkt.pst, ....
label    [O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,...
Name: 0, dtype: object

In [15]:
accuracy(count_label)

Dokumen Ke-1 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-2 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-3 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-4 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-5 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-6 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-7 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-8 => Data Terlebel : 6 ; Total Label : 10 ; Label : ['B_PLAN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-9 => Data Terlebel : 4 ; Total Label : 9 ; Label : ['B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-10 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-11 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-12 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_DENN', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-13 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_LSWR', 'B_TIMV', 'B_PLAN', 'B_PLAO', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-14 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-15 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV']
Dokumen Ke-16 => Data Terlebel : 6 ; Total Label : 10 ; Label : ['B_PLAN', 'B_PLAO', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-17 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_PLAN', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-18 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-19 => Data Terlebel : 6 ; Total Label : 10 ; Label : ['B_VERN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUG', 'B_TIMV']
Dokumen Ke-20 => Data Terlebel : 6 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-21 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-22 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_TIMV', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-23 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-24 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-25 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-26 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-27 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-28 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG']
Dokumen Ke-29 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-30 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-31 => Data Terlebel : 6 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG']
Dokumen Ke-32 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG']
Dokumen Ke-33 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-34 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWV', 'B_TIMV', 'B_JUDP', 'B_JUG']
Dokumen Ke-35 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-36 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_JUDP']
Dokumen Ke-37 => Data Terlebel : 8 ; Total Label : 8 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-38 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_LSWV', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-39 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-40 => Data Terlebel : 10 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_LSWV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-41 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_VERN', 'B_TIMV', 'B_REGI']
Dokumen Ke-42 => Data Terlebel : 6 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG']
Dokumen Ke-43 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-44 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_LSWR', 'B_VERN', 'B_PLAN', 'B_DENN', 'B_JUDP', 'B_REGI', 'B_JUG']
Dokumen Ke-45 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_VERN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-46 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-47 => Data Terlebel : 6 ; Total Label : 8 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-48 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_VERN', 'B_REGI']
Dokumen Ke-49 => Data Terlebel : 6 ; Total Label : 10 ; Label : ['B_PLAN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV']
Dokumen Ke-50 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_LSWR', 'B_PLAN', 'B_PLAO', 'B_DENN', 'B_VERN', 'B_JUDP', 'B_JUG']
Dokumen Ke-51 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-52 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_VERN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-53 => Data Terlebel : 10 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-54 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-55 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-56 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-57 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-58 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAO', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-59 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWV', 'B_LSWR', 'B_JUDP', 'B_TIMV', 'B_JUG']
Dokumen Ke-60 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-61 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-62 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-63 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-64 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-65 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-66 => Data Terlebel : 6 ; Total Label : 9 ; Label : ['B_PLAN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-67 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV']
Dokumen Ke-68 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-69 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_PLAN', 'B_DENN', 'B_VERN', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-70 => Data Terlebel : 8 ; Total Label : 8 ; Label : ['B_PLAN', 'B_DENN', 'B_VERN', 'B_LSWV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-71 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_PLAO', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-72 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_VERN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-73 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-74 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_VERN', 'B_DENN', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-75 => Data Terlebel : 6 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_TIMV', 'B_LSWR', 'B_JUG']
Dokumen Ke-76 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-77 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV']
Dokumen Ke-78 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-79 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-80 => Data Terlebel : 10 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWV', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-81 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_VERN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-82 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-83 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-84 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_LSWR', 'B_VERN', 'B_TIMV', 'B_PLAN', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-85 => Data Terlebel : 6 ; Total Label : 9 ; Label : ['B_VERN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-86 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_DENN', 'B_PLAO', 'B_LSWV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV']
Dokumen Ke-87 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_VERN', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-88 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWR', 'B_VERN', 'B_TIMV', 'B_JUG', 'B_JUDP', 'B_REGI']
Dokumen Ke-89 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-90 => Data Terlebel : 10 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-91 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_PLAN', 'B_DENN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-92 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_VERN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-93 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_PLAO', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-94 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV']
Dokumen Ke-95 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-96 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_PLAN', 'B_DENN', 'B_VERN', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-97 => Data Terlebel : 10 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_TIMV', 'B_LSWR', 'B_LSWV', 'B_JUG', 'B_REGI', 'B_JUDP']
Dokumen Ke-98 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-99 => Data Terlebel : 6 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-100 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-101 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_VERN', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-102 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-103 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-104 => Data Terlebel : 6 ; Total Label : 8 ; Label : ['B_LSWR', 'B_PLAN', 'B_DENN', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-105 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_LSWR', 'B_TIMV', 'B_PLAN', 'B_DENN', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-106 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_VERN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-107 => Data Terlebel : 3 ; Total Label : 8 ; Label : ['B_LSWR', 'B_JUG', 'B_REGI']
Dokumen Ke-108 => Data Terlebel : 6 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-109 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-110 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_TIMV', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-111 => Data Terlebel : 6 ; Total Label : 8 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_TIMV', 'B_JUDP', 'B_JUG']
Dokumen Ke-112 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_LSWR', 'B_VERN', 'B_TIMV', 'B_PLAN', 'B_DENN', 'B_JUDP', 'B_JUG']
Dokumen Ke-113 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-114 => Data Terlebel : 8 ; Total Label : 8 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-115 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_VERN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-116 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_VERN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-117 => Data Terlebel : 8 ; Total Label : 8 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-118 => Data Terlebel : 8 ; Total Label : 8 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-119 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-120 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-121 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-122 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_VERN', 'B_TIMV', 'B_REGI']
Dokumen Ke-123 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_LSWR', 'B_VERN', 'B_PLAN', 'B_DENN', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-124 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-125 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_LSWR', 'B_DENN', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-126 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_LSWR', 'B_TIMV', 'B_PLAN', 'B_DENN', 'B_VERN', 'B_JUG', 'B_REGI', 'B_JUDP']
Dokumen Ke-127 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_VERN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-128 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_LSWR', 'B_TIMV', 'B_PLAN', 'B_DENN', 'B_PLAO', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-129 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-130 => Data Terlebel : 7 ; Total Label : 8 ; Label : ['B_LSWR', 'B_TIMV', 'B_DENN', 'B_PLAN', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-131 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_TIMV', 'B_VERN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-132 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-133 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_PLAN', 'B_TIMV', 'B_VERN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-134 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_DENN', 'B_PLAO', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-135 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_VERN', 'B_DENN', 'B_TIMV', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-136 => Data Terlebel : 9 ; Total Label : 10 ; Label : ['B_VERN', 'B_PLAO', 'B_PLAN', 'B_LSWV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-137 => Data Terlebel : 7 ; Total Label : 10 ; Label : ['B_TIMV', 'B_PLAN', 'B_PLAO', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-138 => Data Terlebel : 8 ; Total Label : 10 ; Label : ['B_PLAN', 'B_TIMV', 'B_DENN', 'B_PLAO', 'B_VERN', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-139 => Data Terlebel : 8 ; Total Label : 9 ; Label : ['B_PLAN', 'B_DENN', 'B_TIMV', 'B_VERN', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-140 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_LSWR', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-141 => Data Terlebel : 7 ; Total Label : 9 ; Label : ['B_VERN', 'B_DENN', 'B_TIMV', 'B_LSWR', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-142 => Data Terlebel : 9 ; Total Label : 9 ; Label : ['B_VERN', 'B_PLAN', 'B_DENN', 'B_LSWR', 'B_LSWV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']

'Accuracy : 81.49946062567422'

In [ ]:
new_df.to_csv('Dataset-Perdata200-blmFix.csv', index=False)