# Anotasi Data Pidana

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm
import pandas as pd
import gdown
import re

## Download Dataset

In [2]:
gdown.download(f'https://drive.google.com/uc?id=1-IK0r41iMPbCIyvE08oaUAtCzloMvYGX', "Dataset Pidana Umum Bangkalan.csv", quiet=False)
gdown.download(f'https://drive.google.com/uc?id=1-Qq0wI5QcBmX5w7jHEA1SAXcuYqeV_ol', "Dataset Pidana Umum Sampang.csv", quiet=False)
gdown.download(f'https://drive.google.com/uc?id=1-UOAa43DNkARQGZ5eEHyDVTzNRbHqesI', "Dataset Pidana Umum Pamekasan.csv", quiet=False)
gdown.download(f'https://drive.google.com/uc?id=1LmovXgGIccg6BrT8gSyjckET6FOIlZcO', "Dataset Pidana Umum Sumenep.csv", quiet=False)
# https://drive.google.com/file/d/1LmovXgGIccg6BrT8gSyjckET6FOIlZcO/view?usp=sharing
# https://drive.google.com/file/d/1-UOAa43DNkARQGZ5eEHyDVTzNRbHqesI/view?usp=sharing

Downloading...
From: https://drive.google.com/uc?id=1-IK0r41iMPbCIyvE08oaUAtCzloMvYGX
To: /content/Dataset Pidana Umum Bangkalan.csv
100%|██████████| 12.6M/12.6M [00:00<00:00, 68.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-Qq0wI5QcBmX5w7jHEA1SAXcuYqeV_ol
To: /content/Dataset Pidana Umum Sampang.csv
100%|██████████| 7.05M/7.05M [00:00<00:00, 36.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-UOAa43DNkARQGZ5eEHyDVTzNRbHqesI
To: /content/Dataset Pidana Umum Pamekasan.csv
100%|██████████| 6.56M/6.56M [00:00<00:00, 32.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1LmovXgGIccg6BrT8gSyjckET6FOIlZcO
To: /content/Dataset Pidana Umum Sumenep.csv
100%|██████████| 5.90M/5.90M [00:00<00:00, 33.4MB/s]

'Dataset Pidana Umum Sumenep.csv'

## Dataset Bangkalan

In [3]:
df_Bangkalan = pd.read_csv("Dataset Pidana Umum Bangkalan.csv")
df_Bangkalan

,url_page,penuntut_umum,terdakwa,nomor,kata_kunci,tahun,tanggal_register,lembaga_peradilan,hakim_ketua,hakim_anggota,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"DEWI IKA AGUSTINA, SH",TISLAN bin MUKAMAR,48/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: Hosnol Bakri,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa TISLAN BIN MUKA...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,48_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 48/Pid.B/2024/PN Bkl\nDEMI KEAD...
1,https://putusan3.mahkamahagung.go.id/direktori...,"NANDINI PARAHITA YULISANI, S.H.",BEIRI Bin BUNALI,42/Pid.B/2024/PN Bkl,Penganiayaan,2024,5 Maret 2024,PN BANGKALAN,Hakim Ketua Zainal Ahmad,"Br Hakim Anggota Wienda Kresnantyo, Hakim Ang...",Panitera Pengganti: Rr. Koosbandriyah As,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Beiri bin Bunal...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,42_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 42/Pid.B/2024/PN Bkl\nDEMI KEAD...
2,https://putusan3.mahkamahagung.go.id/direktori...,"UMU LATHIEFAH, S.H",FANDI bin SULAIMAN,49/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: Hosnol Bakri,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa FANDI BIN SULAI...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,49_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 49/Pid.B/2024/PN Bkl\nDEMI KEAD...
3,https://putusan3.mahkamahagung.go.id/direktori...,"FAJRINI FAISAH, S.H.",PANDI Bin SIDIK,56/Pid.B/2024/PN Bkl,PenadahanPenerbitandan Pencetakan,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Zainal Ahmad,"Br Hakim Anggota Wienda Kresnantyo, Hakim Ang...",Panitera Pengganti: Naruddin,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: MenyatakanTerdakwaPandi Bin Sidikte...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,56_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 56/Pid.B/2024/PN Bkl\nDEMI KEAD...
4,https://putusan3.mahkamahagung.go.id/direktori...,"FAJRINI FAISAH, S.H.",MUSTOFA al. JARWOT bin HADENAN (Alm),57/Pid.B/2024/PN Bkl,Pencurian,2024,15 Maret 2024,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Br Hakim Anggota Wahyu Eko Suryowati, Hakim A...",Panitera Pengganti: H. Mohammad Asari,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I Menyatakan Terdakwa Mustofa ...,2 Mei 2024,2 Mei 2024,https://putusan3.mahkamahagung.go.id/direktori...,57_Pid.B_2024_PN_Bkl.pdf,PUTUSAN\nNomor 57/Pid.B/2024/PN Bkl\nDEMI KEAD...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,https://putusan3.mahkamahagung.go.id/direktori...,"ADHITYA YUANA, SH","MAULANA NOVA GUNARDI, S.E Bin SLAMET MULYADI",251/Pid.B/2021/PN Bkl,Penggelapan,2022,21 Oktober 2021,PN BANGKALAN,Hakim Ketua Oki Basuki Rachmat,"Hakim Anggota Johan Wahyu Hidayat, Br Hakim A...",Panitera Pengganti: Rr. Koosbandriyah As,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,"Menyatakan Terdakwa Maulana Nova Gunardi, S.E ...",4 Januari 2022,4 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,251_Pid.B_2021_PN_Bkl.pdf,PUTUSAN \nNomor 251/Pid.B/202 1/PN Bkl \n \nDE...
269,https://putusan3.mahkamahagung.go.id/direktori...,"FAJRINI FAISAH, SH.",SAWARI BIN NELAN,278/Pid.B/2021/PN Bkl,Kejahatan Perjudian,2022,18 Nopember 2021,PN BANGKALAN,Hakim Ketua Oki Basuki Rachmat,"Hakim Anggota Johan Wahyu Hidayat, Br Hakim A...",Panitera Pengganti Rb Taufikurrahman,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan terdakwa Sawari Bin Nela...,4 Januari 2022,4 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,278_Pid.B_2021_PN_Bkl.pdf,PUTUSAN \nNomor 278/Pid.Sus/2021/PN BkI \nDEMI...
270,https://putusan3.mahkamahagung.go.id/direktori...,"GALIH WICAKSANA,SH",MUARIP BIN JAMALUDIN,293/Pid.B/2021/PN Bkl,Penipuan,2022,25 Nopember 2021,PN BANGKALAN,Hakim Ketua Ernila Widikartikawati,"Hakim Anggota Vilaningrum Wibawani, Br Hakim ...",Panitera Pengganti Muhammad Hamdi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MUARIP Bin JAMA...,3 Januari 2022,3 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,293_Pid.B_2021_PN_Bkl.pdf,PUTUSAN \nNomor 293/Pid.B/2021/PN Bkl \n \nDEM...
271,https://putusan3.mahkamahagung.go.id/direktori...,"FAJRINI FAISAH, SH.",1.Moh.Tolip bin H.Ahmad 2.ACHMADI bin Fathol,244/Pid.B/2021/PN Bkl,Pencurian,2021,7 Oktober 2021,PN BANGKALAN,Hakim Ketua Sugiri Wiryandono,"Hakim Anggota Vilaningrum Wibawani, Br Hakim ...",Panitera Pengganti: Naruddin,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa I M O H T O L I...,29 Desember 2021,29 Desember 2021,https://putusan3.mahkamahagung.go.id/direktori...,244_Pid.B_2021_PN_Bkl.pdf,PUTUSAN \nNomor 244/Pid.B/2021/PN Bkl \n \nDEM...
272,https://putusan3.mahkamahagung.go.id/direktori...,"BENNY RORY WIJAYA, SH",Misnawi Bin Diwi,281/Pid.B/2021/PN Bkl,Pencurian,2021,18 Nopember 2021,PN BANGKALAN,Hakim Ketua Johan Wahyu Hidayat,"Hakim Anggota Putu Wahyudi, Br Hakim Anggota ...",Panitera Pengganti: Soefyan Rusliyanto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I Menyatakan terdakwa Misnawi ...,16 Desember 2021,16 Desember 2021,https://putusan3.mahkamahagung.go.id/direktori...,281_Pid.B_2021_PN_Bkl.pdf,P U T U S A N \n Nomor : 281 /Pid.B/20 21/PN.B...

In [ ]:
# df_Bangkalan = df_Bangkalan.iloc[0:125]
# df_Bangkalan

## Dataset Sampang

In [4]:
df_Sampang = pd.read_csv("Dataset Pidana Umum Sampang.csv")
df_Sampang

,url_page,penuntut_umum,terdakwa,nomor,kata_kunci,tahun,tanggal_register,lembaga_peradilan,hakim_ketua,hakim_anggota,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"1.Dody Prihatman Purba, S.H., M.H. 2.SUHARTO, ...",ALI MUKODDER bin KHOLIL,29/Pid.Sus/2024/PN Spg,Perlindungan Anak,2024,20 Februari 2024,PN SAMPANG,Hakim Ketua Ivan Budi Santoso,"Hakim Anggota Agus Eman, Br Hakim Anggota El...",Panitera Pengganti Hasan Basri,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ALI MUKODDER Bi...,29 April 2024,29 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,29_Pid.Sus_2024_PN_Spg.pdf,PUTUSAN\nNomor 29/Pid.Sus/2024/PN Spg\nDEMI KE...
1,https://putusan3.mahkamahagung.go.id/direktori...,"1.Dody Prihatman Purba, S.H., M.H. 2.SUHARTO, ...",1.ABDUR ROHIM als. ABDUR bin. MAT SALIM 2.MALI...,35/Pid.B/2024/PN Spg,Penganiayaan,2024,6 Maret 2024,PN SAMPANG,Hakim Ketua Ivan Budi Santoso,"Hakim Anggota Agus Eman, Br Hakim Anggota El...",Panitera Pengganti Muhammad Slamet,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa I ABDUR ROHIM A...,29 April 2024,29 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,35_Pid.B_2024_PN_Spg.pdf,PUTUSAN\nNomor 35/Pid.B/2024/PN Spg\nDEMI KEAD...
2,https://putusan3.mahkamahagung.go.id/direktori...,"1.Indah Asry Pinatasari, S.H. 2.MURDIYANTA SET...",ASROR FAQIH Bin BADRUT TAMAM,30/Pid.B/2024/PN Spg,Penipuan,2024,23 Februari 2024,PN SAMPANG,Hakim Ketua Agus Eman,"Hakim Anggota Ivan Budi Santoso, Um.br Hakim ...",Panitera Pengganti Sahwi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ASROR FAQIH Bin...,29 April 2024,29 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,30_Pid.B_2024_PN_Spg.pdf,PUTUSAN\nNomor 30/Pid.B/2024/PN Spg\nDEMI KEAD...
3,https://putusan3.mahkamahagung.go.id/direktori...,"1.SUHARTO, S.H. 2.HERONIKA SETIAWATY, S.H.",HASAN Bin NIRI.Alm,3/Pid.B/2024/PN Spg,Pencurian,2024,15 Januari 2024,PN SAMPANG,Hakim Ketua Agus Eman,"Hakim Anggota Ivan Budi Santoso, Um.br Hakim ...",Panitera Pengganti Muhammad Slamet,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa HASAN BIN NIRI ...,21 Maret 2024,21 Maret 2024,https://putusan3.mahkamahagung.go.id/direktori...,3_Pid.B_2024_PN_Spg.pdf,PUTUSAN\nNomor 3/Pid.B/2024/PN Spg.\nDEMI KEAD...
4,https://putusan3.mahkamahagung.go.id/direktori...,"1.Indah Asry Pinatasari, S.H. 2.HERONIKA SETIA...",MUHLIS BIN H. FATHOLLA,21/Pid.B/2024/PN Spg,Pencurian,2024,7 Februari 2024,PN SAMPANG,Hakim Ketua Ivan Budi Santoso,"Hakim Anggota Agus Eman, Br Hakim Anggota El...",Panitera Pengganti Hasan Basri,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MUHLIS BIN H. F...,14 Maret 2024,14 Maret 2024,https://putusan3.mahkamahagung.go.id/direktori...,21_Pid.B_2024_PN_Spg.pdf,PUTUSAN\nNomor 21/Pid.B/2024/PN Spg.\nDEMI KEA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,https://putusan3.mahkamahagung.go.id/direktori...,"1.BUDI DARMAWAN, S.H. 2.ANTON ZULKARNAEN, SH",H. WAHAB Bin TAHAD,218/Pid.B/2021/PN Spg,Pemerasan dan Pengancaman,2021,7 Oktober 2021,PN SAMPANG,Hakim Ketua Ariesoleh Efendi,"Hakim Anggota Agus Eman, Br Hakim Anggota Iv...",Panitera Pengganti: Abdoel Rachman,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I: Menyatakan Terdakwa H.WAHA...,21 Oktober 2021,21 Oktober 2021,https://putusan3.mahkamahagung.go.id/direktori...,218_Pid.B_2021_PN_Spg.pdf,PUTUSAN\nNomor 218/Pid.B/2021/PN Spg\nDEMI KEA...
161,https://putusan3.mahkamahagung.go.id/direktori...,"1.ERFAN EFFENDI YUDI ARIANTO,S.H. M.H 2.MOCH. ...",ACH. SOLEH,188/Pid.B/2021/PN Spg,Penganiayaan,2021,3 September 2021,PN SAMPANG,Hakim Ketua Andri Falahandika Ansyahrul,"Hakim Anggota Ivan Budi Santoso, Um.br Hakim ...",Panitera Pengganti Sahwi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ACH. SOLEH ters...,18 Oktober 2021,18 Oktober 2021,https://putusan3.mahkamahagung.go.id/direktori...,188_Pid.B_2021_PN_Spg.pdf,PUTUSAN\nNomor 188/Pid.B/2021/PN Spg\nDEMI KEA...
162,https://putusan3.mahkamahagung.go.id/direktori...,"1.MOCH. HASAN, S.H. 2.TUNJUNG SUGHANDIKO,SH",DUL HARI al.ABD.HARI Bin SUFI,183/Pid.Sus/2021/PN Spg,Perlindungan Anak,2021,24 Agustus 2021,PN SAMPANG,Hakim Ketua Andri Falahandika Ansyahrul,"Hakim Anggota Ivan Budi Santoso, Um.br Hakim ...",Panitera Pengganti: Abdoel Rachman,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa DUL HARI Als. A...,29 September 2021,29 September 2021,https://putusan3.mahkamahagung.go.id/direktori...,183_Pid.Sus_2021_PN_Spg.pdf,PUTUSAN\nNomor 183/Pid.Sus/2021/PN Spg\nDEMI K...
163,https://putusan3.mahkamahagung.go.id/direktori...,"1.TUNJUNG SUGHANDIKO,SH 2.ANTON ZULKARNAEN, SH",ARIF WAHYU KUNCORO Bin AGUS MARAMIS,149/Pid.B/2021/PN Spg,Penipuan,2021,30 Juni 2021,PN SAMPANG,Hakim Ketua Juanda Wijaya,"Hakim Anggota Ivan Budi Santoso, Um.br Hakim ...",Panitera Pengganti Mohammad Tohir,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ARIF WAHYU KUNC...,20 September 2021,20 September 2021,https://putusan3.mahkamahagung.go.id/direktori...,149_Pid.B_2021_PN_Spg.pdf,PUTUSAN\nNomor 149/Pid.B/2021/PN Spg\nDEMI KEA...
164,https://putusan3.mahkamahagung.go.id/direktori...,"1.ANTON ZULKARNAEN, SH 2.TUNJUNG SUGHANDIKO,SH",MOH. AMIRUDDIN Bin MOH. SUDIN,129/Pid.B/2021/PN Spg,Pencurian,2021,10 Juni 2021,PN SAMPANG,Hakim Ketua Juanda Wijaya,"Hakim Anggota Ivan Budi Santoso, Um.br Hakim ...",Panitera Pengganti: Sucipto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI:1. Menyatakan terdakwa MOH.AMIRUDDIN...,2 Agustus 2021,2 Agustus 2021,https://putusan3.mahkamahagung.go.id/direktori...,129_Pid.B_2021_PN_Spg.pdf,PUTUSAN\nNomor 129/Pid.B/2021/PN Spg\nDEMI KEA...

In [ ]:
# df_Sampang = df_Sampang.iloc[0:125]
# df_Sampang

## Dataset Pamekasan

In [5]:
df_Pamekasan = pd.read_csv("Dataset Pidana Umum Pamekasan.csv")
df_Pamekasan

,url_page,penuntut_umum,terdakwa,nomor,kata_kunci,tahun,tanggal_register,lembaga_peradilan,hakim_ketua,hakim_anggota,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"SULIANINGSIH, SH",BUNIJO,19/Pid.B/2024/PN Pmk,Penganiayaan,2024,7 Februari 2024,PN PAMEKASAN,Hakim Ketua Anton Saiful Rizal,"Br Hakim Anggota Muhammad Dzulhaq, Hakim Angg...",Panitera Pengganti Edi Haris Mulyono,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Bunijotersebut ...,18 April 2024,18 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,19_Pid.B_2024_PN_Pmk.pdf,PUTUSAN\nNomor 19/Pid.B/2024//PN Pmk.\nDEMI KE...
1,https://putusan3.mahkamahagung.go.id/direktori...,"AGUS SYAMSUL ARIFIN, SH",DAHLAN,12/Pid.B/2024/PN Pmk,Pembunuhan,2024,22 Januari 2024,PN PAMEKASAN,Hakim Ketua Purwanta,"Br Hakim Anggota Yuklayushi, Hakim Anggota A...",Panitera Pengganti Siti Khozaimah,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Dahlan tersebut...,6 Maret 2024,6 Maret 2024,https://putusan3.mahkamahagung.go.id/direktori...,12_Pid.B_2024_PN_Pmk.pdf,PUTUSAN\nNomor 12/Pid.B/2024/PN Pmk\nDEMI KEAD...
2,https://putusan3.mahkamahagung.go.id/direktori...,"SUSMIYATI, SH",TRI WIBOWO,2/Pid.B/2024/PN Pmk,Penipuan,2024,10 Januari 2024,PN PAMEKASAN,Hakim Ketua Mohammad Amrullah,"Br Hakim Anggota Muhammad Dzulhaq, Hakim Angg...",Panitera Pengganti: Ainurrahmah,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,Menyatakan Terdakwa Tri Wibowo tersebut diatas...,29 Februari 2024,29 Februari 2024,https://putusan3.mahkamahagung.go.id/direktori...,2_Pid.B_2024_PN_Pmk.pdf,PUTUSAN\nNomor 2/Pid.B/2024/PN Pmk\nDEMI KEADI...
3,https://putusan3.mahkamahagung.go.id/direktori...,"Agus Kurnia Sandy, SH.",HOLILI,8/Pid.B/2024/PN Pmk,Pencurian,2024,17 Januari 2024,PN PAMEKASAN,Hakim Ketua Saiful Brow,"Br Hakim Anggota Muhammad Dzulhaq, Hakim Angg...",Panitera Pengganti: Mohammad Hariyanto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I Menyatakan Terdakwa Holili t...,22 Februari 2024,22 Februari 2024,https://putusan3.mahkamahagung.go.id/direktori...,8_Pid.B_2024_PN_Pmk.pdf,PUTUSAN\nNomor 8/Pid.B/2024/PN Pmk\nDEMI KEADI...
4,https://putusan3.mahkamahagung.go.id/direktori...,"ERWAN SUSIYANTO, SH",ACH. NADIF,7/Pid.Sus/2024/PN Pmk,Kesehatan,2024,16 Januari 2024,PN PAMEKASAN,Hakim Ketua Muhammad Dzulhaq,"Br Hakim Anggota Saiful Brow, Hakim Anggota ...",Panitera Pengganti: Khairul Wafi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I: Menyatakan Terdakwa Ach. Na...,22 Februari 2024,22 Februari 2024,https://putusan3.mahkamahagung.go.id/direktori...,7_Pid.Sus_2024_PN_Pmk.pdf,PUTUSAN\nNomor 7/Pid.Sus/2024/PN Pmk\nDEMI KEA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,https://putusan3.mahkamahagung.go.id/direktori...,"DODY,SH",Hj. LAILA alias BUK. MAHFUD,252/Pid.B/2020/PN Pmk,Penipuan,2021,3 Desember 2020,PN PAMEKASAN,Hakim Ketua Ari Siswanto,"Hakim Anggota Muhammad Sukamto, Br Hakim Angg...",Panitera Pengganti: Hairus Saleh,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,E N G A D I L I Menyatakan terdakwa HJ. LAILA ...,12 Januari 2021,12 Januari 2021,https://putusan3.mahkamahagung.go.id/direktori...,252_Pid.B_2020_PN_Pmk.pdf,Pid.I.A.3 Pid.I.A.3 \n \nPUTUSAN \nNomor 252 /...
153,https://putusan3.mahkamahagung.go.id/direktori...,"NURHALIFAH, SH",MOH.SYAIFUR RAHMAN,263/Pid.B/2020/PN Pmk,Penganiayaan,2020,8 Desember 2020,PN PAMEKASAN,Hakim Ketua Maslikan,"Hakim Anggota Tito Eliandi, Br Hakim Anggota ...",Panitera Pengganti: Saiman,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MOH. SYAIFUR RA...,29 Desember 2020,29 Desember 2020,https://putusan3.mahkamahagung.go.id/direktori...,263_Pid.B_2020_PN_Pmk.pdf,PUTUSAN \nNomor 263/Pid.B/2020/PN Pmk \n \nDEM...
154,https://putusan3.mahkamahagung.go.id/direktori...,"RAHMAD HIDAYAT, SH",SYAMSUL ARIFIN alias ARIK Bin YUSMAN,237/Pid.Sus/2020/PN Pmk,Kesehatan,2020,17 Nopember 2020,PN PAMEKASAN,Hakim Ketua Ari Siswanto,"Hakim Anggota Muhammad Sukamto, Br Hakim Angg...",Panitera Pengganti: M. Syaiful Rachem,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa SYAMSUL ARIFIN ...,29 Desember 2020,29 Desember 2020,https://putusan3.mahkamahagung.go.id/direktori...,237_Pid.Sus_2020_PN_Pmk.pdf,PUTUSAN \nNomor 237/Pid.Sus/2020/PN Pmk \n \nD...
155,https://putusan3.mahkamahagung.go.id/direktori...,AGUS SYAMSUL A. SH. MH,MOH. ROFIUDDIN als ROFIK,268/Pid.B/2020/PN Pmk,Pencurian,2020,11 Desember 2020,PN PAMEKASAN,Hakim Ketua Fidiyawan Satriantoro,"Hakim Anggota Hirmawan Agung Wicaksono, Br Ha...",Panitera Pengganti: Mohamad Luthfi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I : Menyatakan Terdakwa Moh. R...,23 Desember 2020,23 Desember 2020,https://putusan3.mahkamahagung.go.id/direktori...,268_Pid.B_2020_PN_Pmk.pdf,Nomor 268/Pid. B/2020/PN Pmk \n \nDEMI KEADILA...
156,https://putusan3.mahkamahagung.go.id/direktori...,"SULIANINGSIH, SH",1.AMIR MAHMUD BIN BUMIN 2.MOHAMMAD SHOLEH BIN ...,240/Pid.B/2020/PN Pmk,Penipuan,2020,18 Nopember 2020,PN PAMEKASAN,Hakim Ketua Ari Siswanto,"Br Hakim Anggota Tito Eliandi, Hakim Anggota ...",Panitera Pengganti: Monasik,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I : Menyatakan Terdakwa I. AMI...,22 Desember 2020,22 Desember 2020,https://putusan3.mahkamahagung.go.id/direktori...,240_Pid.B_2020_PN_Pmk.pdf,PUTUSAN \nNomor 2 40 / Pid.B / 20 20 / PN Pmk....

In [ ]:
157# df_Pamekasan = df_Pamekasan.iloc[0:125]
# df_Pamekasan

## Dataset Sumenep

In [ ]:
df_Sumenep = pd.read_csv("Dataset Pidana Umum Sumenep.csv")
df_Sumenep

,url_page,penuntut_umum,terdakwa,nomor,kata_kunci,tahun,tanggal_register,lembaga_peradilan,hakim_ketua,hakim_anggota,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"R TEDDY ROOMIUS, S.H.",HERMANTO Bin SUM,20/Pid.B/2024/PN Smp,Penipuan,2024,12 Februari 2024,PN SUMENEP,Hakim Ketua Muhammad Arief Fatony,"Hakim Anggota Iksandiaji Yuris Firmansah, Br ...",Panitera Pengganti Achmad Junaidi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan Terdakwa HERMANTO Bin SUM...,23 April 2024,23 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,20_Pid.B_2024_PN_Smp.pdf,PUTUSAN \nNomor 20/Pid.B/2024/PN Smp \n \nDEMI...
1,https://putusan3.mahkamahagung.go.id/direktori...,"R TEDDY ROOMIUS, S.H.",MEDI HARIYANTO Bin MOH. HASAN,16/Pid.B/2024/PN Smp,Penipuan,2024,1 Februari 2024,PN SUMENEP,Hakim Ketua Muhammad Arief Fatony,"Hakim Anggota Iksandiaji Yuris Firmansah, Br ...",Panitera Pengganti Suraji,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI:1. Menyatakan Terdakwa Medi Hariyant...,23 April 2024,23 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,16_Pid.B_2024_PN_Smp.pdf,Nomor 16/Pid.B/2024/PN Smp \n \nDEMI KEADILAN ...
2,https://putusan3.mahkamahagung.go.id/direktori...,"HANIS ARISTYA HERMAWAN, S.H., M.H",1.HADIYANTO Bin URIP 2.SUKIRYO Bin HASUDDIN 3....,35/Pid.B/2024/PN Smp,Kejahatan Perjudian,2024,8 Maret 2024,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Iksandiaji Yuris Firmansah, Br ...",Panitera Pengganti Achmad Suriyanto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa I. Hardiyanto B...,3 April 2024,3 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,35_Pid.B_2024_PN_Smp.pdf,PUTUSAN\nNomor 35/Pid.B/2024/PN Smp\nDEMI KEAD...
3,https://putusan3.mahkamahagung.go.id/direktori...,"NUR FAJJRIYAH, S.H.",MUHAMAT PAZA SOLA Bin MATSALEH,17/Pid.B/2024/PN Smp,Penganiayaan,2024,5 Februari 2024,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Miftahol Arifin,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI : Menyatakan Terdakwa Muhamat Paza S...,3 April 2024,3 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,17_Pid.B_2024_PN_Smp.pdf,Nomor 17/Pid.B/2024 /PN Smp \n \nDEMI KEADILAN...
4,https://putusan3.mahkamahagung.go.id/direktori...,"HARRY ACHMAD DWI MARYONO, S.H.",1.HENDRI MUAGAM RIARDI bin SUPARMAN 2.RAHIQUL ...,7/Pid.Sus/2024/PN Smp,Kesehatan,2024,8 Januari 2024,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Ulfah Yunita,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I Menyatakan Terdakwa I HENDR...,3 April 2024,3 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,7_Pid.Sus_2024_PN_Smp.pdf,PUTUSAN \nNomor 7/Pid.Sus/2024/PN Smp \n \nDEM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,https://putusan3.mahkamahagung.go.id/direktori...,"NUR FAJJRIYAH, SH",ZAIFUL ISLAM Bin MUDIRUN,274/Pid.Sus/2021/PN Smp,Perlindungan Anak,2022,10 Nopember 2021,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Br Hakim Anggota Anjar Kumboro, Hakim Anggota...",Panitera Pengganti Edi Haris Mulyono,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: 1. Menyatakan Terdakwa ZAIFUL ...,20 Januari 2022,20 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,274_Pid.Sus_2021_PN_Smp.pdf,PUTUSAN \nNomor 274/Pid.Sus/2021/PN Smp \n \nD...
150,https://putusan3.mahkamahagung.go.id/direktori...,HARRY ACHMAD DWI MARYONO,ABDUL MUGHNIS Bin JAUHARI,272/Pid.B/2021/PN Smp,Penganiayaan,2022,10 Nopember 2021,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Sugiarto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Abdul Mughnis B...,20 Januari 2022,20 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,272_Pid.B_2021_PN_Smp.pdf,PUTUSAN \nNomor 272/Pid.B/2021/PN Smp \n \nDEM...
151,https://putusan3.mahkamahagung.go.id/direktori...,"NUR FAJJRIYAH, SH",SUKRAWI Bin SUPATMO,220/Pid.Sus/2021/PN Smp,Perlindungan Anak,2022,2 September 2021,PN SUMENEP,Hakim Ketua Yuniar Yudha Himawan,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti Sugiarto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan terdakwa Sukrawi Bin Supa...,4 Januari 2022,4 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,220_Pid.Sus_2021_PN_Smp.pdf,PUTUSAN \nNomor 220/Pid.Sus/2021/PN Smp \n \nD...
152,https://putusan3.mahkamahagung.go.id/direktori...,"R. TEDDY ROOMIUS, SH",1.ASNAWI BIN SYAFI I 2.HORMAH BIN SAMLI,293/Pid.B/2021/PN Smp,Kejahatan Perjudian,2022,26 Nopember 2021,PN SUMENEP,Hakim Ketua Yuniar Yudha Himawan,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti Nani Irianingsih,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI1. Menyatakan terdakwa I.Asnawi Bin S...,4 Januari 2022,4 Januari 2022,https://putusan3.mahkamahagung.go.id/direktori...,293_Pid.B_2021_PN_Smp.pdf,PUTUSAN \nNomor 293/Pid.B/2021/PN Smp \n \nDEM...
153,https://putusan3.mahkamahagung.go.id/direktori...,"SURYA RIZAL HERTADY, SH",LUTPI Bin MOH.DULLA,254/Pid.B/2021/PN Smp,PenadahanPenerbitandan Pencetakan,2021,13 Oktober 2021,PN SUMENEP,Hakim Ketua Arie Andhika Adikresna,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Suraji,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI:1. Menyatakan Terdakwa LUTPI Bin MOH...,27 Desember 2021,27 Desember 2021,https://putusan3.mahkamahagung.go.id/direktori...,254_Pid.B_2021_PN_Smp.pdf,PUTUSAN \nNomor 254/Pid.B/2021 /PN Smp \n \nDE...

In [ ]:
df = df_Sumenep.iloc[0:125]
df

,url_page,penuntut_umum,terdakwa,nomor,kata_kunci,tahun,tanggal_register,lembaga_peradilan,hakim_ketua,hakim_anggota,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"R TEDDY ROOMIUS, S.H.",HERMANTO Bin SUM,20/Pid.B/2024/PN Smp,Penipuan,2024,12 Februari 2024,PN SUMENEP,Hakim Ketua Muhammad Arief Fatony,"Hakim Anggota Iksandiaji Yuris Firmansah, Br ...",Panitera Pengganti Achmad Junaidi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan Terdakwa HERMANTO Bin SUM...,23 April 2024,23 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,20_Pid.B_2024_PN_Smp.pdf,PUTUSAN \nNomor 20/Pid.B/2024/PN Smp \n \nDEMI...
1,https://putusan3.mahkamahagung.go.id/direktori...,"R TEDDY ROOMIUS, S.H.",MEDI HARIYANTO Bin MOH. HASAN,16/Pid.B/2024/PN Smp,Penipuan,2024,1 Februari 2024,PN SUMENEP,Hakim Ketua Muhammad Arief Fatony,"Hakim Anggota Iksandiaji Yuris Firmansah, Br ...",Panitera Pengganti Suraji,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI:1. Menyatakan Terdakwa Medi Hariyant...,23 April 2024,23 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,16_Pid.B_2024_PN_Smp.pdf,Nomor 16/Pid.B/2024/PN Smp \n \nDEMI KEADILAN ...
2,https://putusan3.mahkamahagung.go.id/direktori...,"HANIS ARISTYA HERMAWAN, S.H., M.H",1.HADIYANTO Bin URIP 2.SUKIRYO Bin HASUDDIN 3....,35/Pid.B/2024/PN Smp,Kejahatan Perjudian,2024,8 Maret 2024,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Iksandiaji Yuris Firmansah, Br ...",Panitera Pengganti Achmad Suriyanto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa I. Hardiyanto B...,3 April 2024,3 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,35_Pid.B_2024_PN_Smp.pdf,PUTUSAN\nNomor 35/Pid.B/2024/PN Smp\nDEMI KEAD...
3,https://putusan3.mahkamahagung.go.id/direktori...,"NUR FAJJRIYAH, S.H.",MUHAMAT PAZA SOLA Bin MATSALEH,17/Pid.B/2024/PN Smp,Penganiayaan,2024,5 Februari 2024,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Miftahol Arifin,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI : Menyatakan Terdakwa Muhamat Paza S...,3 April 2024,3 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,17_Pid.B_2024_PN_Smp.pdf,Nomor 17/Pid.B/2024 /PN Smp \n \nDEMI KEADILAN...
4,https://putusan3.mahkamahagung.go.id/direktori...,"HARRY ACHMAD DWI MARYONO, S.H.",1.HENDRI MUAGAM RIARDI bin SUPARMAN 2.RAHIQUL ...,7/Pid.Sus/2024/PN Smp,Kesehatan,2024,8 Januari 2024,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Ulfah Yunita,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,M E N G A D I L I Menyatakan Terdakwa I HENDR...,3 April 2024,3 April 2024,https://putusan3.mahkamahagung.go.id/direktori...,7_Pid.Sus_2024_PN_Smp.pdf,PUTUSAN \nNomor 7/Pid.Sus/2024/PN Smp \n \nDEM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,https://putusan3.mahkamahagung.go.id/direktori...,"R. TEDDY ROOMIUS, SH",SUTIPNO Bin ABDULLAH,33/Pid.B/2022/PN Smp,Pencurian,2022,3 Februari 2022,PN SUMENEP,Hakim Ketua Yuli Purnomosidi,"Hakim Anggota Yahya Wahyudi, Br Hakim Anggota...",Panitera Pengganti H. Achmad Rifa,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa SUTIPNO Bin ABD...,31 Maret 2022,31 Maret 2022,https://putusan3.mahkamahagung.go.id/direktori...,33_Pid.B_2022_PN_Smp.pdf,PUTUSAN \nNomor 33/Pid.B/2022/PN Smp \n \nDEMI...
121,https://putusan3.mahkamahagung.go.id/direktori...,ANNISA NOVITA SARI,Sri Ayumi Binti Abd. Razak,25/Pid.B/2022/PN Smp,Kejahatan terhadap Kesusilaan,2022,27 Januari 2022,PN SUMENEP,Hakim Ketua Arie Andhika Adikresna,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Miftahol Arifin,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI : Menyatakan Terdakwa Sri Ayumi Bint...,30 Maret 2022,30 Maret 2022,https://putusan3.mahkamahagung.go.id/direktori...,25_Pid.B_2022_PN_Smp.pdf,PUTUSAN \nNomor 25/Pid.B/2022/PN Smp \n \nDEMI...
122,https://putusan3.mahkamahagung.go.id/direktori...,HARRY ACHMAD DWI MARYONO,HERMANO Bin SAHIRUDIN,5/Pid.B/2022/PN Smp,PenadahanPenerbitandan Pencetakan,2022,6 Januari 2022,PN SUMENEP,Hakim Ketua Arie Andhika Adikresna,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...","Panitera Pengganti Alimuddin, S.s.os.",Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI:1. Menyatakan Terdakwa HERMANO Bin S...,17 Maret 2022,17 Maret 2022,https://putusan3.mahkamahagung.go.id/direktori...,5_Pid.B_2022_PN_Smp.pdf,Nomor 5/Pid.B/2022 /PN Smp \n \nDEMI KEADILAN ...
123,https://putusan3.mahkamahagung.go.id/direktori...,"SURYA RIZAL HERTADY, SH",IMAM HIDAYAT Bin MOH.MUNIR . Alm,19/Pid.Sus/2022/PN Smp,Lalu Lintas,2022,20 Januari 2022,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Muhammad Arief Fatony, Br Hakim...",Panitera Pengganti Rb. Muhammad,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa IMAM HIDAYAT Bi...,17 Maret 2022,17 Maret 2022,https://putusan3.mahkamahagung.go.id/direktori...,19_Pid.Sus_2022_PN_Smp.pdf,PUTUSAN \nNomor 19/Pid.Sus/2022/PN Smp \n \nDE...
124,https://putusan3.mahkamahagung.go.id/direktori...,"R. INDRA HADI NIZA, SH",ALI BAKRI Bin SANAYAN,298/Pid.B/2021/PN Smp,Pencurian,2022,26 Nopember 2021,PN SUMENEP,Hakim Ketua Yahya Wahyudi,"Hakim Anggota Yuniar Yudha Himawan, Br Hakim ...",Panitera Pengganti Achmad Junaidi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ALI BAKRIBIN SA...,17 Maret 2022,17 Maret 2022,https://putusan3.mahkamahagung.go.id/direktori...,298_Pid.B_2021_PN_Smp.pdf,PUTUSAN \nNomor 298/Pid. B/2021/PN Smp . \n \n...

## Pre Processing

### Penggabungan Data

In [ ]:
# df = pd.concat([df_Bangkalan, df_Sampang, df_Pamekasan, df_Sumenep], ignore_index=True)
# df

### Cleaning

In [ ]:
def clean_text(text):
  text = text.replace("\n", " ")
  text = text.replace("P U T U S A N", "PUTUSAN").replace("P E N E T A P A N", "PENETAPAN")
  text = text.replace('\uf0d8', '')
  text = re.sub(r'\b(\w)\s*\b', r'\1', text)
  text = re.sub(r'(Hal\.\s*\S+(?:\s*\S+)?\.?\s*)|(Halaman \d+(?:\.\d+)?\s*)|Putusan Nomor \S+\s*', '', text)
  text = re.sub(r'^[A-Za-z]+\.\s*', '', text)
  text = re.sub(r'-+', '', text)
  text = re.sub(r'\s+', ' ', text)
  text = re.sub(r'(pn)\.', r'\1 ', text) # Memperbaiki nomor putusan mengganti titik setelah PN dengan spasi
  text = re.sub(r'(\d+)\s*([a-zA-Z]+)\s*(\d+)', r'\1 \2 \3', text) # Memperbaiki format tanggal jika 1 angka di kasih 0
  text = re.sub(r'(\b\d\b)', lambda x: f'0{x.group(1)}', text)
  text = re.sub(r"(\d+)\.(\w)", r"\1. \2", text)
  text = re.sub(r'\b(jkt) (pst)\b', r'\1.\2', text)
  text = re.sub(r'halaman\s*\d+\s*dari\s*\d+\s*', '', text) # Menghapus kata "halaman 1 dari ..."
  # text = re.sub(r'putusannomor(\d+/pid\.b/\d+/pnspg)', r'', text) # Menghapus bagian putusannomorXX/pid.b/YYYY/pnspg

  return text.lower()

df['content'] = df["content"].apply(clean_text)

<ipython-input-123-f752c2c3e581>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = df["content"].apply(clean_text)

In [ ]:
df['content'][100]

'putusan nomor 45 /pid. b/2022/pn smp demi keadilan berdasarkan ketuhanan yang maha esa pengadilan negeri sumenep yang mengadili perkara pidana dengan acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai berikut dalam perkara terdakwa : 01. nama lengkap : endang ekowati; 02. tempat lahir : sumenep ; 03. umur / tanggal lahir : 55 tahun / 07 september 1966 ; 04. kebangsaan : indonesia ; 05. jenis kelamin : perempuan ; 06. tempat tinggal : perum satelit jalan aquarius nomor 51 desa pabian kecamatan kota kabupaten sumenep, jalan sulthan abdurrahman gang iii nomor 6desa kolor kecamatan kota kabupaten sumenep; 07. agama : islam; 08. pekerjaan : mengurus rumah tangga ; terdakwa tidak ditahan; terdakwa dipersidangan didampingi penasihat hukum kamarullah, s.h., m.h., syuhada’ mashari, s.h., hidayatullah, s.h., muhammad vawaid, s.h., nadianto, s.h., m.h., angga adi negoro putra, s.h., ibnu hajar, s.h., para advokat dan konsultan hukum pada kantor hukum “lembaga bantuan hukum (lbh) achmad madani putra dan rekan – rekan” alamat kantor jalan teuku umar iv/12 apandian sumenep, berdasarkan surat kuasa khusus tanggal 24 februari 2022; pengadilan negeri tersebut ; setelah membaca : \xad penetapan ketua pe ngadilan negeri sumenep nomor 45 /pid.b/2022/pn smp tanggal 18 februari 2022 tentang penunjukan majelis hakim pemeriksa perkara ini; \xad penetapan majelis hakim pengadilan negeri sumenep nomor 45/pid.b/2022/pn smp tanggal 18 februari 2022 tentang penetapan ha ri sidang; \xad berkas perkara dan surat – surat lain yang bersangkutan ; pid.i.a.3setelah mendengar keterangan saksi – saksi dan terdakwa serta memperhatikan bukti surat dan barang bukti yang diajukan di persidangan; setelah mendengar pembacaan tuntutan pidana yang diajukan oleh penuntut umum yang pada pokoknya sebagai berikut: 01. menyatakan terdakwa endang ekowati bersalah melakukan tindak pidana “dengan membuat surat palsu atau memalsukan surat yang dapat menimbulkan sesuatu hak, perikatan atau pembebasan hutang atau yang diperuntukkan sebagai bukti daripada sesuatu hal dengan maksud untuk memakai atau menyuruh orang lain memakai surat tersebut seolah olah isinya benar dan tidak dipalsu, diancam jika pemakaian tersebut dapat menimbulkan kerugian karena pemalsuan surat ” sebagaimana diatur dalam dakwaan primair penuntut umum yakni melanggar pasal 263 ayat (01) kuhp ; 02. menjatuhkan pidana terhadap terdakwa endang ekowati dengan pidana penjara selama 02 (dua) tahun ; 03. menyatakan barang bukti berupa : \uf02d 03 (tiga) lembar surat pengantar permohonan pemeriksaan laboratoris kriminalistik terhadap tanda tangan yang diduga non identic dari kapolres sumenep kepada kabidlabfor polda jatim nomor: b/01/i/res.01. 01. 01/2021/satreskrim, tanggal 25 januari 2021; \uf02d 01 (satu) lembar surat pengantar pengiriman hasil pemeriksaan tanda tangan dari kabidlabfor polda jatim kepada kapolres sumenep nomor : b/1986/ii/res.09. 02/2021/bidlabfor, tanggal 22 februari 2021 ; \uf02d 01 (satu) berkas berita acara pemeriksaan laboratorik kriminalistik nomor : lab/1251/dtf/2021 tanggal 18 februari 2021 ; \uf02d 01 (satu) lembar kwitansi berwarna biru tertanggal 03 januari 2019 yang bertuliskan telah terima uang dari endang kadar uang sejumlah seratus juta rupiah dan lima puluh juta rupiah untuk pembayaran hutang endang dengan penerima dan tanda tang an di atas materai 6000 atas nama bu sruji dan 01 ( satu) lembar kwitansi berwarna orange hijau tertanggal 17 desember 2018 yang bertuliskan telah terima uang dari endang kadar uang sejumlah sembilan puluh juta rupiah untuk pembayaran hutang endang + 3hari dengan penerima dan tanda tangan di atas materai 6000 atas nama hj. bu sruji , tetap terlampir dalam berkas perkara ; 04. menetapkan supaya terdakwa dibebani biaya perkara sebesar rp 05. 000, 00 (lima ribu rupiah); setelah mendengar pembelaan terdakwa dan penasihat hukum terdakwa yang pada pokoknya mohon keringanan hukuman; setelah mendengar tanggapan penuntut umum terhadap pembelaan terdakwa dan penasihat hukum terdakwa yang pada pokoknya menyatakan tetap pada tuntutannya ; setelah mendengar tanggapan terdakwa dan penasihat hukum terdakwa terhadap tanggapan penuntut umum yang pada pokoknya tetap pada pembelannya ; menimbang, bahwa terdakwa diajukan ke persidangan oleh penuntut umum didakwa berdasarkan surat dakwaan sebagai berikut : primair; bahwa terdakwa endang ekowati pada hari dan tanggal yang sudah tidak diingat secara pasti bulan januari 2021, atau setidak tidaknya dalam bulan januari 2021 atau setidak tidaknya dalam tahun 2021, bertempat di rumah hj.sayyaroh jalan antariksa 45 a, rt 02 rw 04, desa pabian, kecamatan kota kabupaten sumenep atau setidak tidaknya di suatu tempat yang masih termasuk dalam daerah hukum pengadilan negeri sumenep yang berwenang untuk memeriksa dan mengadili, dengan membuat surat palsu atau memalsukan surat yang dapat menimbulkan sesuatu hak, perikatan atau pembebasan hutang atau yang diperuntukkan sebagai bukti daripada sesuatu hal dengan maksud untuk memakai atau menyuruh orang lain memakai surat tersebut seolah olah isinya benar dan tidak dipalsu, diancam jika pemakaian tersebut dapat menimbulkan kerugian karena pemalsuan surat , perbuatan ini dilakukan oleh terdakwa dengan cara sebagai berikut : bahwa berawal ketika terdakwa endang ekowati pada tanggal 22 desember 2018 meminjam uang kepada saksi hj.sayyaroh se besar rp. 380. 000. 000, (tiga ratus delapan puluh juta rupiah) dengan alasan untuk memperpanjang pajak perusahaan kayu sengon, namun hingga saat ini uang tersebut tidak dikembalikan oleh terdakwa endang ekowati kepada saksi hj.sayyaroh, kemudian saksi hj.sa yyaroh melaporkan kejadian ini ke polres sumenep ; bahwa ketika dilakukan penyidikan, di temukan bukti yaitu surat kwitansi pembayaran hutang oleh terdakwa endang ekowati yang mana terdakwa endang ekowati mengaku sudah membayar dan menunjukan bukti kwitan si pembayaran hutang terdakwa endang kadar tertanggal 17 desember 2018 pembayaran hutang sebesar rp. 90. 000. 000 dan surat kwitansi pembayaran hutang terdakwa endang kadar tertanggal 03 januari 2019 pembayaran hutang sebesar rp 100. 000. 000 + 50. 000. 000 yang mana di kwitansi tersebut ada tanda tangan saksi hj.sayyaroh dan tanda tangan saksi hj.sayyaroh tersebut telah dipalsu oleh terdakwa endang ekowati, karena saksi hj.sayyroh tidak pernah menerima uang pembayaran hutang dari terdakwa endang ekowati dan juga saksi hj.sayyaroh tidak pernah menandatangani 02 (dua) kwitansi pembayaran dari terdakwa endang ekowati tersebut ; bahwa selanjutnya penyidik dari unit ipidum polres sumenep melakukan tes laboratorium forensik dengan adanya 2lembar kwitansi yang terdap at tanda saksi hj.sayyaroh yang diduga palsu, dan hasil dari labfor polda jatim no.lab : 1251/dtf/2021 tanggal 18 pebruari 2021 menyatakan bahwa tanda tangan saksi hj.sayyaroh yang terdapat di 2lembar kwitansi tersebut tidak edentik dengan tanda tangan mi lik saksi hj.sayyaroh; perbuatan terdakwa sebagaimana diatur dan diancam pidana dalam pasal 263 ayat (01) kuhp ; subsidair ; bahwa terdakwa endang ekowati pada hari dan tanggal yang sudah tidak diingat secara pasti bulan januari 2021, atau setidak tidaknya dalam bulan januari 2021 atau setidak tidaknya dalam tahun 2021, bertempat di rumah hj.sayyaroh jalan antariksa 45 a, rt 02 rw 04, desa pab ian, kecamatan kota kabupaten sumenep atau setidak tidaknya di suatu tempat yang masih termasuk dalam daerah hukum pengadilan negeri sumenep yang berwenang untuk memeriksa dan mengadili, dengan sengaja memakai surat palsu atau yang dipalsukan seolah olah sejati, jika pemakaian surat itu dapat menimbulkan kerugian , perbuatan ini dilakukan oleh terdakwa dengan cara sebagai berikut : bahwa berawal ketika terdakwa endang ekowati pada tanggal 22 desember 2018 meminjam uang kepada saksi hj.sayyaroh sebesar rp. 380. 000. 000, (tiga ratus delapan puluh juta rupiah) dengan alasan untuk memperpanjang pajak perusahaan kayu sengon, namun hingga saat ini uang tersebut tidak dikembalikan oleh terdakwa endang ekowati kepada saksi hj.sayyaroh, kemudian saksi hj.sayyaroh me laporkan kejadian ini ke polres sumenep ; bahwa ketika dilakukan penyidikan, di temukan bukti yaitu surat kwitansi pembayaran hutang oleh terdakwa endang ekowati yang mana terdakwa endang ekowati mengaku sudah membayar dan menunjukan bukti kwitansi pembay aran hutang terdakwa endang kadar tertanggal 17 desember 2018 pembayaran hutang sebesar rp. 90. 000. 000 dan surat kwitansi pembayaran hutang terdakwa endang kadar tertanggal 03 januari 2019 pembayaran hutang sebesar rp 100. 000. 000 + 50. 000. 000 yang mana di kwitansi tersebut ada tanda tangan saksi hj.sayyaroh dan tanda tangan saksi hj.sayyaroh tersebut telah dipalsu oleh terdakwa endang ekowati, karena saksi hj.sayyroh tidak pernah menerima uang pembayaran hutang dari terdakwa endang ekowati dan juga saksi hj .sayyaroh tidak pernah menandatangani 02 (dua) kwitansi pembayaran dari terdakwa endang ekowati tersebut ; bahwa selanjutnya penyidik dari unit ipidum polres sumenep melakukan tes laboratorium forensik dengan adanya 2lembar kwitansi yang terdapat tanda saksi hj.sayyaroh yang diduga palsu, dan hasil dari labfor polda jatim no.lab : 1251/dtf/2021 tanggal 18 pebruari 2021 menyatakan bahwa tanda tangan saksi hj.sayyaroh yang terdapat di 2lembar kwitansi tersebut tidak edentik dengan tanda tangan milik saksi hj.sayyaroh; perbuatan terdakwa sebagaimana diatur dan diancam pidana dalam pasal 263 ayat (02) kuhp; menimbang, bahwa terhadap dakwaan penuntut umum tersebut terdakwa telah mengerti isi dan maksudnya serta tidak mengajukan keberatan; menimbang, bahwa untuk membuktikan dakwaannya penuntut umum telah mengajukan saksi – saksi yang telah memberikan keterangan dibawah sumpah, pada pokoknya menerangkan sebagai berikut ; 01. saksi hj. sayyarah; \uf02d bahwa tanggal 22 desember 2018 terdakwa meminjam uang kepada saksi sebesar rp380. 000. 000, 00 (tiga ratus delapan puluh juta rupiah) dengan alasan untuk memperpanjang pajak perusahaan kayu sengon, namun hingga saat ini uang tersebut tidak dikembalikan oleh terdakwa ; \uf02d bahwa terdakwa mengaku sudah membayar hutang tersebut deng an menunjukan bukti kwitansi pembayaran hutang terdakwa tertanggal 17 desember 2018 pembayaran hutang sebesar rp90. 000. 000 ,00 (sembilan puluh juta rupiah) dan surat kwitansi pembayaran hutang tertanggal 03 januari 2019 pembayaran hutang sebesar rp100. 000. 000,00 (seratus juta rupiah) + rp50. 000. 000 ,00 (lima puluh juta rupiah) yang mana di kwitansi tersebut ada tanda tangan saksi ; \uf02d bahwa tanda tangan saksi tersebut telah dipalsu oleh terdakwa , karena saksi tidak pernah menandatangani 02 (dua) kwitansi pembayara ndari terdakwa tersebut ; \uf02d bahwa saksi tidak pernah menerima uang pembayaran hutang dari terdakwa; menimbang, bahwa atas keterangan saksi tersebut terdakwa menyatakan keberatan karena terdakwa telah membayar hutang sebesar rp225. 000. 000,00 (dua ratus dua puluh lima juta rupiah) dan rp100. 000. 000,00 (seratus juta rupiah). terhadap keberatan terdakwa tersebut, saksi tetap pada keterangannya. seme ntara terhadap keterangan saksi yang lain terdakwa membenarkan dan tidak keberatan; 02. saksi siti aminah; \uf02d bahwa saksi mengetahui dalam perkara ini ada masalah pemalsuan tanda tangan saksi hj. sayyarah ya ng ada dalam kwitansi pembayaran uang yang ditandatangani oleh terdakwa; \uf02d bahwa saksi diberitahu oleh saksi hj. sayyarah kalau terdakwa pada tanggal 22 desember 2018 meminjam uang kepada saksi hj. sayyarah sebesar rp380. 000. 000, 00 (tiga ratus delapan puluh juta rupiah) ; \uf02d bahwa terdakwa mengaku sudah membayar hutang tersebut dengan menunjukan bukti kwitansi pembayaran hutang terdakwa tertanggal 17 desembe r2018 pembayaran hutang sebesar rp90. 000. 000 ,00 (sembilan puluh juta rupiah) dan surat kwitansi pembayaran hutang tertanggal 03 januari 2019 pembayaran hutang sebesar rp100. 000. 000 ,00 (seratus juta rupiah) + rp50. 000. 000 ,00 (lima puluh juta rupiah) yang mana di kwitansi tersebut ada tanda tangan saksi hj. sayyarah ; \uf02d bahwa tanda tangan saksi hj. sayyarah tersebut telah dipalsu oleh terdakwa , karena saksi hj. sayyarah tidak pernah menandatangani 02 (dua) kwitansi pembayaran dari terdakwa tersebut dan ti dak pernah menerima uang pembayaran hutang dari terdakwa; menimbang, bahwa terhadap keterangan saksi tersebut terdakwa menyatakan benar dan tidak keberatan ; 03. saksi sakinah; \uf02d bahwa saksi mengetahui dalam perkara ini ada masalah pemalsuan tanda tangan saksi hj. sayyarah ya ng ada dalam kwitansi pembayaran uang yang ditandatangani oleh terdakwa; \uf02d bahwa saksi mengetahui hal tersebut karena diberitahu oleh saksi hj. sayyarah kalau terdakwa pada tanggal 22 desember 2018 meminjam uang kepada saksi hj. sayyarah sebesar rp380. 000. 000, 00 (tiga ratus delapan puluh juta rupiah) ; \uf02d bahwa terdakwa mengaku sudah membayar hutang tersebut dengan menunjukan bukti kwitansi pembayaran hutang terdakwa tertanggal 17 desember 2018 pembayaran hutang sebesar rp90. 000. 000 ,00 (sembil an puluh juta rupiah) dan surat kwitansi pembayaran hutang tertanggal 03 januari 2019 pembayaran hutang sebesar rp100. 000. 000 ,00 (seratus juta rupiah) + rp50. 000. 000 ,00 (lima puluh juta rupiah) yang mana di kwitansi tersebut ada tanda tangan saksi hj. sayy arah; \uf02d bahwa tanda tangan saksi hj. sayyarah tersebut telah dipalsu oleh terdakwa , karena saksi hj. sayyarah tidak pernah menandatangani 02 (dua) kwitansi pembayaran dari terdakwa tersebut dan tidak pernah menerima uang pembayaran hutang dari terdakwa; 04. saksi risang jati pakuan, s.h.; \uf02d bahwa saksi mengetahui masalah pemalsuan tanda tangan saksi hj. sayyarah yag ada dalam kwitansi pembayaran uang yang ditandatangani oleh terdakwa; \uf02d bahwa ketika dilakukan penyidikan, ditemukan bukti surat kwitansi pembayaran hutang oleh terdakwa dimana terdakwa mengaku sudah membayar dan menunjukan bukti kwitansi pembayaran hutang terdakwa tertanggal 17 desember 2018 pembayaran hutang sebesar rp90. 000 .000 (sembilan puluh juta rupiah) dan surat kwitansi pembayaran hutang terdakwa tertanggal 03 januari 2019 pembayaran hutang sebesar rp100. 000. 000 ,00 (seratus juta rupiah) + rp50. 000. 000 ,00 (lima puluh juta rupiah) yang mana di kwitansi tersebut ada tanda tangan saksi hj.sayyaroh; \uf02d bahwa tanda tangan saksi hj. sayyaroh tersebut telah dipalsu oleh terdakwa, karena saksi hj. sayyroh merasa tidak pernah menerima uang pembayaran hutang dari terdakwa dan juga saksi hj. sayyaroh tidak pernah menandatangani 02 (dua) kwitansi pem bayaran dari terdakwa tersebut ; \uf02d bahwa selanjutnya penyidik unit ipidum polres sumenep melakukan tes laboratorium forensik dengan adanya 02 (dua) lembar kwitansi yang terdapat tanda tangan saksi hj. sayyaroh yang diduga palsu, dan hasil dari la bfor polda jatim no.lab : 1251/dtf/2021 tanggal 18 pebruari 2021 menyatakan bahwa tanda tangan saksi hj. sayyaroh yang terdapat di 02 (dua) lembar kwitansi tersebut tidak edentik dengan tanda tangan milik saksi hj. sayyaroh ; menimbang, bahwa terhadap keterangan saksi tersebut terdakwa menyatakan benar dan tidak keberatan ; menimbang, bahwa terdakwa di persidangan telah memberikan keterangan yang pada pokoknya sebagai berikut ; \uf02d bahwa pada tanggal 22 desember 2018 terdakwa meminjam uang kepada saksi hj.sayyaroh sebesar rp380. 000. 000, 00 (tiga ratus delapan puluh juta rupiah) dengan alasan untuk memperpanjang pajak perusahaan kayu sengon; \uf02d bahwa ketika dilakukan penyidikan, terdakwa menunjukkan kepada penyidik polres sumenep su rat kwitansi pembayaran hutang oleh terdakwa yang mana terdakwa mengaku sudah membayar dan menunjukan bukti kwitansi pembayaran hutang terdakwa tertanggal 17 desember 2018 pembayaran hutang sebesar rp90. 000. 000 (sembilan puluh juta rupiah) dan surat kwitan si pembayaran hutang terdakwa tertanggal 03 januari 2019 pembayaran hutang sebesar rp100. 000. 000 ,00 (seratus juta rupiah) + rp50. 000. 000 ,00 (lima puluh juta rupiah) yang mana di kwitansi tersebut ada tanda tangan saksi hj.sayyaroh; \uf02d bahwa tanda tangan saksi hj.sayyaroh dalam 02 (dua) kwitansi tersebut ditanda tangani oleh terdakwa; \uf02d bahwa terdakwa menandatangani 02 (dua) kwitansi pembayaran hutang tersebut karena terdakwa sudah membayar pinjaman uang kepada saksi hj. sayyarah , namun saksi hj. sayyarah tidak mengakui kalau terdakwa sudah membayar hutang ; \uf02d bahwa terdakwa sudah membayar semua pinjaman uang dari saksi hj. sayyarah ; menimbang, bahwa penuntut umum mengajukan barang bukti sebagai berikut : \uf02d 03 (tiga) lembar surat pengantar permohonan pemeriksaan laboratoris kriminalistik terhadap tanda tangan yang diduga non identic dari kapolres sumenep kepada kabidlabfor polda jatim nomor: b/01/i/res.01. 01. 01/2021/satreskrim tanggal 25 januari 2021; \uf02d 01 (satu) lembar surat pengantar pengiriman hasil pemerik saan tanda tangan dari kabidlabfor polda jatim kepada kapolres sumenep nomor: b/1986/ii/res.09. 02/2021/bidlabfor tanggal 22 februari 2021 ; \uf02d 01 (satu) berkas berita acara pemeriksaan laboratorik kriminalistik nomor: lab/1251/dtf/2021 tanggal 18 februari 2021 ; \uf02d 01 (satu) lembar kwitansi berwarna biru tertanggal 03 januari 2019 yang bertuliskan telah terima uang dari endang kadar uang sejumlah seratus juta rupiah dan lima puluh juta rupiah untuk pembayaran hutang endang dengan penerima dan tanda tangan diatas matera i6000 atas nama bu sruji dan 01 ( satu) lembar kwitansi berwarna orange hijau tertanggal 17 desember 2018 yang bertuliskan telah terima uang dari endang kadar uang sejumlah sembilan puluh juta rupiah untuk pembayaran hutang endang + 3hari dengan penerima dan tanda tangan di atas materai 6000 atas nama hj. bu sruji; menimbang, bahwa barang bukti tersebut telah disita secara sah sesuai aturan hukum yang berlaku sehingga dapat diajukan ke persidangan untuk memperkuat pembuktian; menimbang, bahwa barang bukti tersebut telah diperlihatkan kepada saksi dan terdakwa dimana saksi – saksi dan terdakwa masih mengenali dan membenarkannya ; menimbang, bahwa selanjutnya terjadilah segala sesuatu seperti yang termuat dalam berita acara per sidangan yang untuk mempersingkat uraian putusan ini secara keseluruhan dianggap ikut termuat dan terbaca dalam putusan ini ; menimbang, bahwa berdasarkan alat bukti dan barang bukti yang diajukan diperoleh fakta – fakta hukum sebagai berikut : \uf02d bahwa benar tanggal 22 desember 2018 terdakwa meminjam uang kepada saksi hj. sayyarah sebesar rp380. 000. 000, 00 (tiga ratus delapan puluh juta rupiah) dengan alasan untuk memperpanjang pajak perusahaan kayu sengon, dan hingga saat ini uang tersebut belum dikembalikan oleh terdakwa ; \uf02d bahwa benar terdakwa mengaku sudah membayar hutang tersebut dengan menunjukan bukti kwitansi pembayaran hutang terdakwa tertanggal 17 desember 2018 pembayaran hutang sebesar rp90. 000. 000 ,00 (sembilan puluh juta rupiah) dan surat kwitansi pembayaran hutang tertanggal 03 januari 2019 pembayaran hutang sebesar rp100. 000. 000 ,00 (seratus juta rupiah) + rp50. 000. 000 ,00 (lima puluh juta rupiah) yang mana di kwitansi tersebut ada tanda tangan saksi hj. sayyarah ; \uf02d bahwa benar tanda tangan saksi hj. sayyarah dalam kwitansi pembayaran hutang tersebut telah telah dipalsu oleh terdakwa , karena saksi hj. sayyarah tidak pernah menandatangani 02 (dua) kwitansi pembayaran dari terdakwa tersebut ; \uf02d bahwa benar saksi hj. sayyarah tidak pernah menerima uang pembayaran hutang dari terdakwa; \uf02d bahwa benar saksi minah dan saksi sakinah mengetahui masalah pemalsuan tanda tangan saksi hj. sayyarah ya ng ada dalam kwitansi pembayaran uang yang ditandatangani oleh terdakwa karena diberitahu oleh saksi hj. sayyarah ; \uf02d bahwa benar saksi risang jati pakuan, s.h. mengetahui ketika dilakukan penyidikan, ditemukan kwitansi pembayaran hutang oleh terdakwa kepada saksi hj. sayyarah , dimana terdakwa mengaku sudah membayar dan menunjukan bukti kwitansi pembayaran h

In [ ]:
# def find_similar_sentence(text, target_sentence):
#   sentences = text.split(';')  # Pisahkan teks menjadi kalimat-kalimat
#   if len(target_sentence.split()) > 1:
#     # Gunakan TF-IDF untuk mewakili teks
#     vectorizer = TfidfVectorizer()
#     vectors = vectorizer.fit_transform(sentences + [target_sentence])

#     # Hitung cosine similarity antara vektor target dan vektor kalimat
#     similarity_scores = cosine_similarity(vectors[-1], vectors[:-1])[0]

#     # Temukan kalimat dengan similarity tertinggi
#     max_similarity_index = similarity_scores.argmax()

#     if similarity_scores[max_similarity_index] > 0.0:  # Ubah ambang batas sesuai kebutuhan
#         return sentences[max_similarity_index].strip()
#     else:
#         return None
#   else:
#     return target_sentence

### Anotasi Data

In [ ]:
def generate_label(data):
  label = {}
  nomor_putusan = data["nomor"].lower() # cek nomor putusan
  # cek terdakwa
  if any(char.isdigit() for char in data["terdakwa"]): # jika terdakwa lebih dari satu
    terdakwa = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', data["terdakwa"].lower().replace("(alm)", ''))
  else: # jika terdakwa hanya satu
    terdakwa = re.findall(r'(.*?)\s*(?=\d+\.|$)', data["terdakwa"].lower().replace("(alm)", ''))
  terdakwa_filtered = [item for item in terdakwa if item.strip()] # menghapus index kosong
  jenis_dakwaan = re.findall(r'tindak pidana\s+“([^“”]*)', data["content"].lower()) #cek dakwaan
  pasal = re.findall(r'pasal\s+([^;]*kuhp\b)', data["content"].lower())# cek pasal
  tgl_putusan = re.sub(r'(\b\d\b)', lambda x: f'0{x.group(1)}', data["tanggal_dibacakan"].lower()) # cek tanggal
  hakim_ketua = data["hakim_ketua"].lower().replace("hakim ketua", '').strip() # cek hakim ketua
  hakim_anggota = data["hakim_anggota"].lower().replace("hakim anggota", '').strip().split(',') # cek hakim anggota
  panitera = data["panitera"].lower().replace("panitera pengganti", "").replace(":", "").strip() # cek panitera
  penuntut_umum = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', data["penuntut_umum"].lower()) # cek penuntut umum
  amar_lainnya = data["amar_lainnya"].lower() # cek amar lainnya
  catatan_amar = re.sub(r'(\w+)\s*(\d+\.)', r'\1 \2', re.sub(r'(pn)\.', r'\1 ', data["catatan_amar"].lower().replace("mengadili:", ''))) # cek catatan amar
  tuntutan_hukuman = re.search(r'selama(.*?);', data["content"].lower()) # cek tuntutan hukuman
  if tuntutan_hukuman:
      tuntutan_hukuman = tuntutan_hukuman.group(1).strip() # menghilangkan re Match
  else:
      tuntutan_hukuman = ""
  putusan_hukuman = re.search(r'selama(.*?);', data["catatan_amar"].lower()) # cek putusan hukuman
  if putusan_hukuman:
      putusan_hukuman = putusan_hukuman.group(1).strip() # menghilangkan re Match
  else:
      putusan_hukuman = ""
  label[nomor_putusan] = "B_VERN"
  label[tgl_putusan] = "B_TIMV"
  label[hakim_ketua] = "B_JUDP"
  label[panitera] = "B_REGI"
  label[tuntutan_hukuman] = "B_PENA"
  label[putusan_hukuman] = "B_PUNI"
  label[pasal[0] if pasal else ""] = "B_ARTV"
  if not hakim_anggota:
    label[data["hakim_anggota"].lower()] = "B_JUG"
  else:
    label.update({anggota.strip() : "B_JUG" for anggota in hakim_anggota})
  if not penuntut_umum:
    label[data["penuntut_umum"].lower()] = "B_PROS"
  else:
    label.update({i.strip() : "B_PROS" for i in penuntut_umum})
  if not terdakwa_filtered:
    label[data["terdakwa"].lower()] = "B_DEFN"
  else:
    label.update({i.strip() : "B_DEFN" for i in terdakwa_filtered if i})
  if not jenis_dakwaan:
    label[data["kata_kunci"].lower()] = "B_CRIA"
  else:
    label.update({i.strip() : "B_CRIA" for i in jenis_dakwaan if i})
  return label

def labeling_token(text, label_dict):
  tokens = text.split()
  labeled_tokens = ['O'] * len(tokens)
  find_label = dict()
  for key, value in label_dict.items():
      words = key.split()
      # print(words, value)
      current_dict = find_label
      for word in words[:-1]:
          word = re.sub(r'[.,;]', '', word)
          current_dict = current_dict.setdefault(word, {})
      if words:
          last_word = re.sub(r'[.,;]', '', words[-1])
          current_dict[last_word] = {'label': value}
  # print(find_label)

  temp_idx_token = []
  find_label_selected = find_label
  for i, token in enumerate(tokens):
    clean_token = re.sub(r'[.,;]', '', token)
    # print(clean_token)
    if clean_token in find_label_selected:
      find_label_selected = find_label_selected[clean_token]
      temp_idx_token.append(i)
      # print(clean_token)
      # print(find_label_selected)
      if 'label' in find_label_selected:
        tag = find_label_selected['label']
        # print(clean_token, tag, temp_idx_token)
        new_label = [tag if ind == 0 else tag.replace('B', 'I') for ind in range(len(temp_idx_token))]
        labeled_tokens[temp_idx_token[0]:temp_idx_token[0] + len(new_label)] = new_label
        temp_idx_token = []
        find_label_selected = find_label
    else:
      temp_idx_token = []
      find_label_selected = find_label

  return labeled_tokens

def countLabel(result, label_ori):
  label_found = {}
  temp = []
  for i, row in result.iterrows():
    for t, l in zip(row["text"], row["label"]):
      if l != 'O' and l.replace('I_', 'B_') not in temp:
        temp.append(l.replace('I_', 'B_'))

  label_found[f"Dokumen Ke-{i+1}"] = (len(temp), label_ori, temp)

  return label_found

def accuracy(result):
  sum_label = 0
  label_in = 0
  for key, value in result.items():
    print(f"{key} => Data Terlebel : {value[0]} ; Total Label : {value[1]} ; Label : {value[2]}")
    sum_label+= value[1]
    label_in += value[0]
  print("Accuracy : {label_in/sum_label * 100}")

  return f"Accuracy : {label_in/sum_label * 100}"

def anotasi(data):
  new_data = pd.DataFrame([], columns=['doc','text', 'label'])
  # start = 0
  # end = 0
  count_label = {}
  for i, row in tqdm(data.iterrows(), total=len(data), desc="Annotating"):
    label = generate_label(row)
    labeled_tokens = labeling_token(row["content"], label)
    new_data = pd.concat([new_data, pd.DataFrame({"doc": [row["nama_file"].split()],"text": [row["content"].split()], "label": [labeled_tokens]})], ignore_index=True)
    new_data = new_data.explode('doc').reset_index(drop=True)
    count_label.update(countLabel(new_data.loc[i:i], len(set(label.values()))))

  return (new_data, count_label)

### Cek Anotasi per Data

In [ ]:
generate_label(df.iloc[1])

{'16/pid.b/2024/pn smp': 'B_VERN',
 '23 april 2024': 'B_TIMV',
 'muhammad arief fatony': 'B_JUDP',
 'suraji': 'B_REGI',
 '02 (dua) tahun dan 08 (delapan) bulan penjara dikurangi selama terdakwa tersebut ditahan . 03. barang bukti berupa: 01 (satu) unit mobil toyota kijang innova warna abu abu metalik, tahun pembuatan 2015, nomor polisi m1153 tw kembali ke saksi agus aliyanto . 04. terdakwa agar dibebani membayar biaya perkara sebesar rp.05. 000, (lima ribu rupiah). setelah mendengar permohonan terdakwa yang pada pokoknya memohon keringanan hukuman': 'B_PENA',
 '1 (satu) tahun dan 10 (sepuluh) bulan': 'B_PUNI',
 '372 kuhp': 'B_ARTV',
 'iksandiaji yuris firmansah': 'B_JUG',
 'br   ekho pratama': 'B_JUG',
 'r teddy roomius, s.h.': 'B_PROS',
 'medi hariyanto bin moh. hasan': 'B_DEFN',
 'penipuan': 'B_CRIA'}

In [ ]:
new_df, count_label = anotasi(df)

Annotating: 100%|██████████| 125/125 [00:02<00:00, 48.53it/s]

### Hasil Anotasi

In [ ]:
new_df

,doc,text,label
0,20_Pid.B_2024_PN_Smp.pdf,"[putusan, nomor, 20/pid.b/2024/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
1,16_Pid.B_2024_PN_Smp.pdf,"[nomor, 16/pid.b/2024/pn, smp, demi, keadilan,...","[O, B_VERN, I_VERN, O, O, O, O, O, O, O, O, O,..."
2,35_Pid.B_2024_PN_Smp.pdf,"[putusan, nomor, 35/pid.b/2024/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
3,17_Pid.B_2024_PN_Smp.pdf,"[nomor, 17/pid.b/2024, /pn, smp, demi, keadila...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,7_Pid.Sus_2024_PN_Smp.pdf,"[putusan, nomor, 07/pid.sus/2024/pn, smp, demi...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...,...
120,33_Pid.B_2022_PN_Smp.pdf,"[putusan, nomor, 33/pid.b/2022/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
121,25_Pid.B_2022_PN_Smp.pdf,"[putusan, nomor, 25/pid.b/2022/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
122,5_Pid.B_2022_PN_Smp.pdf,"[nomor, 05/pid.b/2022, /pn, smp, demi, keadila...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
123,19_Pid.Sus_2022_PN_Smp.pdf,"[putusan, nomor, 19/pid.sus/2022/pn, smp, demi...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
124,298_Pid.B_2021_PN_Smp.pdf,"[putusan, nomor, 298/pid., b/2021/pn, smp, ., ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [ ]:
print(new_df.iloc[1])

doc                               16_Pid.B_2024_PN_Smp.pdf
text     [nomor, 16/pid.b/2024/pn, smp, demi, keadilan,...
label    [O, B_VERN, I_VERN, O, O, O, O, O, O, O, O, O,...
Name: 1, dtype: object

### Cek Akurasi Anotasi

In [ ]:
accuracy(count_label)

Dokumen Ke-1 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_DEFN', 'B_TIMV', 'B_JUDP', 'B_REGI', 'B_JUG']
Dokumen Ke-2 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_REGI', 'B_JUG']
Dokumen Ke-3 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-4 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-5 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_PROS', 'B_REGI']
Dokumen Ke-6 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_PROS', 'B_JUG']
Dokumen Ke-7 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_REGI', 'B_PROS', 'B_JUG']
Dokumen Ke-8 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_REGI', 'B_PROS', 'B_JUG']
Dokumen Ke-9 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-10 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_PROS']
Dokumen Ke-11 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-12 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-13 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_TIMV']
Dokumen Ke-14 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-15 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-16 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-17 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_CRIA', 'B_PENA', 'B_JUDP', 'B_REGI', 'B_PROS', 'B_JUG']
Dokumen Ke-18 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-19 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_DEFN', 'B_ARTV', 'B_PENA', 'B_PUNI', 'B_TIMV', 'B_JUG', 'B_REGI', 'B_PROS', 'B_JUDP']
Dokumen Ke-20 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-21 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-22 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS', 'B_JUDP']
Dokumen Ke-23 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-24 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-25 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-26 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-27 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_PROS']
Dokumen Ke-28 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_TIMV', 'B_JUDP', 'B_JUG']
Dokumen Ke-29 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-30 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-31 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_PENA', 'B_ARTV', 'B_DEFN', 'B_TIMV', 'B_JUDP', 'B_JUG']
Dokumen Ke-32 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_PENA', 'B_ARTV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-33 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_PENA', 'B_ARTV', 'B_TIMV', 'B_JUG', 'B_REGI', 'B_PROS', 'B_JUDP']
Dokumen Ke-34 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-35 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG']
Dokumen Ke-36 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-37 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_CRIA', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_PROS']
Dokumen Ke-38 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_PROS']
Dokumen Ke-39 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-40 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-41 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_PENA', 'B_ARTV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-42 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG']
Dokumen Ke-43 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-44 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_TIMV', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-45 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-46 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-47 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_PENA', 'B_CRIA', 'B_ARTV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-48 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-49 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-50 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-51 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-52 => Data Terlebel : 5 ; Total Label : 11 ; Label : ['B_CRIA', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG']
Dokumen Ke-53 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-54 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG']
Dokumen Ke-55 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-56 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_PENA', 'B_CRIA', 'B_ARTV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-57 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_CRIA', 'B_PENA', 'B_PUNI', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-58 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-59 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-60 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-61 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-62 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG']
Dokumen Ke-63 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_PENA', 'B_ARTV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-64 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_PENA', 'B_JUG', 'B_REGI']
Dokumen Ke-65 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_VERN', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-66 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_PENA', 'B_ARTV', 'B_TIMV', 'B_JUDP', 'B_REGI', 'B_JUG']
Dokumen Ke-67 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_REGI', 'B_JUG']
Dokumen Ke-68 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_TIMV', 'B_VERN', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-69 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_ARTV', 'B_TIMV', 'B_JUG', 'B_REGI', 'B_PROS', 'B_JUDP']
Dokumen Ke-70 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-71 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-72 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-73 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-74 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUG', 'B_REGI', 'B_JUDP']
Dokumen Ke-75 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-76 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_PUNI', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-77 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_ARTV', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-78 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_ARTV', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-79 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-80 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PUNI', 'B_TIMV', 'B_JUG', 'B_REGI', 'B_JUDP']
Dokumen Ke-81 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUG', 'B_REGI', 'B_JUDP']
Dokumen Ke-82 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-83 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-84 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_PENA', 'B_ARTV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-85 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-86 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-87 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_ARTV', 'B_DEFN', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-88 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-89 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUG', 'B_REGI', 'B_PROS', 'B_JUDP']
Dokumen Ke-90 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_TIMV', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_PROS']
Dokumen Ke-91 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_PENA', 'B_ARTV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-92 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-93 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_PENA', 'B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-94 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-95 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-96 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_TIMV', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-97 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_CRIA', 'B_PUNI', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-98 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-99 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-100 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_PUNI', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-101 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-102 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_ARTV', 'B_TIMV', 'B_REGI', 'B_JUG', 'B_JUDP']
Dokumen Ke-103 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-104 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_TIMV', 'B_CRIA', 'B_PUNI', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-105 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_DEFN', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-106 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_VERN', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-107 => Data Terlebel : 5 ; Total Label : 11 ; Label : ['B_CRIA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-108 => Data Terlebel : 10 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_PUNI', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-109 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-110 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_CRIA', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Dokumen Ke-111 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG']
Dokumen Ke-112 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_ARTV', 'B_PENA', 'B_DEFN', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-113 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-114 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_CRIA', 'B_PENA', 'B_TIMV', 'B_REGI']
Dokumen Ke-115 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_VERN', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-116 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-117 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-118 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-119 => Data Terlebel : 6 ; Total Label : 11 ; Label : ['B_DEFN', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI']
Dokumen Ke-120 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-121 => Data Terlebel : 7 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG']
Dokumen Ke-122 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_ARTV', 'B_PENA', 'B_TIMV', 'B_JUDP', 'B_JUG', 'B_REGI', 'B_PROS']
Dokumen Ke-123 => Data Terlebel : 1 ; Total Label : 11 ; Label : ['B_CRIA']
Dokumen Ke-124 => Data Terlebel : 9 ; Total Label : 11 ; Label : ['B_VERN', 'B_DEFN', 'B_PENA', 'B_CRIA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI', 'B_PROS']
Dokumen Ke-125 => Data Terlebel : 8 ; Total Label : 11 ; Label : ['B_DEFN', 'B_VERN', 'B_ARTV', 'B_PENA', 'B_JUDP', 'B_JUG', 'B_TIMV', 'B_REGI']
Accuracy : {label_in/sum_label * 100}

'Accuracy : 71.11597374179432'

## Save Dataset

In [ ]:
import json
new_df.to_json('datasetAnotasiSMNP.json', orient='records')