In [1]:
import pandas as pd

In [2]:
df_all_json = pd.read_json('/content/drive/MyDrive/NER nlp/Dataset/all.json', lines=True)
df_all_json

,verdict,indictment,lawyer,id,owner,text-tags,text
0,guilty,subsider,False,2743,agree,"[O, O, B-Nomor Putusan, I-Nomor Putusan, O, O,...","[﻿putusan, nomor, 325/pid.b/2015/pn, bwi, demi..."
1,guilty,alternatif,False,2744,agree,"[O, O, B-Nomor Putusan, I-Nomor Putusan, O, O,...","[﻿putusan, nomor, 285/pid.b/2016/pn, sda, demi..."
2,guilty,tunggal,False,2745,agree,"[O, O, B-Nomor Putusan, O, O, O, O, O, O, O, B...","[﻿putusan, nomor:, 80/pid.b/2014/pn.spg, demi,..."
3,guilty,NA,False,2746,agree,"[O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O...","[﻿putusan, nomor, :, 325/pid.sus/2012/pn.ta., ..."
4,guilty,tunggal,False,2747,agree,"[O, O, B-Nomor Putusan, I-Nomor Putusan, O, O,...","[﻿putusan, nomor, 92/pid.b/2015/pn, slw., demi..."
...,...,...,...,...,...,...,...
988,guilty,tunggal,False,2738,jafar,"[O, O, O, B-Nomor Putusan, I-Nomor Putusan, I-...","[﻿1, putusan, no., 21/pid., b/2012/pn., tmg, “..."
989,guilty,tunggal,False,2739,jafar,"[O, O, O, O, O, O, O, O, O, B-Nomor Putusan, O...","[﻿dir1ektori, putusan, mahkamah, agung, republ..."
990,guilty,NA,False,2740,jafar,"[O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O...","[﻿putusan, nomor, :, 376/pid.b/2012/pn.kdi, de..."
991,guilty,alternatif,False,2741,jafar,"[O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O...","[﻿putusan, nomor, :, 79/pid.sus/2015/pn.blb, d..."
992,guilty,tunggal,False,2742,jafar,"[O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O...","[﻿putusan, nomor, :, 121/pid.b/2010/pn.smp, de..."

In [46]:
df_all_json.shape

(993, 7)

In [47]:
df_all_json.isnull().sum()

verdict       0
indictment    0
lawyer        0
id            0
owner         0
text-tags     0
text          0
dtype: int64

In [48]:
df_all_json['indictment'].unique()

array(['subsider', 'alternatif', 'tunggal', 'NA', 'komul',
       'NF - dakwaanaternatif,|', 'kombinasi',
       'NF - dakwaandalambentukaternatife|', 'NF - dakwaantnggal|',
       'NF - dakwaanyangdisusunsecaraaltematif,|',
       'NF - dakwaanaltematif|', 'NF - dakwaanakternatif,|', 'gabungan',
       'NF - dakwaanprimair|', 'NF - dakwaanaternatif|',
       'NF - dakwaankomolatif,|', 'NF - didakwasecarasusidairitas,|',
       'NF - dakwaanberbentuksubidairitas,|',
       'NF - dakwaanberbentuksudsidairitas|'], dtype=object)

In [49]:
df_all_json['verdict'].unique()

array(['guilty', 'bebas', 'lepas'], dtype=object)

In [50]:
df_all_json['owner'].unique()

array(['agree', 'dhipa', 'fariz', 'jafar'], dtype=object)

In [51]:
# Split labels based on whitespace and turn them into a list
labels = [i for i in df_all_json['text-tags']]

# Check how many labels are there in the dataset
unique_labels = set()

for lb in labels:
  [unique_labels.add(i) for i in lb if i not in unique_labels]

print(unique_labels)

{'B-Melanggar UU (Pertimbangan Hukum)', 'I-Jenis Dakwaan', 'B-Melanggar UU (Tuntutan)', 'O', 'B-Jenis Amar', 'I-Tanggal Putusan', 'I-Nama Hakim Ketua', 'I-Nama Panitera', 'B-Jenis Perkara', 'B-Tanggal Kejadian', 'I-Jenis Perkara', 'I-Nama Hakim Anggota', 'I-Tanggal Kejadian', 'B-Nama Terdakwa', 'B-Nama Jaksa', 'B-Nomor Putusan', 'I-Tingkat Kasus', 'B-Nama Panitera', 'B-Tanggal Putusan', 'I-Melanggar UU (Tuntutan)', 'B-Nama Hakim Anggota', 'I-Nama Terdakwa', 'B-Melanggar UU (Dakwaan)', 'I-Tuntutan Hukuman', 'B-Nama Hakim Ketua', 'I-Putusan Hukuman', 'I-Nama Pengadilan', 'I-Nama Jaksa', 'B-Tingkat Kasus', 'B-Putusan Hukuman', 'I-Jenis Amar', 'I-Melanggar UU (Dakwaan)', 'B-Nama Saksi', 'B-Jenis Dakwaan', 'B-Nama Pengadilan', 'I-Nama Saksi', 'I-Nomor Putusan', 'B-Nama Pengacara', 'I-Melanggar UU (Pertimbangan Hukum)', 'I-Nama Pengacara', 'B-Tuntutan Hukuman'}

In [52]:
print(df_all_json['text'][0])

['\ufeffputusan', 'nomor', '325/pid.b/2015/pn', 'bwi', 'demi', 'keadilan', 'berdasarkan', 'ketuhanan', 'yang', 'maha', 'esa', 'pengadilan', 'negeri', 'banyuwangi', 'yang', 'mengadili', 'dan', 'memutus', 'perkara', 'pidana', 'dengan', 'acara', 'pemeriksaan', 'biasa', 'dalam', 'tingkat', 'pertama', 'menjatuhkan', 'putusan', 'sebagai', 'berikut', 'dalam', 'perkara', 'terdakwa:', 'nama', 'lengkap', ':', 'suyanto', 'al.', 'yanto;', 'tempat', 'lahir', ':', 'banyuwangi;', 'umur', '/', 'tanggal', 'lahir', ':', '35', 'tahun/2', 'maret', '1979;', 'jenis', 'kelamin', ':', 'laki-laki;', 'kebangsaan', ':', 'indonesia;', 'agama', ':', 'islam;', 'tempat', 'tinggal', ':', 'dusun', 'krajan', 'rt.', '08', 'rw.', 'iii,', 'desa', 'tembokrejo,', 'kecamatan', 'muncar,', 'kabupaten', 'banyuwangi;', 'pekerjaan', ':', 'karyawan', 'pt.', 'fi', 'perkasa', 'banyuwangi;', 'pendidikan', ':', 'd.1;', 'terdakwa', 'ditangkap', 'pada', 'tanggal', '17', 'maret', '2015;', 'terdakwa', 'ditahan', 'dalam', 'rumah', 'tahanan', 'negara', 'berdasarkan', 'surat', 'perintah/', 'penetapan', 'penahanan', 'dari/oleh:', '1.', 'penyidik', 'tanggal', '18', 'maret', '2015,', 'nomor', 'sp-han/14/iii/2015/reskrim,', 'sejak', 'tanggal', '18', 'maret', '2015', 'sampai', 'dengan', 'tanggal', '6', 'april', '2015;', '2.', 'perpanjangan', 'oleh', 'penuntut', 'umum', 'tanggal', '1', 'april', '2015,', 'nomor', 'prin-', '216/epp.1/rt.2/04/2015,', 'sejak', 'tanggal', '7', 'april', '2015', 'sampai', 'dengan', 'tanggal', '16', 'mei', '2015;', '3.', 'penuntut', 'umum', 'tanggal', '13', 'mei', '2015,', 'nomor', 'prin-118/', 'rt.3/ep.1/05/2015,', 'sejak', 'tanggal', '13', 'mei', '2015', 'sampai', 'dengan', 'tanggal', '1', 'juni', '2015;', '4.', 'majelis', 'hakim', 'pengadilan', 'negeri', 'tanggal', '27', 'mei', '2015,', 'nomor', '325/pid.b/2015/pn', 'bwi,', 'sejak', 'tanggal', '27', 'mei', '2015', 'sampai', 'dengan', 'tanggal', '25', 'juni', '2015;', '5.', 'perpanjangan', 'ketua', 'pengadilan', 'negeri', 'banyuwangi', 'tanggal', '23', 'juni', '2015,', 'nomor', '325/pid.b/2015/pn', 'bwi,', 'sejak', 'tanggal', '26', 'juni', '2015', 'sampai', 'dengan', 'tanggal', '24', 'agustus', '2015;', 'terdakwa', 'tidak', 'didampingi', 'penasehat', 'hukum;', 'pengadilan', 'negeri', 'tersebut;', 'setelah', 'membaca:', '-', 'penetapan', 'ketua', 'pengadilan', 'negeri', 'banyuwangi', 'nomor', '325/pid.b/2015/pn', 'bwi', 'tanggal', '27', 'mei', '2015', 'tentang', 'penunjukan', 'majelis', 'hakim;', '-', 'penetapan', 'majelis', 'hakim', 'nomor', '325/pid.b/2015/pn', 'bwi', 'tanggal', '27', 'mei', '2015', 'tentang', 'penetapan', 'hari', 'sidang;', '-', 'berkas', 'perkara', 'dan', 'surat-surat', 'lain', 'yang', 'bersangkutan;', 'setelah', 'mendengar', 'keterangan', 'saksi-saksi', 'dan', 'terdakwa', 'serta', 'memperhatikan', 'bukti', 'surat', 'dan', 'barang', 'bukti', 'yang', 'diajukan', 'di', 'persidangan;', 'setelah', 'mendengar', 'tuntutan', 'pidana', 'jaksa/penuntut', 'umum', 'yang', 'dibacakan', 'dipersidangan', 'pada', 'hari', 'rabu,', 'tanggal', '8', 'juli', '2015,', 'nomor', 'pdm-113/0.5.21/ep.1/05/2015,', 'yang', 'pada', 'pokoknya', 'sebagai', 'berikut:', '1.', 'menyatakan', 'terdakwa', 'suyanto', 'als', 'yanto', 'bersalah', 'melakukan', 'tindak', 'pidana', '“penggelapan', 'dengan', 'pemberatan”', 'sebagaimana', 'diatur', 'dan', 'diancam', 'pidana', 'dalam', 'pasal', '374', 'kuhpidana', 'dalam', 'surat', 'dakwaan', 'primair;', '2.', 'menjatuhkan', 'pidana', 'terhadap', 'terdakwa', 'suyanto', 'als', 'yanto', 'dengan', 'pidana', 'penjara', 'selama', '1(satu)', 'tahun', '4(empat)', 'dipotong', 'selama', 'terdakwa', 'ditahan,', 'dengan', 'dengan', 'perintah', 'terdakwa', 'tetap', 'ditahan;', '3.', 'menyatakan', 'agar', 'barang', 'bukti', 'berupa:', '1', '(satu)', 'unit', 'mobil', 'toyota', 'hilux', 'pick', 'up', '2', '5', 'l', 'dsl', 'mt,', 'warna', 'putih', 'tahun', '2013', 'nopol.', 'p-9087-vo,', '21', '(dua', 'puluh', 'satu)', 'batang', 'pipa', 'besi', 'stainless', 'dengan', 'panjang', '6', '(enam)', 'm', 'masing-masing', 'diameter', '1', '(satu)', 'inchi', 'sebanyak', '12', '(dua', 'belas)', 'batang', 'dan', '1', '25', '(satu', 'koma', 'dua', 'lima)', 'inchi', 'sebanyak', '9', '(sembilan)', 'batang', 'dikembalikan', 'kepada', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'melalui', 'saksi', 'suyadi', '(pemilik', 'dan', 'direktur', 'pt.', 'fl', 'perkasa', 'banyuwangi);', '4.', 'menetapkan', 'agar', 'terdakwa,', 'jika', 'ternyata', 'dipersalahkan', 'dan', 'dijatuhi', 'pidana', 'supaya', 'terdakwa', 'dibebani', 'membayar', 'biaya', 'perkara', 'sebesar', 'rp', '1000', '(seribu', 'rupiah);', 'setelah', 'mendengar', 'permohonan', 'terdakwa', 'secara', 'lisan', 'yang', 'pada', 'pokoknya', 'mohon', 'keringanan', 'hukuman', 'karena', 'terdakwa', 'merasa', 'bersalah', 'dan', 'menyesal', 'serta', 'berjanji', 'tidak', 'akan', 'mengulangi', 'perbuatannya', 'lagi;', 'menimbang,', 'bahwa', 'terdakwa', 'diajukan', 'ke', 'persidangan', 'oleh', 'jaksa/', 'penuntut', 'umum', 'didakwa', 'berdasarkan', 'surat', 'dakwaannya', 'nomor', 'pdm-113/0.5.21/ep.1/05/2015', 'tanggal', '25', 'mei', '2015,', 'yang', 'isinya', 'sebagai', 'berikut:', 'pertama:', 'primair:', 'bahwa', 'ia', 'terdakwa', 'suyanto', 'als', 'yanto', 'selaku', 'supervisor', 'finishing', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'yang', 'bertugas', 'mengawasi', 'pengecatan,', 'interior', 'dan', 'pembuatan', 'pagar', 'kapal', 'serta', 'mendapat', 'gaji', 'dari', 'fl', 'perkasa', 'banyuwangi,', 'pada', 'hari', 'sabtu', 'tanggal', '14', 'maret', '2015', 'sekira', 'jam', '13.00', 'wib,', 'atau', 'setidak-tidaknya', 'pada', 'suatu', 'waktu', 'dalam', 'bulan', 'maret', 'tahun', '2015,', 'bertempat', 'di', 'dalam', 'gudang', 'bengkel', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'masuk', 'desa', 'blimbingsari', 'kecamatan', 'rogojampi', 'kabupaten', 'banyuwangi,', 'atau', 'setidak-tidaknya', 'pada', 'suatu', 'tempat', 'yang', 'masih', 'termasuk', 'dalam', 'daerah', 'hukum', 'pengadilan', 'negeri', 'banyuwangi,', 'dengan', 'sengaja', 'memiliki', 'dengan', 'melawan', 'hak', 'sesuatu', 'barang', 'yang', 'sama', 'sekali', 'atau', 'sebagiannya', 'termasuk', 'kepunyaan', 'orang', 'lain', 'dan', 'barang', 'itu', 'ada', 'dalam', 'tangannya', 'bukan', 'karena', 'kejahatan,', 'yang', 'dilakukan', 'oleh', 'orang', 'yang', 'memegang', 'barang', 'itu', 'berhubung', 'dengan', 'pekerjaannya', 'atau', 'jabatannya', 'atau', 'karena', 'ia', 'mendapat', 'upah,', 'dengan', 'cara', 'sebagai', 'berikut', ':', 'terdakwa', 'selaku', 'supervisor', 'finishing', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'yang', 'berwenang', 'untuk', 'mengeluarkan', 'barang', 'yang', 'dibutuhkan', 'oleh', 'bagian', 'produksi', 'telah', 'membawa', 'mobil', 'toyota', 'hilux', 'nopol.', 'p-9087-vo', 'milik', 'perusahaan', 'lalu', 'tanpa', 'ijin', 'dari', 'pihak', 'perusahaan', 'terdakwa', 'mengambil', '22', '(dua', 'puluh', 'dua)', 'batang', 'pipa', 'besi', 'stainless', 'yang', 'ada', 'di', 'rak', 'gudang,', 'selanjutnya', 'pipa', 'besi', 'stainless', 'tersebut', 'dinaikkan', 'ke', 'atas', 'mobil', 'toyota', 'hilux', 'dan', 'dibawa', 'keluar', 'dari', 'areal', 'perusahaan', 'pt.', 'fl', 'perkasa', 'banyuwangi,', 'selanjutnya', 'pipa', 'besi', 'stainless', 'yang', 'diambil', 'diletakkan', 'di', 'dekat', 'pondok', 'pesantren', 'manbaul', 'ulum', 'sumberberas', 'muncar', 'banyuwangi,', 'akibat', 'dari', 'perbuatan', 'terdakwa', 'tersebut', 'maka', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'mengalami', 'kerugian', 'sebesar', 'rp', '6300000', '(eiam', 'juta', 'tiga', 'ratus', 'ribu', 'rupiah),', 'atau', 'setidaktidaknya', 'sekitar', 'jumlah', 'tersebut;', 'perbuatan', 'terdakwa', 'sebagaimana', 'diatur', 'dan', 'diancam', 'pidana', 'dalam', 'pasal', '374', 'kuhpidana;', 'subsidair:', 'bahwa', 'ia', 'terdakwa', 'suyanto', 'als', 'yanto,', 'pada', 'waktu', 'dan', 'tempat', 'sebagaimana', 'diuraikan', 'dalam', 'dakwaan', 'primair', 'tersebut', 'diatas,', 'dengan', 'sengaja', 'memiliki', 'dengan', 'melawan', 'hak', 'sesuatu', 'barang', 'yang', 'sama', 'sekali', 'atau', 'sebagiannya', 'termasuk', 'kepunyaan', 'orang', 'lain', 'dan', 'barang', 'itu', 'ada', 'dalam', 'tangannya', 'bukan', 'karena', 'kejahatan,', 'yang', 'dilakukan', 'dengan', 'cara', 'sebagai', 'berikut', ':', 'terdakwa', 'seorang', 'karyawan', 'pt.', 'fl.', 'perkasa', 'banyuwangi', 'telah', 'membawa', 'mobil', 'toyota', 'hilux', 'nopol.', 'p-9087-vo', 'milik', 'perusahaan', 'lalu', 'tanpa', 'ijin', 'dari', 'pihak', 'perusahaan', 'terdakwa', 'mengambil', '22', '(dua', 'puluh', 'dua)', 'batang', 'pipa', 'besi', 'stainless', 'yang', 'ada', 'di', 'rak', 'gudang,', 'selanjutnya', 'pipa', 'besi', 'stainless', 'tersebut', 'dinaikkan', 'ke', 'atas', 'mobil', 'toyota', 'hilux', 'dan', 'dibawa', 'keluar', 'dari', 'areal', 'perusahaan', 'pt.', 'fl', 'perkasa', 'banyuwangi,', 'selanjutnya', 'pipa', 'besi', 'stainless', 'yang', 'diambil', 'diletakkan', 'di', 'dekat', 'pondok', 'pesantren', 'manbaul', 'ulum', 'sumberberas', 'muncar', 'banyuwangi,', 'akibat', 'dari', 'perbuatan', 'terdakwa', 'tersebut', 'maka', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'mengalami', 'kerugian', 'sebesar', 'rp', '6300000', '(enam', 'juta', 'tiga', 'ratas', 'ribu', 'rupiah),', 'atau', 'setidak-tidaknya', 'sekitar', 'jumlah', 'tersebut;', 'perbuatan', 'terdakwa', 'sebagaimana', 'diatur', 'dan', 'diancam', 'pidana', 'dalam', 'pasal', '372', 'kuhpidana;', 'atau:', 'kedua:', 'bahwa', 'ia', 'terdakwa', 'suyanto', 'als', 'yanto,', 'pada', 'waktu', 'dan', 'tempat', 'sebagaimana', 'diuraikan', 'dalam', 'dakwaan', 'pertama', 'primair', 'tersebut', 'diatas,', 'telah', 'mengambil', 'sesuatu', 'barang,', 'yang', 'sama', 'sekali', 'atau', 'sebagian', 'kepunyaan', 'orang', 'lain,', 'dengan', 'maksud', 'akan', 'memiliki', 'barang', 'itu', 'dengan', 'melawan', 'hak', 'yang', 'dilakukan', 'dengan', 'cara', ':', 'terdakwa', 'telah', 'membawa', 'mobil', 'toyota', 'hilux', 'nopol.', 'p-9087-vo', 'milik', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'lalu', 'tanpa', 'ijin', 'yang', 'berhak', 'terdakwa', 'mengambil', '22', '(dua', 'puluh', 'dua)', 'batang', 'pipa', 'besi', 'stainless', 'yang', 'ada', 'di', 'rak', 'gudang,', 'selanjutnya', 'pipa', 'besi', 'stainless', 'tersebut', 'dinaikkan', 'ke', 'atas', 'mobil', 'toyota', 'hilux', 'dan', 'dibawa', 'keluar', 'dari', 'areal', 'perusahaan', 'pt.', 'fl', 'perkasa', 'banyuwangi,', 'selanjutnya', 'pipa', 'besi', 'stainless', 'yang', 'diambil', 'diletakkan', 'di', 'dekat', 'pondok', 'pesantren', 'manbaul', 'ulum', 'sumberberas', 'muncar', 'banyuwangi,', 'akibat', 'dari', 'perbuatan', 'terdakwa', 'tersebut', 'maka', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'mengalami', 'kerugian', 'sebesar', 'rp', '6300000', '(enam', 'juta', 'tiga', 'ratus', 'ribu', 'rupiah),', 'atau', 'setidak-tidaknya', 'sekitar', 'jumlah', 'tersebut,', 'adapun', 'maksud', 'dan', 'tujuan', 'terdakwa', 'mengambil', 'pipa', 'besi', 'stainless', 'tersebut', 'adalah', 'untuk', 'disumbangkan', 'ke', 'pondok', 'pesantren', 'manbaul', 'ulum', 'sumberberas', 'muncar', '-', 'banyuwangi;', 'perbuatan', 'terdakwa', 'tersebut', 'sebagaimana', 'diatur', 'dan', 'diancam', 'pidana', 'dalam', 'pasal', '362', 'kuhpidana;', 'menimbang,', 'bahwa', 'terhadap', 'dakwaan', 'penuntut', 'umum,', 'terdakwa', 'tidak', 'mengajukan', 'keberatan/eksepsi;', 'menimbang,', 'bahwa', 'untuk', 'membuktikan', 'dakwaannya', 'penuntut', 'umum', 'telah', 'mengajukan', 'saksi-saksi', 'sebagai', 'berikut:', '1.', 'slamet', 'sugianto,', 'dibawah', 'sumpah', 'dipersidangan', 'pada', 'pokoknya', 'menerangkan', 'sebagai', 'berikut:', '-', 'bahwa', 'saksi', 'kenal', 'dengan', 'terdakwa', 'sebagai', 'teman', 'kerja', 'tetapi', 'tidak', 'ada', 'hubungan', 'keluarga;', '-', 'bahwa', 'saksi', 'membenarkan', 'keterangan', 'dan', 'tanda', 'tangannya', 'dalam', 'bap', 'penyidik;', '-', 'bahwa', 'benar', 'saksi', 'diperiksa', 'sehubungan', 'dengan', 'permasalahan', 'pipa', 'stainless', 'milik', 'pt.', 'fl', 'perkasa', 'banyuwangi,', 'pelakunya', 'adalah', 'terdakwa;', '-', 'bahwa', 'benar', 'saksi', 'adalah', 'anggota', 'satpam', 'pt.', 'fi', 'perkasa', 'banyuwangi,', 'sedangkan', 'terdakwa', 'adalah', 'karyawan', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'pada', 'bagian', 'kepala', 'produksi', 'yakni', 'mengawasi', 'pembuatan', 'kapal', 'fiber', 'glass;', '-', 'bahwa', 'benar', 'terdakwa', 'di', 'gaji', 'oleh', 'perusahaan,', 'tetapi', 'berapa', 'besarnya', 'saksi', 'tidak', 'tahu;', '-', 'bahwa', 'benar', 'waktu', 'saksi', 'piket', 'jaga', 'di', 'pos', 'iii,', 'saksi', 'melihat', 'terdakwa', 'mengendarai', 'mobil', 'pick', 'up', 'toyota', 'hilux', 'warna', 'putih', 'nopol.', 'p-9087-vo', 'dengan', 'membawa', 'pipa', 'besi', 'stainless', 'sebanyak', '½', '(setengah)', 'bendel,', 'tapi', 'berapa', 'banyaknya', 'saksi', 'tidak', 'tahu;', '-', 'bahwa', 'benar', 'waktu', 'ditanya', '“mau', 'dibawa', 'kemana?”,', 'dijawab', 'oleh', 'terdakwa', '“mau', 'di', 'tukar”;', '-', 'bahwa', 'benar', 'waktu', 'ditanya', 'surat', 'jalannya,', 'terdakwa', 'kelihatannya', 'buru-', 'buru', 'dan', 'langsung', 'pergi;', '-', 'bahwa', 'benar', 'kejadiannya', 'pada', 'han', 'sabtu', 'tanggal', '14', 'maret', '2015', 'sekira', 'jam', '13.00', 'wib,', 'di', 'pos', 'iii', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'masuk', 'ds', 'blimbingsari', 'kec', 'rogojampi', 'kab', 'banyuwangi;', '-', 'bahwa', 'benar', 'kemudian', 'saksi', 'mengontak', 'pos', 'i', 'yang', 'dijaga', 'oleh', 'sdr', 'ontoseno', 'untuk', 'ditanyakan', 'surat', 'jalannya;', '-', 'bahwa', 'benar', 'setelah', 'terdakwa', 'melewati', 'pos', 'i,', 'saksi', 'baru', 'tahu', 'dari', 'sdr', 'supron', 'selaku', 'koordinator', 'satpam', 'bahwa', 'terdakwa', 'tidak', 'ada', 'ijin', 'dari', 'perusahaan', 'untuk', 'membawa', 'keluar', 'pipa', 'besi', 'stainless', 'tersebut;', '-', 'bahwa', 'benar', 'hari', 'seninnya', 'terdakwa', 'kembali', 'ke', 'perusahaan', 'dengan', 'mengendarai', 'mobil', 'pick', 'up', 'toyota', 'flilux', 'warna', 'putih', 'nopol.', 'p-9087-vo', 'tetapi', 'tanpa', 'pipa', 'stainless;', '-', 'bahwa', 'benar', 'pipa', 'stainless', 'sudah', 'di', 'temukan,', 'tetapi', 'ditemukan', 'dimana', 'saksi', 'tidak', 'tahu;', '-', 'bahwa', 'benar', 'saksi', 'tidak', 'tahu', 'berapa', 'kerugian', 'perusahaan', 'pt.', 'fi', 'perkasa', 'banyuwangi;', '-', 'bahwa', 'benar', 'barang', 'bukti', 'yang', 'diajukan', 'dipersidangan;', 'terdakwa', 'membenarkan', 'keterangan', 'saksi', 'tersebut;', '2.', 'supron,', 'dibawah', 'sumpah', 'dipersidangan', 'pada', 'pokoknya', 'menerangkan', 'sebagai', 'berikut:', '-', 'bahwa', 'saksi', 'kenal', 'dengan', 'terdakwa', 'tetapi', 'tidak', 'ada', 'hubungan', 'keluarga;', '-', 'bahwa', 'saksi', 'membenarkan', 'keterangan', 'dan', 'tanda', 'tangannya', 'dalam', 'bap', 'penyidik;', '-', 'bahwa', 'benar', 'saksi', 'diperiksa', 'sehubungan', 'dengan', 'permasalahan', 'pipa', 'stainless', 'milik', 'pt.', 'fl', 'perkasa', 'banyuwangi,', 'pelakunya', 'adalah', 'terdakwa;', '-', 'bahwa', 'benar', 'saksi', 'selaku', 'koordinator', 'satpam', 'pt.', 'fl', 'perkasa', 'banyuwangi,', 'sedangkan', 'terdakwa', 'adalah', 'karyawan', 'pt.', 'fi', 'perkasa', 'banyuwangi', 'sebagai', 'supervisor', 'finishing', '(pengawas)', 'yang', 'bertugas', 'mengawasi', 'pengecatan', 'interior', 'dan', 'pembuatan', 'pagar', 'kapal', 'di', 'pt.', 'fi', 'perkasa', 'banyuwangi;', '-', 'bahwa', 'benar', 'terdakwa', 'di', 'gaji', 'oleh', 'perusahaan,', 'tetapi', 'berapa', 'besarnya', 'saksi', 'tidak', 'tahu;', '-', 'bahwa', 'benar', 'waktu', 'saksi', 'jaga', 'di', 'pos', 'i', 'di', 'kontak', 'oleh', 'saksi', 'slamet', 'sugianto', 'bahwa', 'terdakwa', 'telah', 'membawa', 'mobil', 'hilux', 'dan', 'pipa', 'besi', 'stainles', 'milik', 'perusahaan', 'dengan', 'terburu-buru;', '-', 'bahwa', 'benar', 'tidak', 'lama', 'kemudian', 'kelihatan', 'terdakwa', 'mengendarai', 'mobil', 'hilux,', 'waktu', 'dihentikan', 'terdakwa', 'berhenti', 'agak', 'jauh', 'dari', 'pos', 'i,', 'kemudian', 'saksi', 'mendekati', 'mobil', 'hilux', 'dan', 'melihat', 'ada', 'pipa', 'besi', 'stainless', 'kira-kira', 'sejumlah', '20', '(dua', 'puluh)', 'batang', 'lebih;', '-', 'bahwa', 'benar', 'ketika', 'mau', 'ditanyakan', 'surat', 'jalannya', 'terdakwa', 'langsung', 'tancap', 'gas', 'meninggalkan', 'saksi;', '-', 'bahwa', 'benar', 'kejadiannya', 'pada', 'hari', 'sabtu', 'tanggal', '14', 'maret', '2015', 'sekira', 'pukul', '13.00', 'wib,', 'di', 'pos', 'i', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'masuk', 'desa', 'blimbingsari,', 'kecamatan', 'rogojampi,', 'kabupaten', 'banyuwangi;', '-', 'bahwa', 'benar', 'kejadian', 'tersebut', 'dilaporkan', 'kepada', 'saksi', 'suyadi', 'selaku', 'direktur', 'pt.', 'fl', 'perkasa', 'banyuwangi;', '-', 'bahwa', 'benar', 'terdakwa', 'tidak', 'ada', 'ijin', 'dari', 'perusahaan', 'untuk', 'membawa', 'keluar', 'pipa', 'besi', 'stainless', 'tersebut;', '-', 'bahwa', 'benar', 'terdakwa', 'kembali', 'pada', 'hari', 'seninnya', 'dengan', 'mengendarai', 'mobil', 'hilux,', 'tetapi', 'pipa', 'besi', 'stainless', 'sudah', 'tidak', 'ada;', '-', 'bahwa', 'benar', 'barang', 'bukti', 'yang', 'diajukan', 'dipersidangan;', 'terdakwa', 'membenarkan', 'keterangan', 'saksi', 'tersebut;', '3.', 'suyadi,', 'dibawah', 'sumpah', 'dipersidangan', 'pada', 'pokoknya', 'menerangkan', 'sebagai', 'berikut:', '-', 'bahwa', 'saksi', 'kenal', 'dengan', 'terdakwa', 'tetapi', 'tidak', 'ada', 'hubungan', 'keluarga;', '-', 'bahwa', 'saksi', 'membenarkan', 'keterangan', 'dan', 'tanda', 'tangannya', 'dalam', 'bap', 'penyidik;', '-', 'bahwa', 'benar', 'saksi', 'diperiksa', 'sehubungan', 'dengan', 'permasalahan', 'pipa', 'stainless', 'milik', 'pt.', 'fl', 'perkasa', 'banyuwangi,', 'pelakunya', 'adalah', 'terdakwa;', '-', 'bahwa', 'benar', 'saksi', 'selaku', 'pemilik', 'sekaligus', 'direktur', 'utama', 'pt.', 'fi', 'perkasa', 'banyuwangi,', 'sedangkan', 'terdakwa', 'adalah', 'karyawan', 'pt.', 'fi', 'perkasa', 'banyuwangi', 'sebagai', 'supervisor', 'finishing', '(pengawas)', 'yang', 'bertugas', 'mengawasi', 'pengecatan', 'interior', 'dan', 'pembuatan', 'pagar', 'kapal', 'di', 'pt.', 'fi', 'perkasa', 'banyuwangi;', '-', 'bahwa', 'benar', 'terdakwa', 'di', 'gaji', 'sebesar', 'rp', '2600000', '(dua', 'juta', 'enam', 'ratus', 'ribu', 'rupiah)', 'per-bulan;', '-', 'bahwa', 'benar', 'saksi', 'tidak', 'tahu', 'kejadiannya,', 'saksi', 'tahu', 'kejadian', 'setelah', 'diberitahu', 'oleh', 'saksi', 'supron', '(koordinator', 'satpam)', 'bahwa', 'terdakwa', 'telah', 'membawa', 'mobil', 'hilux', 'dan', 'pipa', 'besi', 'stainless', 'milik', 'perusahaan;', '-', 'bahwa', 'benar', 'pipa', 'besi', 'stainless', 'yang', 'dibawa', 'oleh', 'terdakwa', 'sejumlah', '22', '(dua', 'puluh', 'dua)', 'batang', 'dengan', 'panjang', '6', '(enam)', 'm', 'masing-masing', 'diameter', '1', '(satu)', 'inchi', 'sebanyak', '12', '(dua', 'belas)', 'batang', 'dan', '1', '25', '(satu', 'koma', 'dua', 'lima)', 'inchi', 'sebanyak', '10', '(sepuluh)', 'batang;', '-', 'bahwa', 'benar', 'kejadiannya', 'pada', 'hari', 'sabtu', 'tanggal', '14', 'maret', '2015', 'sekira', 'pukul', '13.00', 'wib,', 'di', 'pt.', 'fl', 'perkasa', 'banyuwangi', 'masuk', 'desa', 'blimbingsari,', 'kecamatan', 'rogojampi,', 'kabupaten', 'banyuwangi;', '-', 'bahwa', 'benar', '22', '(dua', 'puluh', 'dua)', 'batang', 'pipa', 'besi', 'stainless', 'ditaksir', 'seharga', 'rp6300000', '(enam', 'juta', 'tiga', 'ratus', 'ribu', 'rupiah);', '-', 'bahwa', 'benar', 'terdakwa', 'tidak', 'ada', 'ijin', 'dari', 'pihak', 'perusahaan', 'untuk', 'membawa', 'keluar', 'pipa', 'besi', 'stainless', 'tersebut;', '-', 'bahwa', 'benar', 'barang', 'bukti', 'yang', 'diajukan', 'dipersidangan;', 'terdakwa', 'membenarkan', 'keterangan', 'saksi', 'tersebut;', 'menimbang,', 'bahwa', 'terdakwa', 'di', 'persidangan', 'telah', 'memberikan', 'keterangan', 'yang', 'pada', 'pokoknya', 'sebagai', 'berikut:', '-', 'bahwa', 'terdakwa', 'membenarkan', 'dakwaan', 'jaksa/penuntut', 'umum;', '-', 'bahwa', 'keterangan', 'dan', 'tanda', 'tangan', 'terdakwa', 'yang', 'tertuang', 'dalam', 'berkas', 'perkara/bap', 'penyidik', 'benar;', '-', 'bahwa', 'benar', 'terdakwa', 'selaku', 'supervisor', 'finishing', 'pt.', 'fl', 'perkasa', '

In [53]:
print(df_all_json['text-tags'][0])

['O', 'O', 'B-Nomor Putusan', 'I-Nomor Putusan', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Nama Pengadilan', 'I-Nama Pengadilan', 'I-Nama Pengadilan', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Tingkat Kasus', 'I-Tingkat Kasus', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Nama Terdakwa', 'I-Nama Terdakwa', 'I-Nama Terdakwa', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Jenis Perkara', 'I-Jenis Perkara', 'I-Jenis Perkara', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Melanggar UU (Tuntutan)', 'I-Melanggar UU (Tuntutan)', 'I-Melanggar UU (Tuntutan)', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Tuntutan Hukuman', 'I-Tuntutan Hukuman', 'I-Tuntutan Hukuman', 'I-Tuntutan Hukuman', 'I-Tuntutan Hukuman', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Nama Saksi', 'I-Nama Saksi', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Nama Saksi', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Nama Saksi', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Tanggal Kejadian', 'I-Tanggal Kejadian', 'I-Tanggal Kejadian', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Jenis Dakwaan', 'I-Jenis Dakwaan', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Melanggar UU (Dakwaan)', 'I-Melanggar UU (Dakwaan)', 'O', 'B-Melanggar UU (Dakwaan)', 'I-Melanggar UU (Dakwaan)', 'O', 'O', 'B-Melanggar UU (Dakwaan)', 'I-Melanggar UU (Dakwaan)', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-Melanggar UU (Pertimbangan Hukum)',

In [16]:
new_df= pd.DataFrame([])

In [17]:
import re, string

# Text Cleaning
def cleaning(text):

    # Mengubah text yang berisi 'nan' dengan whitespace agar nantinya dapat dihapus
    text = re.sub(",,", ",", text)

    return text

In [18]:
new_df['text'] = df_all_json['text'].apply(lambda x: ', '.join(x))
new_df['labels'] = df_all_json['text-tags'].apply(lambda x: ', '.join(x))
# new_df['text'] = new_df['text'].apply(lambda x: cleaning(x))
# new_df['length_text'] = new_df['text'].apply(lambda x: len(x.split(',')))
# new_df['length_labels'] = new_df['labels'].apply(lambda x: len(x.split(',')))

In [19]:
new_df

,text,labels
0,"﻿putusan, nomor, 325/pid.b/2015/pn, bwi, demi,...","O, O, B-Nomor Putusan, I-Nomor Putusan, O, O, ..."
1,"﻿putusan, nomor, 285/pid.b/2016/pn, sda, demi,...","O, O, B-Nomor Putusan, I-Nomor Putusan, O, O, ..."
2,"﻿putusan, nomor:, 80/pid.b/2014/pn.spg, demi, ...","O, O, B-Nomor Putusan, O, O, O, O, O, O, O, B-..."
3,"﻿putusan, nomor, :, 325/pid.sus/2012/pn.ta., “...","O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O,..."
4,"﻿putusan, nomor, 92/pid.b/2015/pn, slw., demi,...","O, O, B-Nomor Putusan, I-Nomor Putusan, O, O, ..."
...,...,...
988,"﻿1, putusan, no., 21/pid., b/2012/pn., tmg, “,...","O, O, O, B-Nomor Putusan, I-Nomor Putusan, I-N..."
989,"﻿dir1ektori, putusan, mahkamah, agung, republi...","O, O, O, O, O, O, O, O, O, B-Nomor Putusan, O,..."
990,"﻿putusan, nomor, :, 376/pid.b/2012/pn.kdi, dem...","O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O,..."
991,"﻿putusan, nomor, :, 79/pid.sus/2015/pn.blb, de...","O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O,..."
992,"﻿putusan, nomor, :, 121/pid.b/2010/pn.smp, dem...","O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O,..."

In [20]:
df_exploded = new_df.apply(lambda col: col.explode()).reset_index(drop=True)

In [21]:
df_exploded

,text,labels
0,"﻿putusan, nomor, 325/pid.b/2015/pn, bwi, demi,...","O, O, B-Nomor Putusan, I-Nomor Putusan, O, O, ..."
1,"﻿putusan, nomor, 285/pid.b/2016/pn, sda, demi,...","O, O, B-Nomor Putusan, I-Nomor Putusan, O, O, ..."
2,"﻿putusan, nomor:, 80/pid.b/2014/pn.spg, demi, ...","O, O, B-Nomor Putusan, O, O, O, O, O, O, O, B-..."
3,"﻿putusan, nomor, :, 325/pid.sus/2012/pn.ta., “...","O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O,..."
4,"﻿putusan, nomor, 92/pid.b/2015/pn, slw., demi,...","O, O, B-Nomor Putusan, I-Nomor Putusan, O, O, ..."
...,...,...
988,"﻿1, putusan, no., 21/pid., b/2012/pn., tmg, “,...","O, O, O, B-Nomor Putusan, I-Nomor Putusan, I-N..."
989,"﻿dir1ektori, putusan, mahkamah, agung, republi...","O, O, O, O, O, O, O, O, O, B-Nomor Putusan, O,..."
990,"﻿putusan, nomor, :, 376/pid.b/2012/pn.kdi, dem...","O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O,..."
991,"﻿putusan, nomor, :, 79/pid.sus/2015/pn.blb, de...","O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O,..."
992,"﻿putusan, nomor, :, 121/pid.b/2010/pn.smp, dem...","O, O, O, B-Nomor Putusan, O, O, O, O, O, O, O,..."

In [40]:
new_df.to_csv('hmm.csv', index=False)

In [11]:
# Pecah setiap teks dan label menjadi list berdasarkan koma dan spasi
split_text = [text.split(', ') for text in new_df['text']]
split_text_tag = [tag.split(', ') for tag in new_df['labels']]

# Periksa panjang setiap baris, pastikan jumlah elemen sama untuk kedua kolom
max_length = max(len(text) for text in split_text)
for i in range(len(split_text)):
    while len(split_text[i]) < max_length:
        split_text[i].append('')
    while len(split_text_tag[i]) < max_length:
        split_text_tag[i].append('')

# Buat DataFrame baru dengan kata dan label dalam baris terpisah
new_data2 = {'text': [word for sublist in split_text for word in sublist],
            'text-tag': [tag for sublist in split_text_tag for tag in sublist]}
new_df2 = pd.DataFrame(new_data2)

# Menampilkan DataFrame baru dengan kata dan label dalam baris terpisah
new_df2

                        text         text-tag
0                   ﻿putusan                O
1                      nomor                O
2          325/pid.b/2015/pn  B-Nomor Putusan
3                        bwi  I-Nomor Putusan
4                       demi                O
...                      ...              ...
124704907
124704908
124704909
124704910
124704911

[124704912 rows x 2 columns]