# Pre Processing Dataset Baru

In [1]:
import pandas as pd
import nltk
import time
import re
import tqdm

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [3]:
print(f"BeautifulSoup version: {tqdm.__version__}")

BeautifulSoup version: 4.66.4

## Load Data

In [ ]:
# load_df = pd.read_json('/content/drive/MyDrive/NER nlp/Dataset/all.json', lines=True, nrows=203)
load_df = pd.read_json('/content/drive/MyDrive/NER nlp/Dataset/Dataset Fix/datasetAnotasi.json')
# load_df = pd.concat([load_df.iloc[0:199], load_df.iloc[202:203]])
# load_df = load_df.reset_index(drop=True)
load_df

,doc,text,label
0,48_Pid.B_2024_PN_Bkl.pdf,"[putusan, nomor, 48/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
1,42_Pid.B_2024_PN_Bkl.pdf,"[putusan, nomor, 42/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
2,49_Pid.B_2024_PN_Bkl.pdf,"[putusan, nomor, 49/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
3,56_Pid.B_2024_PN_Bkl.pdf,"[putusan, nomor, 56/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
4,57_Pid.B_2024_PN_Bkl.pdf,"[putusan, nomor, 57/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
...,...,...,...
495,33_Pid.B_2022_PN_Smp.pdf,"[putusan, nomor, 33/pid.b/2022/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
496,25_Pid.B_2022_PN_Smp.pdf,"[putusan, nomor, 25/pid.b/2022/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
497,5_Pid.B_2022_PN_Smp.pdf,"[nomor, 05/pid.b/2022, /pn, smp, demi, keadila...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
498,19_Pid.Sus_2022_PN_Smp.pdf,"[putusan, nomor, 19/pid.sus/2022/pn, smp, demi...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
499,298_Pid.B_2021_PN_Smp.pdf,"[putusan, nomor, 298/pid., b/2021/pn, smp, ., ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

### Ambil Kolom text dan text-tags

In [ ]:
df = load_df[["text", "label"]]
df

,text,label
0,"[putusan, nomor, 48/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
1,"[putusan, nomor, 42/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
2,"[putusan, nomor, 49/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
3,"[putusan, nomor, 56/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
4,"[putusan, nomor, 57/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
...,...,...
495,"[putusan, nomor, 33/pid.b/2022/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
496,"[putusan, nomor, 25/pid.b/2022/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
497,"[nomor, 05/pid.b/2022, /pn, smp, demi, keadila...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
498,"[putusan, nomor, 19/pid.sus/2022/pn, smp, demi...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
499,"[putusan, nomor, 298/pid., b/2021/pn, smp, ., ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

## Cleaning Dataset

In [ ]:
def cleaning_text(dataset):
  for i, row in tqdm.tqdm(dataset.iterrows(), total=len(dataset), desc="Cleaning text"):
    dataset.at[i, "text"] = [word.replace("\ufeff", "") for word in row["text"]]
    data_text, data_tag = zip(*[(token, label) for token, label in zip(row["text"], row["label"]) if token.strip() != ''])
    dataset.at[i, "text"] = list(data_text)
    dataset.at[i, "label"] = list(data_tag)

  return dataset

cleaning_text(df)

Cleaning text: 100%|██████████| 500/500 [00:10<00:00, 47.66it/s]

,text,label
0,"[putusan, nomor, 48/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
1,"[putusan, nomor, 42/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
2,"[putusan, nomor, 49/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
3,"[putusan, nomor, 56/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
4,"[putusan, nomor, 57/pid.b/2024/pn, bkl, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
...,...,...
495,"[putusan, nomor, 33/pid.b/2022/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
496,"[putusan, nomor, 25/pid.b/2022/pn, smp, demi, ...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
497,"[nomor, 05/pid.b/2022, /pn, smp, demi, keadila...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
498,"[putusan, nomor, 19/pid.sus/2022/pn, smp, demi...","[O, O, B_VERN, I_VERN, O, O, O, O, O, O, O, O,..."
499,"[putusan, nomor, 298/pid., b/2021/pn, smp, ., ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [ ]:
text_example = df['text'][199]
label_example = df['label'][199]
print(text_example)
print(label_example)

['putusan', 'nomor', '19/pid.b/2023/pn', 'spg', 'demi', 'keadilan', 'berdasarkan', 'ketuhanan', 'yang', 'maha', 'esa', 'pengadilan', 'negeri', 'sampang', 'yang', 'mengadili', 'perkara', 'pidana', 'dengan', 'acara', 'pemeriksaan', 'biasa', 'dalam', 'tingkat', 'pertama', 'menjatuhkan', 'putusan', 'sebagai', 'berikut', 'dalam', 'perkara', 'terdakwa', ':', '01.', 'nama', 'lengkap', ':', 'halimi', 'bin', 'busadin', ';', '02.', 'tempat', 'lahir', ':', 'pamekasan', ';', '03.', 'umur/tanggal', 'lahir', ':', '46', 'tahun', '/20', 'februari', '1977', ';', '04.', 'jenis', 'kelamin', ':', 'laki', 'laki;', '05.', 'kebangsaan', ':', 'indonesia;', '06.', 'tempat', 'tinggal', ':', 'dusun', 'atas', 'desa', 'tlanakan', 'kecamatan', 'tlanakan', 'kabupaten', 'pamekasan', ';', '07.', 'agama', ':', 'islam;', '08.', 'pekerjaan', ':', 'swasta', ';', 'terdakwa', 'halimi', 'bin', 'busadin', 'ditahan', 'dalam', 'tahanan', 'rutan', 'oleh:', '01.', 'penyidik', 'sejak', 'tanggal', '27', 'november', '2022', 'sampai', 'dengan', 'tanggal', '16', 'desember', '2022', '02.', 'perpanjangan', 'penahanan', 'oleh', 'penyidik', 'kepada', 'penuntut', 'umum', 'sejak', 'tanggal', '17', 'desember', '2022', 'sampai', 'dengan', 'tanggal', '25', 'januari', '2023', '03.', 'penuntut', 'umum', 'sejak', 'tanggal', '18', 'januari', '20', '23', 'sampai', 'dengan', 'tanggal', '06', 'februari', '2023', '04.', 'hakim', 'pengadilan', 'negeri', 'sejak', 'tanggal', '25', 'januari', '2023', 'sampai', 'dengan', 'tanggal', '23', 'februari', '2023', '05.', 'perpanjangan', 'penahanan', 'oleh', 'ketua', 'pengadilan', 'negeri', 'sejak', 'tanggal', '24', 'februari', '2023', 'sampa', 'idengan', 'tanggal', '24', 'april', '2023', 'terdakwa', 'di', 'persidangan', 'didampingi', 'oleh', 'penasihat', 'hukumnya', 'bernama', 'moh.barokah', ',', 's.h.', ',', 'dkk', 'advokat', 'dan', 'konsultan', 'hukum', 'pos', 'bantuan', 'hukum', 'advokat', 'indonesia', '(pos', 'bakumadin)', 'yang', 'berkantor', 'di', 'jalan', 'raya', 'camplong', 'desa', 'taddan', 'kecamatan', 'camplong', 'kabupaten', 'sampang,', 'berdasarkan', 'surat', 'kuasa', 'khusus', 'tertanggal', '22', 'februari', '2023', 'dan', 'telah', 'didaftarkan', 'di', 'kepaniteraan', 'pengadilan', 'negeri', 'sampang', 'dengan', 'register', 'surat', 'kuasa', 'nomor', '31/psk.2023/pn', 'spg', 'tanggal', '06', 'maret', '2023', ';', 'pengadilan', 'negeri', 'tersebut', ';', 'setelah', 'membaca', ':', 'penetapan', 'wakil', 'ketua', 'pengadilan', 'negeri', 'sampang', 'nomor', '19/pid.b/2023/pn', 'spg', 'tanggal', '25', 'januari', '2023', 'tentang', 'penunjukan', 'majelis', 'hakim', ';', 'penetapan', 'majelis', 'hakim', 'nomor', '19/pid.b/2023/pn', 'spg', 'tanggal', '25', 'januari', '2023', 'tentang', 'penetapan', 'hari', 'sidang', ';', 'berkas', 'perkara', 'dan', 'sur', 'atsurat', 'lain', 'yang', 'bersangkutan', 'setelah', 'mendengar', 'keterangan', 'saksisaksi', 'dan', 'terdakwa', 'serta', 'memperhatikan', 'barang', 'bukti', 'yang', 'diajukan', 'di', 'persidangan', ';', 'setelah', 'mendengar', 'pembacaan', 'tuntutan', 'pidana', 'yang', 'diajukan', 'oleh', 'penuntut', 'umum', 'yang', 'pada', 'pokoknya', 'sebagai', 'berikut', ':', '01.', 'menyatakan', 'terdakwa', 'halimi', 'bin', 'busadin', 'bersalah', 'melakukan', 'tindak', 'pidana', '“', 'penadahan', '“', 'sebagaimana', 'diatur', 'dalam', 'pasal', '480', 'ke', '1kuhp', 'dalam', 'dakwaan;', '02.', 'menjatuhkan', 'pidana', 'terhadap', 'terdakwa', 'halimi', 'bin', 'busadin', 'selama', '08', '(delapan)', 'bulan', 'dikurungi', 'selama', 'terdakwa', 'dalam', 'tahanan', 'sementara', 'dengan', 'perintah', 'terdakwa', 'tetap', 'ditahan;', '03.', 'menetapkan', 'agar', 'terdakwa', 'membayar', 'biaya', 'perkara', 'sebesar', 'rp.', '5000.', '(lima', 'ribu', 'rupiah', ');', 'menimbang,', 'bahwa', 'atas', 'tuntutan', '(', 'requisitoir)', 'tersebut,', 'terdakwa', 'menyatakan', 'mengajukan', 'permohonan', 'secara', 'lisan', ',', 'memohon', 'supaya', 'mendapat', 'keringanan', 'hukuman', 'karena', 'terdakwa', 'menyesali', 'perbuatannya,', 'bertobat', 'dan', 'tidak', 'akan', 'mengulangi', 'perbuatanya;', 'menimbang,', 'bahwa', 'atas', 'permohonan', 'terdakwa', ',', 'penuntut', 'umum', 'secara', 'lisan', 'menyatakan', 'tetap', 'pada', 'tuntutannya', 'demikian', 'juga', 'denga', 'nterdakwa', 'menyatakan', 'tetap', 'pada', 'permohonannya', ';', 'menimbang,', 'bahwa', 'terdakwa', 'diajukan', 'ke', 'persidangan', 'oleh', 'penuntut', 'umum', 'didakwa', 'berdasarkan', 'surat', 'dakwaan', 'sebagai', 'berikut:', 'bahwa', 'terdakwa', 'halimi', 'bin', 'busadin', 'pada', 'hari', 'rabu', 'tanggal', '23', 'november', '2022', 'sekitar', 'jam', '09.', '30.', '00', 'wib', 'atau', 'sekitar', 'waktu', 'itu', 'atau', 'setidak', 'tidaknya', 'pada', 'waktu', 'lain', 'dalam', 'bulan', 'november', '2022', 'bertempat', 'di', 'rumah', 'terdakwa', 'dusun', 'atas', 'desa', 'tlanakan', 'kecamatan', 'tlanankan', 'kabupaten', 'pamekasan,', 'yang', 'berdsarka', 'nketentuan', 'pasal', '84', 'ayat', '(02)', 'kuhap,', 'oleh', 'karena', 'sebagian', 'besar', 'tempat', 'kediaman', 'para', 'saksi', 'berada', 'di', 'kabupaten', 'sampang', ',', 'maka', 'pengadilan', 'negeri', 'sampang', 'berwenang', 'mengadili', 'dan', 'memeriksa', 'perkara,', 'membeli,', 'menawarkan,', 'menukar,', 'menerima', 'gadai,', 'atau', 'untuk', 'me', 'narik', 'keuntungan,', 'menjual,', 'menyewakan,', 'menukarkan,', 'mengadaikan,', 'mengangkut,', 'menyimpan', 'atau', 'menyembunyikan', 'sesuatu', 'benda,', 'yang', 'diketahuinya', 'atau', 'sepatutnya', 'harus', 'diduga,', 'bahwa', 'diperoleh', 'karena', 'kejahatan', ',', 'perbuatan', 'tersebut', 'terdakwa', 'lakukan', 'dengan', 'cara', 'sebagai', 'berikut', ':', 'berawal', 'pada', 'hari', 'rabu', 'sekira', 'pukul', '08.', '30', 'wib', 'sewaktu', 'terdakwa', 'berada', 'di', 'rumahnya', ',', 'terdakwa', 'di', 'telpon', 'oleh', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', '(penuntutannya', 'diajukan', 'tersendiri', ')', 'dengan', 'maksud', 'dan', 'tujuan', 'untuk', 'menawakan', '01', '(satu)', 'unit', 'sepeda', 'motor', 'supra', 'x125', 'cc', 'warna', 'hitam', 'strip', 'merah', 'tahun', '2010', 'dengan', 'no.pol', ':', 'm4981', 'np', 'noka', ':', 'mhijb8116', 'ak', '506565', 'nosin', ':', 'jb81', 'e', '1501935', 'yang', 'sebelumnya', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'ambil', 'motor', 'tersebut', 'tanpa', 'ijin', 'dari', 'rumah', 'saksi', 'pornomo,', 'karena', 'sebelumya', 'terdakwa', 'pesan', 'kepada', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi,', 'apabila', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'mempunyai', 'sepeda', 'motor', 'tanpa', 'dilengkapi', 'surat', '–', 'surat', 'bisa', 'dijual', 'kepada', 'terdakwa', ',', 'kemudian', 'terdakwa', 'menyuruh', 'saksi', 'miftahul', 'arifin', 'membawa', 'sepeda', 'motor', 'tersebut', 'ke', 'rumah', 'terdakwa', ',', 'sekira', 'jam', '09.', '30', 'wib', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'sampai', 'dirumah', 'terdakwa', ',', 'setelah', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'tiba', 'di', 'rumah', 'terdakwa', 'kemudian', 'terdakwa', 'mengecek', 'ko', 'ndisi', 'sepeda', 'motor', 'supra', 'x125cc', 'tersebut', 'dan', 'menanyakan', 'tentang', 'surat', 'surat', 'dari', 'sepeda', 'motor', 'tersebut', 'kepada', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'dan', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'mengatakan', 'jika', 'sepeda', 'motor', 'tersebut', 'tidak', 'ada', 'stnk', 'dan', 'bpkbnya', ';', 'bahwa', 'setelah', 'terdakwa', 'mengecek', 'kondisi', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc', 'warna', 'hitam', 'stip', 'merah', 'tahun', '2010', 'tersebut', ',', 'kemudian', 'terdakwa', 'menanyakan', 'kepada', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'mau', 'di', 'kasih', 'berapa', 'dan', 'pada', 'saat', 'itu', 'saksi', 'miftahul', 'arin', 'bin', 'supardi', 'menawarkan', 'seharga', 'rp.', '02.', '000.', '000,', 'karena', 'harga', 'sepeda', 'motor', 'honda', 'supra', 'x125cc', 'tersebut', 'dibawah', 'harga', 'pasar', 'kemudian', 'terdakwa', 'menawar', 'dengan', 'harga', 'rp.', '01.', '500.', '000,', 'akhirnya', 'terjadi', 'kesepakatan', 'bersama', 'bahwa', 'terdakwa', 'membeli', 'sepeda', 'motor', 'tersebut', 'dengan', 'har', 'ga', 'rp.', '01.', '700.', '000.', '(satu', 'juta', 'tujuh', 'ratus', 'ribu', 'rupiah', ');', 'bahwa', 'terdakwa', 'halimi', 'bin', 'busadin', 'pada', 'hari', 'rabu', 'tanggal', '23', 'november', '2022', 'sekitar', 'jam', '09.', '30.', '00', 'wib', 'atau', 'sekitar', 'waktu', 'itu', 'atau', 'setidak', 'tidaknya', 'pada', 'waktu', 'lain', 'dalam', 'bulan', 'november', '2022', 'bertempat', 'dirumah', 'terdakwa', 'dusun', 'atas', 'desa', 'tlanakan', 'kecamatan', 'tlanankan', 'kabupaten', 'pamekasan,', 'yang', 'berdsarkan', 'ketentuan', 'pasal', '84', 'ayat', '(02)', 'kuhap,', 'oleh', 'karena', 'sebagian', 'besar', 'tempat', 'kediaman', 'para', 'saksi', 'berada', 'di', 'kabupaten', 'sampang', ',', 'maka', 'pengadilan', 'negeri', 'sampang', 'berwena', 'ng', 'mengadili', 'dan', 'memeriksa', 'perkara,', 'membeli,', 'menawarkan,', 'menukar,', 'menerima', 'gadai,', 'atau', 'untuk', 'menarik', 'keuntungan,', 'menjual,', 'menyewakan,', 'menukarkan,', 'mengadaikan,', 'mengangkut,', 'menyimpan', 'atau', 'menyembunyikan', 'sesuatu', 'benda,', 'yang', 'diketahuinya', 'atau', 'sepatutnya', 'har', 'us', 'diduga,', 'bahwa', 'diperoleh', 'karena', 'kejahatan', ',', 'perbuatan', 'tersebut', 'terdakwa', 'lakukan', 'dengan', 'cara', 'sebagai', 'berikut', ':', 'berawal', 'pada', 'hari', 'rabu', 'sekira', 'pukul', '08.', '30', 'wib', 'sewaktu', 'terdakwa', 'berada', 'di', 'rumahnya', ',', 'terdakwa', 'di', 'telpon', 'oleh', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', '(penuntutannya', 'diajukan', 'tersendiri', ')', 'dengan', 'maksud', 'dan', 'tujuan', 'untuk', 'menawakan', '01', '(satu)', 'unit', 'sepeda', 'motor', 'supra', 'x125', 'cc', 'warna', 'hitam', 'strip', 'merah', 'tahun', '2010', 'dengan', 'no.pol', ':', 'm4981', 'np', 'noka', ':', 'mhijb8116', 'ak', '506565', 'nosin', ':', 'jb81', 'e', '1501935', 'yang', 'sebelumnya', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'ambil', 'motor', 'tersebut', 'tanpa', 'ijin', 'dari', 'rumah', 'saksi', 'pornomo,', 'karena', 'sebelumya', 'terdakwa', 'pesan', 'kepada', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi,', 'apabila', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'mempunya', 'isepeda', 'motor', 'tanpa', 'dilengkapi', 'surat', '–', 'surat', 'bisa', 'dijual', 'kepada', 'terdakwa', ',', 'kemudian', 'terdakwa', 'menyuruh', 'saksi', 'miftahul', 'arifin', 'membawa', 'sepeda', 'motor', 'tersebut', 'ke', 'rumah', 'terdakwa', ',', 'sekira', 'jam', '09.', '30', 'wib', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'sampai', 'dirumah', 'terdakwa', ',', 'setelah', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'tiba', 'di', 'rumah', 'terdakwa', 'kemudian', 'terdakwa', 'mengecek', 'kondisi', 'sepeda', 'motor', 'supra', 'x125cc', 'tersebut', 'dan', 'menanyakan', 'tentang', 'surat', 'surat', 'dari', 'sepeda', 'motor', 'tersebut', 'kepada', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'dan', 'saksi', 'miftah', 'ul', 'arifin', 'bin', 'supardi', 'mengatakan', 'jika', 'sepeda', 'motor', 'terseb', 'ut', 'tidak', 'ada', 'stnk', 'dan', 'bpkbnya;', 'bahwa', 'setelah', 'terdakwa', 'mengecek', 'kondisi', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc', 'warna', 'hitam', 'stip', 'merah', 'tahun', '2010', 'tersebut', ',', 'kemudian', 'terdakwa', 'menanyakan', 'kepada', 'saksi', 'miftahul', 'arifin', 'bin', 'supardi', 'mau', 'di', 'kasih', 'berapa', 'dan', 'pada', 'saat', 'itu', 'saksi', 'miftahul', 'arin', 'bin', 'supardi', 'menawarkan', 'seharga', 'rp.', '02.', '000.', '000,', 'karena', 'harga', 'sepeda', 'motor', 'honda', 'supra', 'x125cc', 'tersebut', 'dibawah', 'harga', 'pasar', 'kemudian', 'terdakwa', 'menawar', 'dengan', 'harga', 'rp.', '01.', '500.', '000,', 'akhirnya', 'terjadi', 'kesepakatan', 'bersama', 'bahwa', 'terdakwa', 'membeli', 'sepeda', 'motor', 'tersebut', 'dengan', 'harga', 'rp.', '01.', '700.', '000.', '(satu', 'juta', 'tujuh', 'ratus', 'ribu', 'rupiah', ');', 'perbutan', 'terdakwa', 'sebagaimana', 'diatur', 'dan', 'diancam', 'pidana', 'dalam', 'pasal', '480', 'ke', '1kuhp', ';', 'menimbang,', 'bahwa', 'dimuka', 'persidangan,', 'terdakwa', '/', 'penasihat', 'hukumnya', 'menyatakan', 'telah', 'mengerti', 'isi', 'dakwaan', 'tersebut', 'dan', 'tidak', 'mengajuka', 'nkeberatan;', 'menimbang,', 'bahwa', 'untuk', 'membuktikan', 'dakwaannya', 'penuntut', 'umum', 'telah', 'mengajukan', 'saksi', 'saksi', 'sebagai', 'berikut:', '01.', 'saksi', 'miftahul', 'arifin', ',', 'di', 'bawah', 'sumpah', 'yang', 'pada', 'pokoknya', 'menerangkan', 'sebagai', 'berikut:', 'bahwa', 'peristiwa', 'tersebut', 'terjadi', 'pada', 'hari', 'selasa', 'tanggal', '22', 'november', '2022', 'sekitar', 'pukul', '11.', '00', 'wib', 'di', 'sebuah', 'teras', 'rumah', 'yang', 'beralamat', 'di', 'jalan', 'pemuda', 'satria', 'kelurahan', 'rongtengah', 'kecamata', 'nsampang', 'kabupaten', 'sampang', 'saksi', 'telah', 'mengambil', '01', '(satu)', 'unit', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc,', 'nopol', 'm', '4981', 'np,', 'tahun', '2010,', 'warna', 'hitam,', 'noka', 'mhijb8116', 'ak', '506565,', 'nosin', 'jb81', 'e', '1501935', ';', 'bahwa', 'saksi', 'sudah', 'mempersiapkan', 'dan', 'saksi', 'rencanakan', 'jauh', 'jauh', 'hari', 'sebelum', 'pada', 'akhirnya', 'saksi', 'melakukan', 'hal', 'tersebut.', 'awalnya', 'rumah', 'tempat', 'sepeda', 'motor', 'tersebut', 'terparkir', 'sudah', 'berberapa', 'hari', 'saksi', 'pantau', 'dengan', 'cara', 'melewati', 'depan', 'rumah', 'setiap', 'hari', 'dan', 'hal', 'tersebut', 'di', 'lakukan', 'saksi', 'selama', '04', '(empat)', 'hari.', 'selama', '04', '(empat', ')', 'hari', 'tersebut', 'saksi', 'selalu', 'mendapati', 'sepeda', 'motor', 'honda', 'supra', 'xselalu', 'terparkir', 'di', 'halaman', 'teras', 'rumah', 'yang', 'terletak', 'di', 'jalan', 'pemuda', 'satria', 'kelurahan', 'rongtengah', 'kecamatan', 'sampang', 'kabupaten', 'sampang', 'serta', 'rumahnya', 'selalu', 'dalam', 'keadaan', 'sepi;', 'bahwa', 'setela', 'hbeberapa', 'hari', 'mengamati', 'sasaran', 'serta', 'memperkirakan', 'segala', 'resiko,', 'kemudian', 'saksi', 'me', 'mutuskan', 'untuk', 'mengambil', 'sepeda', 'motor', 'dengan', 'cara', 'berangkat', 'dari', 'rumah', 'dengan', 'mengendarai', 'sepeda', 'motor', 'milik', 'saksi', 'sendiri', 'lalu', 'karena', 'mogok', 'akhirnya', 'saksi', 'menitipkan', 'motornya', 'kerumah', 'teman', 'saksi', 'yang', 'tidak', 'jauh', 'dari', 'kawasan', 'monument.', 'selanjutnya', 'saksi', 'menelphone', 'teman', 'saksi', 'yaitu', 'hariyanto', 'untuk', 'datang', 'menjemput', 'saksi', 'serta', 'mengantarkan', 'saksi', 'kesuatu', 'tempat', 'dengan', 'alasan', 'akan', 'mengambil', 'alat', 'perbengkelan,', 'kemudian', 'hariyant', 'omengiyakan', 'keinginan', 'saksi.', 'sesampainya', 'di', 'dekat', 'lokasi', 'lalu', 'saksi', 'menyuruh', 'hariyanto', 'berhenti', 'kemudian', 'saksi', 'turun', 'dan', 'mempersilahkan', 'hariyanto', 'untuk', 'meninggalkan', 'saksi;', 'bahwa', 'setelah', 'itu', 'saksi', 'berjalan', 'menuju', 'lokasi', 'sasaran', 'serta', 'melihat', 'dari', 'luar', 'pa', 'gar', 'sepeda', 'motor', 'terparkir', 'diteras', 'rumah,', 'kemudian', 'saksi', 'memastikan', 'situasi', 'sepi', 'lalu', 'saksi', 'mendekati', 'sepeda', 'motor', 'tersebut', 'dan', 'bergegas', 'membobol', 'rumah', 'kunci', 'dengan', 'menggunakan', 'sebuah', 'kunci', 'tyang', 'sudah', 'saksi', 'persiapkan', 'dari', 'rumah.', 'setelah', 'stir', 'tidak', 'terku', 'nci', 'serta', 'indicator', 'sudah', 'menyala', 'lalu', 'saksi', 'menuntun', 'sepeda', 'motor', 'untuk', 'membawanya', 'menjauh', 'dari', 'lokasi;', 'bahwa', 'setelah', 'saksi', 'berhasil', 'mengambil', 'sepeda', 'motor', 'tersebut', 'lalu', 'saksi', 'membawa', 'sepeda', 'motor', 'tersebut', 'ke', 'pamekasan', 'untuk', 'saksi', 'tawarkan', 'kepada', 'terdakwa', 'yang', 'merupakan', 'teman', 'saksi', 'yang', 'tinggal', 'di', 'desa', 'tlanakan', 'kecamatan', 'tlanakan', 'kabupaten', 'pamekasan', 'karena', 'sebelumnya', 'terdakwa', 'mengatakan', 'apabila', 'saksi', 'memiliki', 'sepeda', 'motor', 'tanpa', 'dilengkapi', 'surat', 'surat', 'saksi', 'bisa', 'menjualnya', 'kepada', 'terdakwa', ';', 'bahwa', 'terdakwa', 'membeli', 'sepeda', 'motor', 'honda', 'supra', 'xtersebut', 'dengan', 'harga', 'sebesar', 'rp1.', '300.', '000,00', '(satu', 'juta', 'tiga', 'ratus', 'ribu', 'rupiah)', 'dan', 'saksi', 'menyepakatinya.', 'kemudian,', 'maksud', 'dan', 'tujuan', 'saksi', 'melakukan', 'hal', 'tersebut', 'karena', 'ingin', 'saksi', 'jual', 'atau', 'gadaikan', 'dan', 'hasilnya', 'akan', 'saksi', 'gunakan', 'untuk', 'membayar', 'hutan', 'serta', 'memenuhi', 'kebutuhan', 'sehari', 'hari', 'saksi;', 'bahwa', 'pada', 'saat', 'itu', 'saksi', 'mengambil', 'sepeda', 'motor', 'tersebut', 'sendirian', 'dengan', 'cara', 'menggunakan', 'kunci', 'tdan', 'saat', 'ini', 'kunci', 'ttersebut', 'saksi', 'buang', 'disungai', 'dibawah', 'jembatan', 'yang', 'lokasinya', 'tidak', 'jauh', 'dari', 'kawasan', 'terminal', 'sampang', ';', 'bahwa', 'saksi', 'mengambil', 'sepeda', 'motor', 'milik', 'orang', 'yang', 'tidak', 'dikenal', 'tersebut', 'tidak', 'ijin', 'terhadap', 'orang', 'tersebut', ';', 'atas', 'keterangan', 'tersebut', 'terdakwa', 'tidak', 'keberatan', 'dan', 'membenarkannya;', '02.', 'saksi', 'jupriadi', ',', 'di', 'bawah', 'sumpah', 'yang', 'pada', 'pokoknya', 'menerangkan', 'sebagai', 'berikut', ':', 'bahwa', 'peristiwa', 'tersebut', 'terjadi', 'pada', 'hari', 'rabu', 'tanggal', '23', 'november', '2022', 'sekitar', 'pukul', '10', '.00', 'wib', 'di', 'rumah', 'terdakwa', 'yang', 'beralamat', 'didusun', 'beddian', 'desa', 'beddurih', 'kecamatan', 'pademawu', 'kabupaten', 'pamekasan', 'saksi', 'telah', 'membeli', '01', '(satu)', 'unit', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc,', 'nopol', 'm', '4981', 'np,', 'tahun', '2010,', 'warna', 'hitam,', 'noka', 'mhijb8116', 'ak', '506565,', 'nosin', 'jb81', 'e', '1501935', 'dari', 'terdakwa', ',', 'namun', 'sepeda', 'moto', 'rtersebut', 'merupakan', 'hasil', 'dari', 'kejahatan', ';', 'bahwa', 'awalnya', 'saksi', 'di', 'telephone', 'oleh', 'terdakwa', 'dan', 'memberitahu', 'kepada', 'saksi', 'apabila', 'baru', 'saja', 'membeli', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc', 'dari', 'saksi', 'miftahul', 'aripin', 'warga', 'sampang', 'seharga', 'rp1.', '700.', '000,', '00', '(satu', 'juta', 'tujuh', 'ratus', 'ribu', 'rupiah).', 'karena', 'saat', 'itu', 'terdakwa', 'sedang', 'butuh', 'uang', 'sehingga', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc', 'oleh', 'terdakwa', 'akan', 'di', 'jual', 'kembali', 'kepada', 'saksi', 'sebesar', 'rp1.', '800.', '000,00', '(satu', 'juta', 'delapan', 'ratus', 'ribu', 'rupiah)', 'karena', 'sedang', 'membutuhka', 'nuang', 'lalu', 'saat', 'itu', 'juga', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc', 'diantarkan', 'kerumah', 'saksi', 'oleh', 'terdakwa', '.', 'setelah', 'cocok', 'saksi', 'langsung', 'membayar', 'sebesar', 'rp1.', '800.', '000,00', '(satu', 'juta', 'delapan', 'ratus', 'ribu', 'rupiah)', ';', 'bahwa', 'setelah', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc', 'ada', 'di', 'penguasaan', 'saksi', 'lalu', 'saksi', 'mencuci', 'sepeda', 'motor', 'tersebut', 'karena', 'sepeda', 'motor', 'tersebut', 'dalam', 'keadaan', 'kotor', 'dan', 'kaca', 'lampu', 'depan', 'saat', 'saksi', 'terima', 'dalam', 'keadaan', 'pecah', 'serta', 'diisolasi.', 'setelah', 'itu', 'oleh', 'saksi', 'kaca', 'lampunya', 'di', 'belikan;', 'bahwa', 'saksi', 'tidak', 'mengetahui', 'apabila', 'sepeda', 'motor', 'honda', 'supra', 'x125', 'cc', 'adalah', 'dari', 'hasil', 'kejahatan;', 'atas', 'keterangan', 'tersebut', 'terdakwa', 'tidak', 'keberatan', 'dan', 'membenarkannya;', '03.', 'saksi', 'poernomo', ',', 'di', 'bawah', 'sumpah', 'yang', 'pada', 'pokoknya', 'menerangkan', 'sebagai', 'berikut:', 'bahwa', 'perist', 'iwa', 'tersebut', 'terjadi', 'pada', 'hari', 'selasa', 'tanggal', '22', 'november', '2022', 'sekitar', 'pukul', '11.', '00', 'wib', 'di', 'garasi', 'depan', 'rumah', 'yang', 'terlet

In [ ]:
for token, label in zip(text_example, label_example):
  if label != 'O' or token == ' ':
    print(f"Token Text : {token} => {label}")

Token Text : 19/pid.b/2023/pn => B_VERN
Token Text : spg => I_VERN
Token Text : halimi => B_DEFN
Token Text : bin => I_DEFN
Token Text : busadin => I_DEFN
Token Text : halimi => B_DEFN
Token Text : bin => I_DEFN
Token Text : busadin => I_DEFN
Token Text : 19/pid.b/2023/pn => B_VERN
Token Text : spg => I_VERN
Token Text : 19/pid.b/2023/pn => B_VERN
Token Text : spg => I_VERN
Token Text : halimi => B_DEFN
Token Text : bin => I_DEFN
Token Text : busadin => I_DEFN
Token Text : penadahan => B_CRIA
Token Text : 480 => B_ARTV
Token Text : ke => I_ARTV
Token Text : 1kuhp => I_ARTV
Token Text : halimi => B_DEFN
Token Text : bin => I_DEFN
Token Text : busadin => I_DEFN
Token Text : 08 => B_PENA
Token Text : (delapan) => I_PENA
Token Text : bulan => I_PENA
Token Text : dikurungi => I_PENA
Token Text : selama => I_PENA
Token Text : terdakwa => I_PENA
Token Text : dalam => I_PENA
Token Text : tahanan => I_PENA
Token Text : sementara => I_PENA
Token Text : dengan => I_PENA
Token Text : perintah => I_PENA
Token Text : terdakwa => I_PENA
Token Text : tetap => I_PENA
Token Text : ditahan; => I_PENA
Token Text : halimi => B_DEFN
Token Text : bin => I_DEFN
Token Text : busadin => I_DEFN
Token Text : halimi => B_DEFN
Token Text : bin => I_DEFN
Token Text : busadin => I_DEFN
Token Text : 480 => B_ARTV
Token Text : ke => I_ARTV
Token Text : 1kuhp => I_ARTV
Token Text : 480 => B_ARTV
Token Text : ke => I_ARTV
Token Text : 1kuhp, => I_ARTV
Token Text : halimi => B_DEFN
Token Text : bin => I_DEFN
Token Text : busadin => I_DEFN
Token Text : 480 => B_ARTV
Token Text : ke => I_ARTV
Token Text : 1kuhp => I_ARTV
Token Text : penadahan => B_CRIA
Token Text : 480 => B_ARTV
Token Text : ke => I_ARTV
Token Text : 1kuhp => I_ARTV
Token Text : halimi => B_DEFN
Token Text : bin => I_DEFN
Token Text : busadin => I_DEFN
Token Text : penadahan => B_CRIA
Token Text : 15 => B_TIMV
Token Text : maret => I_TIMV
Token Text : 2023 => I_TIMV
Token Text : afrizal => B_JUDP
Token Text : agus => B_JUG
Token Text : eman, => I_JUG
Token Text : h. => B_REGI
Token Text : yuli => I_REGI
Token Text : karyanto => I_REGI
Token Text : agus => B_JUG
Token Text : eman, => I_JUG
Token Text : afrizal => B_JUDP
Token Text : h. => B_REGI
Token Text : yuli => I_REGI
Token Text : karyanto => I_REGI

## Split token

In [ ]:
def split_token(dataset):
  for i, row in tqdm.tqdm(dataset.iterrows(), total=len(dataset), desc="Processing rows"):
    for index, (text, tag) in enumerate(zip(row["text"], row["label"])):
      if tag != "O":
        token = re.findall(r'[^\/,\.():;]+|[\/\.,():;]', text)
        add_label = []
        for i in range(len(token)):
          if 'B' in tag and not add_label:
            add_label.append(tag)
          else:
            if token[i] != ';':
              add_label.append(tag.replace('B', 'I'))
            else:
              add_label.append('O')

        del row["text"][index]
        del row["label"][index]
        row["text"][index:index] = token
        row["label"][index:index] = add_label
      else:
        token = re.findall(r'[^\/,\.():;]+|[\/\.,():;]', text)
        add_label = []
        for i in range(len(token)):
          add_label.append('O')

        del row["text"][index]
        del row["label"][index]
        row["text"][index:index] = token
        row["label"][index:index] = add_label
  return dataset
split_token(df)

Processing rows: 100%|██████████| 500/500 [01:02<00:00,  8.06it/s]

,text,label
0,"[putusan, nomor, 48, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
1,"[putusan, nomor, 42, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
2,"[putusan, nomor, 49, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
3,"[putusan, nomor, 56, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
4,"[putusan, nomor, 57, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
...,...,...
495,"[putusan, nomor, 33, /, pid, ., b, /, 2022, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
496,"[putusan, nomor, 25, /, pid, ., b, /, 2022, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
497,"[nomor, 05, /, pid, ., b, /, 2022, /, pn, smp,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
498,"[putusan, nomor, 19, /, pid, ., sus, /, 2022, ...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
499,"[putusan, nomor, 298, /, pid, ., b, /, 2021, /...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [ ]:
for token, label in zip(df.loc(0)[0:0]["text"], df.loc(0)[0:0]["label"]):
  for index, (word, l) in enumerate(zip(token, label)):
    if label != 'O' or token == ' ':
      print(f"Token Text : {word} => {l}")

Streaming output truncated to the last 5000 lines.
Token Text : kunci => O
Token Text : kontak => O
Token Text : lalu => O
Token Text : memutar => O
Token Text : paksa => O
Token Text : kunci => O
Token Text : tke => O
Token Text : arah => O
Token Text : “on” => O
Token Text : sehingga => O
Token Text : rumah => O
Token Text : kunci => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : rusak => O
Token Text : , => O
Token Text : setelah => O
Token Text : itu => O
Token Text : satu => O
Token Text : persatu => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : dituntun => O
Token Text : oleh => O
Token Text : saksi => O
Token Text : dan => O
Token Text : terdakwa => O
Token Text : lalu => O
Token Text : setelah => O
Token Text : agak => O
Token Text : jauh => O
Token Text : , => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : dihidupkan => O
Token Text : lalu => O
Token Text : dibawa => O
Token Text : kabur => O
Token Text : oleh => O
Token Text : saksi => O
Token Text : dan => O
Token Text : terdakwa => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : yang => O
Token Text : berhasil => O
Token Text : dicuri => O
Token Text : tersebut => O
Token Text : , => O
Token Text : oleh => O
Token Text : saksi => O
Token Text : dan => O
Token Text : terdakwa => O
Token Text : dibawa => O
Token Text : ke => O
Token Text : rumah => O
Token Text : subhan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : selanjutnya => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : dijual => O
Token Text : oleh => O
Token Text : subhan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : saksi => O
Token Text : tidak => O
Token Text : tahu => O
Token Text : dijual => O
Token Text : kepada => O
Token Text : siapa => O
Token Text : oleh => O
Token Text : subhan => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : menurut => O
Token Text : pengakuan => O
Token Text : subhan => O
Token Text : , => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : hasil => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : dijual => O
Token Text : dengan => O
Token Text : harga => O
Token Text : rp => O
Token Text : . => O
Token Text : 7000 => O
Token Text : . => O
Token Text : 000 => O
Token Text : , => O
Token Text : ( => O
Token Text : tujuh => O
Token Text : juta => O
Token Text : rupiah => O
Token Text : ) => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : dari => O
Token Text : hasil => O
Token Text : menjual => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : , => O
Token Text : saksi => O
Token Text : dan => O
Token Text : terdakwa => O
Token Text : masingmasing => O
Token Text : mendapat => O
Token Text : bagian => O
Token Text : sebesar => O
Token Text : rp => O
Token Text : . => O
Token Text : 02 => O
Token Text : . => O
Token Text : 000 => O
Token Text : . => O
Token Text : 000 => O
Token Text : , => O
Token Text : ( => O
Token Text : dua => O
Token Text : juta => O
Token Text : rupiah => O
Token Text : ) => O
Token Text : , => O
Token Text : sedangkan => O
Token Text : sisanya => O
Token Text : sebesar => O
Token Text : rp => O
Token Text : . => O
Token Text : 03 => O
Token Text : . => O
Token Text : 000 => O
Token Text : . => O
Token Text : 000 => O
Token Text : , => O
Token Text : ( => O
Token Text : tiga => O
Token Text : juta => O
Token Text : rupiah => O
Token Text : ) => O
Token Text : adalah => O
Token Text : bagian => O
Token Text : subhan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : uang => O
Token Text : hasil => O
Token Text : menjual => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : , => O
Token Text : saksi => O
Token Text : gunakan => O
Token Text : untuk => O
Token Text : kebutuhan => O
Token Text : seharihari => O
Token Text : seperti => O
Token Text : makan => O
Token Text : dan => O
Token Text : beli => O
Token Text : rokok => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : sewaktu => O
Token Text : mengambil => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : , => O
Token Text : saksi => O
Token Text : dan => O
Token Text : terdakwa => O
Token Text : tidak => O
Token Text : minta => O
Token Text : ijin => O
Token Text : terlebih => O
Token Text : dahulu => O
Token Text : kepada => O
Token Text : pemiliknya => O
Token Text : ; => O
Token Text : terhadap => O
Token Text : keterangan => O
Token Text : saksi => O
Token Text : , => O
Token Text : terdakwa => O
Token Text : memberikan => O
Token Text : pendapat => O
Token Text : benar => O
Token Text : dan => O
Token Text : tidak => O
Token Text : keberatan => O
Token Text : . => O
Token Text : menimbang => O
Token Text : , => O
Token Text : bahwa => O
Token Text : terdakwa => O
Token Text : di => O
Token Text : persidangan => O
Token Text : telah => O
Token Text : memberikan => O
Token Text : keterangan => O
Token Text : yang => O
Token Text : pada => O
Token Text : pokoknya => O
Token Text : sebagai => O
Token Text : berikut => O
Token Text : : => O
Token Text : bahwa => O
Token Text : terdakwa => O
Token Text : dihadapkan => O
Token Text : dipersidangan => O
Token Text : ini => O
Token Text : karena => O
Token Text : telah => O
Token Text : melakukan => O
Token Text : pencurian => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : barang => O
Token Text : yang => O
Token Text : telah => O
Token Text : dicuri => O
Token Text : oleh => O
Token Text : terdakwa => O
Token Text : adalah => O
Token Text : berupa => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : terdakwa => O
Token Text : telah => O
Token Text : melakukan => O
Token Text : pencurian => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : pada => O
Token Text : hari => O
Token Text : sabtu => O
Token Text : , => O
Token Text : tanggal => O
Token Text : 30 => O
Token Text : desember => O
Token Text : 2023 => O
Token Text : , => O
Token Text : sekira => O
Token Text : pukul => O
Token Text : 03 => O
Token Text : . => O
Token Text : 00 => O
Token Text : . => O
Token Text : wib => O
Token Text : . => O
Token Text : di => O
Token Text : teras => O
Token Text : belakang => O
Token Text : sebuah => O
Token Text : rumah => O
Token Text : , => O
Token Text : di => O
Token Text : depan => O
Token Text : dapur => O
Token Text : di => O
Token Text : dusun => O
Token Text : lang => O
Token Text : lebar => O
Token Text : , => O
Token Text : desa => O
Token Text : batobelle => O
Token Text : , => O
Token Text : kecamatan => O
Token Text : geger => O
Token Text : , => O
Token Text : kabupaten => O
Token Text : bangkalan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : terdakwa => O
Token Text : melakukan => O
Token Text : pencurian => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : bersama => O
Token Text : dengan => O
Token Text : teman => O
Token Text : terdakwa => O
Token Text : yang => O
Token Text : bernama => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : , => O
Token Text : mahmud => O
Token Text : dan => O
Token Text : subhan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : ciriciri => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : yang => O
Token Text : terdakwa => O
Token Text : curi => O
Token Text : bersama => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : ( => O
Token Text : berkas => O
Token Text : terpisah => O
Token Text : ) => O
Token Text : mahmud => O
Token Text : dan => O
Token Text : subhan => O
Token Text : yaitu => O
Token Text : yang => O
Token Text : pertama => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : honda => O
Token Text : vario => O
Token Text : , => O
Token Text : warna => O
Token Text : white => O
Token Text : silver => O
Token Text : nopol => O
Token Text : m3728hb => O
Token Text : dan => O
Token Text : satunya => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : vario => O
Token Text : 125 => O
Token Text : 1ss => O
Token Text : , => O
Token Text : warna => O
Token Text : putih => O
Token Text : strip => O
Token Text : merah => O
Token Text : , => O
Token Text : nopol => O
Token Text : m3089gc => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : rumah => O
Token Text : dimana => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : diparkir => O
Token Text : tidak => O
Token Text : ada => O
Token Text : pagarnya => O
Token Text : hanya => O
Token Text : dkelilingi => O
Token Text : oleh => O
Token Text : beberapa => O
Token Text : bangunan => O
Token Text : dan => O
Token Text : kandang => O
Token Text : hewan => O
Token Text : dan => O
Token Text : satusatunya => O
Token Text : jalan => O
Token Text : menuju => O
Token Text : tempat => O
Token Text : tersebut => O
Token Text : lewat => O
Token Text : depan => O
Token Text : rumah => O
Token Text : utama => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : diparkir => O
Token Text : dalam => O
Token Text : keadaan => O
Token Text : terkunci => O
Token Text : stir => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : terdakwa => O
Token Text : tidak => O
Token Text : tahu => O
Token Text : siapakah => O
Token Text : pemilik => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : yang => O
Token Text : diambil => O
Token Text : oleh => O
Token Text : terdakwa => O
Token Text : tersebut => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : yang => O
Token Text : mempunyai => O
Token Text : ide => O
Token Text : untuk => O
Token Text : melakukan => O
Token Text : pencurian => O
Token Text : adalah => O
Token Text : terdakwa => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : untuk => O
Token Text : menuju => O
Token Text : ke => O
Token Text : tempat => O
Token Text : pencurian => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : , => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : diantar => O
Token Text : mahmud => O
Token Text : naik => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : berboncengan => O
Token Text : , => O
Token Text : sedangkan => O
Token Text : terdaka => O
Token Text : diantar => O
Token Text : subhan => O
Token Text : naik => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : berboncengan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : dalam => O
Token Text : pencurian => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : , => O
Token Text : peran => O
Token Text : terdakwa => O
Token Text : dan => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : sebagai => O
Token Text : orang => O
Token Text : yang => O
Token Text : mengambil => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : sedangkan => O
Token Text : mahmud => O
Token Text : dan => O
Token Text : subhan => O
Token Text : sebagai => O
Token Text : orang => O
Token Text : yang => O
Token Text : membonceng => O
Token Text : terdakwa => O
Token Text : dan => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : ke => O
Token Text : tempat => O
Token Text : kejadian => O
Token Text : dengan => O
Token Text : naik => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : dalam => O
Token Text : melakukan => O
Token Text : pencurian => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : , => O
Token Text : alat => O
Token Text : yang => O
Token Text : digunakan => O
Token Text : adalah => O
Token Text : kunci => O
Token Text : tyang => O
Token Text : terbuat => O
Token Text : dari => O
Token Text : besi => O
Token Text : dan => O
Token Text : bagian => O
Token Text : depannya => O
Token Text : pipih => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : kunci => O
Token Text : tyang => O
Token Text : terbuat => O
Token Text : dari => O
Token Text : besi => O
Token Text : dan => O
Token Text : bagian => O
Token Text : depannya => O
Token Text : pipih => O
Token Text : yang => O
Token Text : dipakai => O
Token Text : sebagai => O
Token Text : alat => O
Token Text : untuk => O
Token Text : melakukan => O
Token Text : pencurian => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : miliknya => O
Token Text : subhan => O
Token Text : dan => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : pinjam => O
Token Text : untuk => O
Token Text : melakukan => O
Token Text : pencurian => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : terdakwa => O
Token Text : mengambil => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : yaitu => O
Token Text : awalnya => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : memasukkan => O
Token Text : kunci => O
Token Text : tke => O
Token Text : dalam => O
Token Text : rumah => O
Token Text : kunci => O
Token Text : kontak => O
Token Text : lalu => O
Token Text : memutar => O
Token Text : paksa => O
Token Text : kunci => O
Token Text : tke => O
Token Text : arah => O
Token Text : “on” => O
Token Text : sehingga => O
Token Text : rumah => O
Token Text : kunci => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : rusak => O
Token Text : , => O
Token Text : demikian => O
Token Text : juga => O
Token Text : dengan => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : yang => O
Token Text : satunya => O
Token Text : , => O
Token Text : setelah => O
Token Text : itu => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : dituntun => O
Token Text : oleh => O
Token Text : terdakwa => O
Token Text : dan => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : ( => O
Token Text : berkas => O
Token Text : terpisah => O
Token Text : ) => O
Token Text : dan => O
Token Text : setelah => O
Token Text : agak => O
Token Text : jauh => O
Token Text : lalu => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : dihidupkan => O
Token Text : mesinnya => O
Token Text : dan => O
Token Text : dibawa => O
Token Text : kabur => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : hasil => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : , => O
Token Text : oleh => O
Token Text : terdakwa => O
Token Text : dan => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : ( => O
Token Text : berkas => O
Token Text : terpisah => O
Token Text : ) => O
Token Text : dibawa => O
Token Text : ke => O
Token Text : rumah => O
Token Text : subhan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : selanjutnya => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : dijual => O
Token Text : oleh => O
Token Text : subhan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : terdakwa => O
Token Text : tidak => O
Token Text : tahu => O
Token Text : kepada => O
Token Text : siapa => O
Token Text : subhan => O
Token Text : menjual => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : curia => O
Token Text : tersebut => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : menurut => O
Token Text : pengakuan => O
Token Text : subhan => O
Token Text : , => O
Token Text : 02 => O
Token Text : ( => O
Token Text : dua => O
Token Text : ) => O
Token Text : unit => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : hasil => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : dijual => O
Token Text : dengan => O
Token Text : harga => O
Token Text : rp => O
Token Text : . => O
Token Text : 7000 => O
Token Text : . => O
Token Text : 000 => O
Token Text : , => O
Token Text : ( => O
Token Text : tujuh => O
Token Text : juta => O
Token Text : rupiah => O
Token Text : ) => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : dari => O
Token Text : hasil => O
Token Text : menjual => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : curian => O
Token Text : tersebut => O
Token Text : , => O
Token Text : terdakwa => O
Token Text : dan => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : masingmasing => O
Token Text : mendapat => O
Token Text : bagian => O
Token Text : sebesar => O
Token Text : rp => O
Token Text : . => O
Token Text : 02 => O
Token Text : . => O
Token Text : 000 => O
Token Text : . => O
Token Text : 000 => O
Token Text : , => O
Token Text : ( => O
Token Text : dua => O
Token Text : juta => O
Token Text : rupiah => O
Token Text : ) => O
Token Text : , => O
Token Text : sedangkan => O
Token Text : sisanya => O
Token Text : sebesar => O
Token Text : rp => O
Token Text : . => O
Token Text : 03 => O
Token Text : . => O
Token Text : 000 => O
Token Text : . => O
Token Text : 000 => O
Token Text : , => O
Token Text : ( => O
Token Text : tiga => O
Token Text : juta => O
Token Text : rupiah => O
Token Text : ) => O
Token Text : adalah => O
Token Text : bagian => O
Token Text : subhan => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : sewaktu => O
Token Text : mengambil => O
Token Text : sepeda => O
Token Text : motor => O
Token Text : tersebut => O
Token Text : , => O
Token Text : terdakwa => O
Token Text : dan => O
Token Text : fandi => O
Token Text : bin => O
Token Text : sulaiman => O
Token Text : ( => O
Token Text : berkas => O
Token Text : terpisah => O
Token Text : ) => O
Token Text : tidak => O
Token Text : minta => O
Token Text : ijin => O
Token Text : terlebih => O
Token Text : dahulu => O
Token Text : kepada => O
Token Text : pemiliknya => O
Token Text : ; => O
Token Text : bahwa => O
Token Text : terdakwa => O

## Menambahkan kolom Doc

In [ ]:
doc_column = ['doc: ' + str(i + 1) for i in range(len(df))]
df['doc'] = doc_column
df

,text,label,doc
0,"[putusan, nomor, 48, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1
1,"[putusan, nomor, 42, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 2
2,"[putusan, nomor, 49, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 3
3,"[putusan, nomor, 56, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 4
4,"[putusan, nomor, 57, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 5
...,...,...,...
495,"[putusan, nomor, 33, /, pid, ., b, /, 2022, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 496
496,"[putusan, nomor, 25, /, pid, ., b, /, 2022, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 497
497,"[nomor, 05, /, pid, ., b, /, 2022, /, pn, smp,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 498
498,"[putusan, nomor, 19, /, pid, ., sus, /, 2022, ...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 499
499,"[putusan, nomor, 298, /, pid, ., b, /, 2021, /...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500

## Split data per Sentence

In [ ]:
new_rows = []
for index, row in df.iterrows():
    sentences = []
    tags = []
    sentence = []
    tag = []
    for word, tag_word in zip(row['text'], row['label']):
      if word != ';':
          sentence.append(word)
          tag.append(tag_word)
      else:
          if sentence:
              sentences.append(sentence)
              tags.append(tag)
          sentence = []
          tag = []
    if sentence:
      sentences.append(sentence)
      tags.append(tag)
    for sentence, tag in zip(sentences, tags):
      new_rows.append({
          'text': sentence,
          'label': tag,
          'doc': row['doc']
      })
new_df = pd.DataFrame(new_rows)
new_df

,text,label,doc
0,"[putusan, nomor, 48, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1
1,"[pengadilan, negeri, tersebut]","[O, O, O]",doc: 1
2,"[setelah, membaca, :, penetapan, ketua, pengad...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_...",doc: 1
3,"[penetapan, majelis, hakim, nomor, 48, /, pid,...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I...",doc: 1
4,"[berkas, perkara, dan, suratsurat, lain, yang,...","[O, O, O, O, O, O, O]",doc: 1
...,...,...,...
65695,"[04, ., menetapkan, agar, terdakwa, tetap, dit...","[O, O, O, O, O, O, O]",doc: 500
65696,"[05, ., menetapkan, barang, bukti, berupa, 11,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500
65697,"[06, ., membebankan, kepada, terdakwa, membaya...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500
65698,"[demikian, lah, diputus, kan, dalam, sidang, p...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500
65699,"[hakim, hakim, anggota, hakim, ketua, ttd, ., ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500

## Menambahkan kolom Sentence

In [ ]:
new_df['sentence'] = new_df.index.map(lambda x: f'sentence: {x + 1:06}')
new_df

,text,label,doc,sentence
0,"[putusan, nomor, 48, /, pid, ., b, /, 2024, /,...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1,sentence: 000001
1,"[pengadilan, negeri, tersebut]","[O, O, O]",doc: 1,sentence: 000002
2,"[setelah, membaca, :, penetapan, ketua, pengad...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_...",doc: 1,sentence: 000003
3,"[penetapan, majelis, hakim, nomor, 48, /, pid,...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I...",doc: 1,sentence: 000004
4,"[berkas, perkara, dan, suratsurat, lain, yang,...","[O, O, O, O, O, O, O]",doc: 1,sentence: 000005
...,...,...,...,...
65695,"[04, ., menetapkan, agar, terdakwa, tetap, dit...","[O, O, O, O, O, O, O]",doc: 500,sentence: 065696
65696,"[05, ., menetapkan, barang, bukti, berupa, 11,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500,sentence: 065697
65697,"[06, ., membebankan, kepada, terdakwa, membaya...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500,sentence: 065698
65698,"[demikian, lah, diputus, kan, dalam, sidang, p...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500,sentence: 065699
65699,"[hakim, hakim, anggota, hakim, ketua, ttd, ., ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",doc: 500,sentence: 065700

## Menghilangkan Tag yang hanya berisi O

In [ ]:
# def contains_non_O(labels):
#     return any(label != 'O' for label in labels)
# mask = new_df['text-tags'].apply(contains_non_O)
# new_df = new_df[mask].reset_index(drop=True)
# new_df

## Tokenisasi per kata

In [ ]:
tokens = []
tags = []
docs = []
sentences = []
for i, row in new_df.iterrows():
    for token, tag in zip(row['text'], row['label']):
        tokens.append(token)
        tags.append(tag)
        docs.append(row['doc'])
        sentences.append(row['sentence'])
tokenized_df = pd.DataFrame({
    'text': tokens,
    'label': tags,
    'doc': docs,
    'sentence': sentences
})
tokenized_df

            text   label       doc          sentence
0        putusan       O    doc: 1  sentence: 000001
1          nomor       O    doc: 1  sentence: 000001
2             48  B_VERN    doc: 1  sentence: 000001
3              /  I_VERN    doc: 1  sentence: 000001
4            pid  I_VERN    doc: 1  sentence: 000001
...          ...     ...       ...               ...
3296245   achmad  B_REGI  doc: 500  sentence: 065700
3296246  junaidi  I_REGI  doc: 500  sentence: 065700
3296247        ,       O  doc: 500  sentence: 065700
3296248       sh       O  doc: 500  sentence: 065700
3296249        .       O  doc: 500  sentence: 065700

[3296250 rows x 4 columns]

## Menambahkan Kolom Prev dan Next

In [ ]:
tokenized_df['prev'] = tokenized_df['text'].shift(1)
tokenized_df['next'] = tokenized_df['text'].shift(-1)
tokenized_df['prev'].fillna('.', inplace=True)
tokenized_df['next'].fillna('.', inplace=True)

In [ ]:
tokenized_df

            text   label       doc          sentence     prev     next
0        putusan       O    doc: 1  sentence: 000001        .    nomor
1          nomor       O    doc: 1  sentence: 000001  putusan       48
2             48  B_VERN    doc: 1  sentence: 000001    nomor        /
3              /  I_VERN    doc: 1  sentence: 000001       48      pid
4            pid  I_VERN    doc: 1  sentence: 000001        /        .
...          ...     ...       ...               ...      ...      ...
3296245   achmad  B_REGI  doc: 500  sentence: 065700        .  junaidi
3296246  junaidi  I_REGI  doc: 500  sentence: 065700   achmad        ,
3296247        ,       O  doc: 500  sentence: 065700  junaidi       sh
3296248       sh       O  doc: 500  sentence: 065700        ,        .
3296249        .       O  doc: 500  sentence: 065700       sh        .

[3296250 rows x 6 columns]

In [ ]:
proces_data = tokenized_df.rename(columns={'text': 'word', 'label': 'tag'}).reindex(columns=['doc','sentence', 'word', 'prev', 'next', 'tag'])
proces_data

              doc          sentence     word     prev     next     tag
0          doc: 1  sentence: 000001  putusan        .    nomor       O
1          doc: 1  sentence: 000001    nomor  putusan       48       O
2          doc: 1  sentence: 000001       48    nomor        /  B_VERN
3          doc: 1  sentence: 000001        /       48      pid  I_VERN
4          doc: 1  sentence: 000001      pid        /        .  I_VERN
...           ...               ...      ...      ...      ...     ...
3296245  doc: 500  sentence: 065700   achmad        .  junaidi  B_REGI
3296246  doc: 500  sentence: 065700  junaidi   achmad        ,  I_REGI
3296247  doc: 500  sentence: 065700        ,  junaidi       sh       O
3296248  doc: 500  sentence: 065700       sh        ,        .       O
3296249  doc: 500  sentence: 065700        .       sh        .       O

[3296250 rows x 6 columns]

In [ ]:
proces_data1 = proces_data.iloc[0:1000000]
proces_data2 = proces_data.iloc[1000000:2000000]
proces_data3 = proces_data.iloc[2000000:]

In [ ]:
proces_data3

              doc          sentence     word         prev     next     tag
2000000  doc: 292  sentence: 039905  sebagai  menerangkan  berikut       O
2000001  doc: 292  sentence: 039905  berikut      sebagai        :       O
2000002  doc: 292  sentence: 039905        :      berikut   ─bahwa       O
2000003  doc: 292  sentence: 039905   ─bahwa            :    saksi       O
2000004  doc: 292  sentence: 039905    saksi       ─bahwa   pernah       O
...           ...               ...      ...          ...      ...     ...
3296245  doc: 500  sentence: 065700   achmad            .  junaidi  B_REGI
3296246  doc: 500  sentence: 065700  junaidi       achmad        ,  I_REGI
3296247  doc: 500  sentence: 065700        ,      junaidi       sh       O
3296248  doc: 500  sentence: 065700       sh            ,        .       O
3296249  doc: 500  sentence: 065700        .           sh        .       O

[1296250 rows x 6 columns]

In [ ]:
proces_data1.to_csv('Dataset1.csv', index=False)
proces_data2.to_csv('Dataset2.csv', index=False)
proces_data3.to_csv('Dataset3.csv', index=False)
# proces_data.to_csv('Dataset-Pidana500.csv', index=False)