# Pre Processing Dataset Merge

In [32]:
import pandas as pd
import nltk
import time
import re
import tqdm

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

## Dataset Lama

In [21]:
load_df_lama = pd.read_csv('/content/drive/MyDrive/NER nlp/Dataset/LEGALNER-POS-PREV-NEXT-200.csv')
load_df_lama = load_df_lama.fillna(method="ffill")
df_grouped = load_df_lama.groupby('doc').agg({
    'sentence': ' '.join,
    'word': ' '.join,
    'pos': ' '.join,
    'prev': ' '.join,
    'next': ' '.join,
    'tag': ' '.join
}).reset_index()

<ipython-input-21-a3e82cf8f73e>:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  load_df_lama = pd.read_csv('/content/drive/MyDrive/NER nlp/Dataset/LEGALNER-POS-PREV-NEXT-200.csv')

In [33]:
df_lama = df_grouped[["word", "tag"]]
df_lama = df_lama.rename(columns={'word': 'text','tag':'text-tags'})
df_lama['text'] = df_lama['text'].apply(lambda x: x.lower().split())
df_lama['text-tags'] = df_lama['text-tags'].apply(lambda x: x.split())
df_lama

,text,text-tags
0,"[putusan, nomor, :, 2387, /, pid, ., sus, /, 2...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1,"[putusan, nomor, :, 538, /, pid, ., b, /, 2018...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
2,"[putusan, ., nomor, :, 2280, /, pid, ., b, /, ...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I..."
3,"[putusan, nomor, :, 1107, /, pid, ., sus, /, 2...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
4,"[putusan, nomor, 216, /, pid, ., c, /, 2019, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
...,...,...
102,"[putusan, nomor, :, 724, /, pid, ., sus, /, 20...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
103,"[putusan, nomor, 848, /, pid, ., b, /, 2019, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
104,"[putusan, nomor, :, 538, /, pid, ., b, /, 2014...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
105,"[putusan, pidana, nomor, :, 536, /, pid, ., b,...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I..."
106,"[putusan, no, ., 924, /, pid, ., b, /, 2014, /...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."

## Dataset Baru

In [34]:
load_df_baru = pd.read_csv('/content/drive/MyDrive/NER nlp/Dataset/Dataset Fix/Dataset Pos Tagging/DatasetPos-Baru.csv')
load_df_baru = load_df_baru.fillna(method="ffill")
df_grouped2 = load_df_baru.groupby('doc').agg({
    'sentence': ' '.join,
    'word': ' '.join,
    'pos': ' '.join,
    'prev': ' '.join,
    'next': ' '.join,
    'tag': ' '.join
}).reset_index()

In [35]:
df_baru = df_grouped2[["word", "tag"]]
df_baru = df_baru.rename(columns={'word': 'text','tag':'text-tags'})
df_baru['text'] = df_baru['text'].apply(lambda x: x.lower().split())
df_baru['text-tags'] = df_baru['text-tags'].apply(lambda x: x.split())
df_baru

,text,text-tags
0,"[putusan, nomor, 325, /, pid, ., b, /, 2015, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
1,"[putusan, no, ., 41, /, pid, ., b, /, 2013, /,...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
2,"[putusan, nomor, :, 212, /, pid, ., b, /, 2013...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
3,"[pid, ., i, ., a, ., 3, putusan, nomor, 156, /...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_..."
4,"[putusan, nomor, :, 390, /, pid, ., sus, ., /,...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
...,...,...
988,"[putusan, nomor, 826, /, pid, ., b, /, 2016, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
989,"[dir1ektori, putusan, mahkamah, agung, republi...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_..."
990,"[putusan, nomor, :, 376, /, pid, ., b, /, 2012...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
991,"[putusan, nomor, :, 79, /, pid, ., sus, /, 201...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
992,"[putusan, nomor, :, 121, /, pid, ., b, /, 2010...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."

In [8]:
# load_df = pd.read_json('/content/drive/MyDrive/NER nlp/Dataset/all.json', lines=True)
# load_df

### Ambil Kolom text dan text-tags

In [9]:
# df = load_df[["text", "text-tags"]]
# df

### Modifikasi text-tags

In [10]:
# def correct_label(df):
#   for i, row in df.iterrows():
#     df.at[i, "text-tags"] = [tag.replace(' ', '_').replace('-', '_').upper() for tag in row["text-tags"]]
#   return df

# correct_label(df)

### Menampilkan Text unik pada text-tags

In [11]:
# labels = [label for label in df['text-tags'].values.tolist()]

# unique_labels = set()

# for lb in labels:
#   [unique_labels.add(i) for i in lb if i not in unique_labels]

# print(sorted(unique_labels))

### Convert Bentuk Label

In [12]:
# label_converter = {
#     'B_NOMOR_PUTUSAN' : 'B_VERN',
#     'B_NAMA_TERDAKWA' : 'B_DEFN',
#     'B_MELANGGAR_UU_(TUNTUTAN)' : 'B_ARTV',
#     'B_PUTUSAN_HUKUMAN' : 'B_PUNI',
#     'B_TANGGAL_PUTUSAN' : 'B_TIMV',
#     'B_NAMA_HAKIM_KETUA' : 'B_JUDP',
#     'B_NAMA_HAKIM_ANGGOTA' : 'B_JUDG',
#     'B_NAMA_PANITERA' : 'B_REGI',
#     'B_NAMA_JAKSA' : 'B_PROS',
#     'B_NAMA_PENGACARA' : 'B_ADVO',
#     'B_JENIS_DAKWAAN' : 'B_CRIA',
#     'B_TUNTUTAN_HUKUMAN' : 'B_PENA',

#     'I_NOMOR_PUTUSAN' : 'I_VERN',
#     'I_NAMA_TERDAKWA' : 'I_DEFN',
#     'I_MELANGGAR_UU_(TUNTUTAN)' : 'I_ARTV',
#     'I_PUTUSAN_HUKUMAN' : 'I_PUNI',
#     'I_TANGGAL_PUTUSAN' : 'I_TIMV',
#     'I_NAMA_HAKIM_KETUA' : 'I_JUDP',
#     'I_NAMA_HAKIM_ANGGOTA' : 'I_JUDG',
#     'I_NAMA_PANITERA' : 'I_REGI',
#     'I_NAMA_JAKSA' : 'I_PROS',
#     'I_NAMA_PENGACARA' : 'I_ADVO',
#     'I_JENIS_DAKWAAN' : 'I_CRIA',
#     'I_TUNTUTAN_HUKUMAN' : 'I_PENA',
# }

### Replace label ke text-tags

In [13]:
# def replace_label(df, new_label):
#   for i, row in df.iterrows():
#     temp = []
#     for tag in row["text-tags"]:
#       if tag in list(new_label.keys()):
#         temp.append(new_label[tag])
#       else:
#         temp.append("O")
#     df.at[i, "text-tags"] = temp
#   return df

# replace_label(df, label_converter)

## Join Dataset

In [36]:
merge_df = pd.concat([df_lama, df_baru],ignore_index=True)
merge_df

,text,text-tags
0,"[putusan, nomor, :, 2387, /, pid, ., sus, /, 2...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1,"[putusan, nomor, :, 538, /, pid, ., b, /, 2018...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
2,"[putusan, ., nomor, :, 2280, /, pid, ., b, /, ...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I..."
3,"[putusan, nomor, :, 1107, /, pid, ., sus, /, 2...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
4,"[putusan, nomor, 216, /, pid, ., c, /, 2019, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
...,...,...
1095,"[putusan, nomor, 826, /, pid, ., b, /, 2016, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
1096,"[dir1ektori, putusan, mahkamah, agung, republi...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_..."
1097,"[putusan, nomor, :, 376, /, pid, ., b, /, 2012...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1098,"[putusan, nomor, :, 79, /, pid, ., sus, /, 201...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1099,"[putusan, nomor, :, 121, /, pid, ., b, /, 2010...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."

### Cleaning Dataset

In [37]:
# def cleaning_text(dataset):
#   for i, row in tqdm.tqdm(dataset.iterrows(), total=1len(dataset), desc="Cleaning text"):
#     dataset.at[i, "word"] = [word.replace("\ufeff", "") for word in row["word"]]
#     data_word,data_pos,data_prev,data_next, data_tag = zip(*[(word, pos,prev,next,tag) for word, pos,prev,next,tag in zip(row["word"],row["pos"],row["prev"],row["next"], row["tag"]) if word.strip() != ''])
#     dataset.at[i, "word"] = list(data_word)
#     dataset.at[i, "pos"] = list(data_pos)
#     dataset.at[i, "prev"] = list(data_prev)
#     dataset.at[i, "next"] = list(data_next)
#     dataset.at[i, "tag"] = list(data_tag)

#   return dataset

# cleaning_text(merge_df)
def cleaning_text(dataset):
  for i, row in tqdm.tqdm(dataset.iterrows(), total=len(dataset), desc="Cleaning text"):
    dataset.at[i, "text"] = [word.replace("\ufeff", "") for word in row["text"]]
    data_text, data_tag = zip(*[(token, label) for token, label in zip(row["text"], row["text-tags"]) if token.strip() != ''])
    dataset.at[i, "text"] = list(data_text)
    dataset.at[i, "text-tags"] = list(data_tag)

  return dataset

cleaning_text(merge_df)

Cleaning text: 100%|██████████| 1100/1100 [01:21<00:00, 13.48it/s]

,text,text-tags
0,"[putusan, nomor, :, 2387, /, pid, ., sus, /, 2...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1,"[putusan, nomor, :, 538, /, pid, ., b, /, 2018...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
2,"[putusan, ., nomor, :, 2280, /, pid, ., b, /, ...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I..."
3,"[putusan, nomor, :, 1107, /, pid, ., sus, /, 2...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
4,"[putusan, nomor, 216, /, pid, ., c, /, 2019, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
...,...,...
1095,"[putusan, nomor, 826, /, pid, ., b, /, 2016, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
1096,"[dir1ektori, putusan, mahkamah, agung, republi...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_..."
1097,"[putusan, nomor, :, 376, /, pid, ., b, /, 2012...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1098,"[putusan, nomor, :, 79, /, pid, ., sus, /, 201...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1099,"[putusan, nomor, :, 121, /, pid, ., b, /, 2010...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."

### Split token

In [38]:
def split_token(dataset):
  for i, row in tqdm.tqdm(dataset.iterrows(), total=len(dataset), desc="Processing rows"):
    for index, (text, tag) in enumerate(zip(row["text"], row["text-tags"])):
      if tag != "O":
        token = re.findall(r'[^\/,\.():;]+|[\/\.,():;]', text)
        add_label = []
        for i in range(len(token)):
          if 'B' in tag and not add_label:
            add_label.append(tag)
          else:
            if token[i] != ';':
              add_label.append(tag.replace('B', 'I'))
            else:
              add_label.append('O')

        del row["text"][index]
        del row["text-tags"][index]
        row["text"][index:index] = token
        row["text-tags"][index:index] = add_label
      else:
        token = re.findall(r'[^\/,\.():;]+|[\/\.,():;]', text)
        add_label = []
        for i in range(len(token)):
          add_label.append('O')

        del row["text"][index]
        del row["text-tags"][index]
        row["text"][index:index] = token
        row["text-tags"][index:index] = add_label
  return dataset
split_token(merge_df)
# def split_token(dataset):
#   for i, row in tqdm.tqdm(dataset.iterrows(), total=len(dataset), desc="Processing rows"):
#     for index, (text, tag) in enumerate(zip(row["word"], row["tag"])):
#       if tag != "O":
#         token = re.findall(r'[^\/,\.():;]+|[\/\.,():;]', text)
#         add_label = []
#         for i in range(len(token)):
#           if 'B' in tag and not add_label:
#             add_label.append(tag)
#           else:
#             if token[i] != ';':
#               add_label.append(tag.replace('B', 'I'))
#             else:
#               add_label.append('O')

#         del row["word"][index]
#         del row["tag"][index]
#         row["word"][index:index] = token
#         row["tag"][index:index] = add_label
#       else:
#         token = re.findall(r'[^\/,\.():;]+|[\/\.,():;]', text)
#         add_label = []
#         for i in range(len(token)):
#           add_label.append('O')

#         del row["word"][index]
#         del row["tag"][index]
#         row["word"][index:index] = token
#         row["tag"][index:index] = add_label
#   return dataset
# split_token(merge_df)

Processing rows: 100%|██████████| 1100/1100 [03:24<00:00,  5.39it/s]

,text,text-tags
0,"[putusan, nomor, :, 2387, /, pid, ., sus, /, 2...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1,"[putusan, nomor, :, 538, /, pid, ., b, /, 2018...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
2,"[putusan, ., nomor, :, 2280, /, pid, ., b, /, ...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I..."
3,"[putusan, nomor, :, 1107, /, pid, ., sus, /, 2...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
4,"[putusan, nomor, 216, /, pid, ., c, /, 2019, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
...,...,...
1095,"[putusan, nomor, 826, /, pid, ., b, /, 2016, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,..."
1096,"[dir1ektori, putusan, mahkamah, agung, republi...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_..."
1097,"[putusan, nomor, :, 376, /, pid, ., b, /, 2012...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1098,"[putusan, nomor, :, 79, /, pid, ., sus, /, 201...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."
1099,"[putusan, nomor, :, 121, /, pid, ., b, /, 2010...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE..."

### Menambahkan kolom Doc

In [30]:
doc_column = ['doc: ' + str(i + 1) for i in range(len(merge_df))]
merge_df['doc'] = doc_column
merge_df

,word,pos,prev,next,tag,doc
0,"[putusan, nomor, :, 2387, /, pid, ., sus, /, 2...","[NOUN, NOUN, PUNCT, NUM, SYM, PROPN, PUNCT, PR...","[,, putusan, nomor, :, 2387, /, pid, ., sus, /...","[nomor, :, 2387, /, pid, ., sus, /, 2013, /, p...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1
1,"[putusan, nomor, :, 538, /, pid, ., b, /, 2018...","[NOUN, NOUN, PUNCT, NUM, SYM, PROPN, PUNCT, PR...","[., putusan, nomor, :, 538, /, pid, ., b, /, 2...","[nomor, :, 538, /, pid, ., b, /, 2018, /, pn, ...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 2
2,"[putusan, ., nomor, :, 2280, /, pid, ., b, /, ...","[PROPN, PUNCT, PROPN, PUNCT, NUM, PUNCT, PROPN...","[sh, putusan, ., nomor, :, 2280, /, pid, ., b,...","[., nomor, :, 2280, /, pid, ., b, /, 2012, /, ...","[O, O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I...",doc: 3
3,"[putusan, nomor, :, 1107, /, pid, ., sus, /, 2...","[NOUN, NOUN, PUNCT, NUM, SYM, PROPN, PUNCT, PR...","[., putusan, nomor, :, 1107, /, pid, ., sus, /...","[nomor, :, 1107, /, pid, ., sus, /, 2017, /, p...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 4
4,"[putusan, nomor, 216, /, pid, ., c, /, 2019, /...","[NOUN, NOUN, NUM, SYM, PROPN, PUNCT, PROPN, SY...","[., putusan, nomor, 216, /, pid, ., c, /, 2019...","[nomor, 216, /, pid, ., c, /, 2019, /, pn, jkt...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 5
...,...,...,...,...,...,...
1095,"[putusan, nomor, 826, /, pid, ., b, /, 2016, /...","[NOUN, NOUN, NUM, PUNCT, PROPN, PUNCT, PROPN, ...","[., putusan, nomor, 826, /, pid, ., b, /, 2016...","[nomor, 826, /, pid, ., b, /, 2016, /, pn, sda...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1096
1096,"[dir1ektori, putusan, mahkamah, agung, republi...","[PUNCT, NOUN, NOUN, NOUN, NOUN, PROPN, NOUN, N...","[11, dir1ektori, putusan, mahkamah, agung, rep...","[putusan, mahkamah, agung, republik, indonesia...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_...",doc: 1097
1097,"[putusan, nomor, :, 376, /, pid, ., b, /, 2012...","[NOUN, NOUN, PUNCT, NUM, PUNCT, PROPN, PUNCT, ...","[., putusan, nomor, :, 376, /, pid, ., b, /, 2...","[nomor, :, 376, /, pid, ., b, /, 2012, /, pn, ...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1098
1098,"[putusan, nomor, :, 79, /, pid, ., sus, /, 201...","[NOUN, NOUN, PUNCT, NUM, PUNCT, PROPN, PUNCT, ...","[., putusan, nomor, :, 79, /, pid, ., sus, /, ...","[nomor, :, 79, /, pid, ., sus, /, 2015, /, pn,...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1099
1099,"[putusan, nomor, :, 121, /, pid, ., b, /, 2010...","[NOUN, NOUN, PUNCT, NUM, PUNCT, PROPN, PUNCT, ...","[., putusan, nomor, :, 121, /, pid, ., b, /, 2...","[nomor, :, 121, /, pid, ., b, /, 2010, /, pn, ...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1100

#### Catatan
sentence berdasarkan ; dan tetap di tokenisasi jangan di gabung kan lagi (bentuk tetap dengan koma)

### Split data per Sentence

#### Versi Baru

In [31]:
new_rows = []
for index, row in merge_df.iterrows():
    sentences = ' '.join(row['word']).split(';')
    for sentence in sentences:
        new_rows.append({
            'word': sentence.split(),
            'pos': row['pos'],
            'prev': row['prev'],
            'next': row['next'],
            'tag': row['tag'],
            'doc': row['doc']
        })
new_df = pd.DataFrame(new_rows)
new_df
# new_rows = []
# for index, row in merge_df.iterrows():
#     sentences = ' '.join(row['text']).split(';')
#     for sentence in sentences:
#         new_rows.append({
#             'text': sentence.split(),
#             'text-tags': row['text-tags'],
#             'doc': row['doc']
#         })
# new_df = pd.DataFrame(new_rows)
# new_df

,word,pos,prev,next,tag,doc
0,"[putusan, nomor, :, 2387, /, pid, ., sus, /, 2...","[NOUN, NOUN, PUNCT, NUM, SYM, PROPN, PUNCT, PR...","[,, putusan, nomor, :, 2387, /, pid, ., sus, /...","[nomor, :, 2387, /, pid, ., sus, /, 2013, /, p...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1
1,"[tempat, lahir, :, jakarta]","[NOUN, NOUN, PUNCT, NUM, SYM, PROPN, PUNCT, PR...","[,, putusan, nomor, :, 2387, /, pid, ., sus, /...","[nomor, :, 2387, /, pid, ., sus, /, 2013, /, p...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1
2,"[umur, /, tanggal, lahir, :, 35, tahun, /, 6, ...","[NOUN, NOUN, PUNCT, NUM, SYM, PROPN, PUNCT, PR...","[,, putusan, nomor, :, 2387, /, pid, ., sus, /...","[nomor, :, 2387, /, pid, ., sus, /, 2013, /, p...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1
3,"[jenis, kelamin, :, laki, -, laki]","[NOUN, NOUN, PUNCT, NUM, SYM, PROPN, PUNCT, PR...","[,, putusan, nomor, :, 2387, /, pid, ., sus, /...","[nomor, :, 2387, /, pid, ., sus, /, 2013, /, p...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1
4,"[kebangsaan, :, indonesia]","[NOUN, NOUN, PUNCT, NUM, SYM, PROPN, PUNCT, PR...","[,, putusan, nomor, :, 2387, /, pid, ., sus, /...","[nomor, :, 2387, /, pid, ., sus, /, 2013, /, p...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1
...,...,...,...,...,...,...
21103,"[putusan, nomor, 826, /, pid, ., b, /, 2016, /...","[NOUN, NOUN, NUM, PUNCT, PROPN, PUNCT, PROPN, ...","[., putusan, nomor, 826, /, pid, ., b, /, 2016...","[nomor, 826, /, pid, ., b, /, 2016, /, pn, sda...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1096
21104,"[dir1ektori, putusan, mahkamah, agung, republi...","[PUNCT, NOUN, NOUN, NOUN, NOUN, PROPN, NOUN, N...","[11, dir1ektori, putusan, mahkamah, agung, rep...","[putusan, mahkamah, agung, republik, indonesia...","[O, O, O, O, O, O, O, O, O, B_VERN, I_VERN, I_...",doc: 1097
21105,"[putusan, nomor, :, 376, /, pid, ., b, /, 2012...","[NOUN, NOUN, PUNCT, NUM, PUNCT, PROPN, PUNCT, ...","[., putusan, nomor, :, 376, /, pid, ., b, /, 2...","[nomor, :, 376, /, pid, ., b, /, 2012, /, pn, ...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1098
21106,"[putusan, nomor, :, 79, /, pid, ., sus, /, 201...","[NOUN, NOUN, PUNCT, NUM, PUNCT, PROPN, PUNCT, ...","[., putusan, nomor, :, 79, /, pid, ., sus, /, ...","[nomor, :, 79, /, pid, ., sus, /, 2015, /, pn,...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1099
21107,"[putusan, nomor, :, 121, /, pid, ., b, /, 2010...","[NOUN, NOUN, PUNCT, NUM, PUNCT, PROPN, PUNCT, ...","[., putusan, nomor, :, 121, /, pid, ., b, /, 2...","[nomor, :, 121, /, pid, ., b, /, 2010, /, pn, ...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1100

#### Versi Lama

In [ ]:
# def convertLSTM(dataset):
#     new_dataset = pd.DataFrame(columns=["text", "text-tags", "doc"])  # Menambahkan kolom 'doc'
#     for i, row in tqdm.tqdm(dataset.iterrows(), total=len(dataset), desc="Converting to LSTM format"):
#         text = ""
#         tag = ""
#         doc = row['doc']  # Menyimpan nilai kolom 'doc' dari dataset asli
#         for index, (word, l) in enumerate(zip(row["text"], row["text-tags"])):
#             if word != ';':
#                 text += word + " "
#                 tag += l + " "
#             else:
#                 text += word + " "
#                 tag += l + " "
#                 # Membuat DataFrame baru dari text, tag, dan doc
#                 data = pd.DataFrame({"text": [text.strip()], "text-tags": [tag.strip()], "doc": [doc]})

#                 # Menambahkan DataFrame baru ke dataset baru
#                 new_dataset = pd.concat([new_dataset, data], ignore_index=True)

#                 text = ""
#                 tag = ""

#     return new_dataset

# new_df_sentences = convertLSTM(merge_df)
# new_df_sentences

Converting to LSTM format: 100%|██████████| 1100/1100 [13:19<00:00,  1.38it/s]

,text,text-tags,doc
0,putusan nomor 325 / pid . b / 2015 / pn bwi de...,O O B_VERN I_VERN I_VERN I_VERN I_VERN I_VERN ...,doc: 1
1,tempat lahir : banyuwangi ;,O O O O O,doc: 1
2,umur / tanggal lahir : 35 tahun / 2 maret 1979 ;,O O O O O O O O O O O O,doc: 1
3,jenis kelamin : laki-laki ;,O O O O O,doc: 1
4,kebangsaan : indonesia ;,O O O O,doc: 1
...,...,...,...
139289,mengadili menyatakan terdakwa : yayat rukayat ...,O O O O B_DEFN I_DEFN I_DEFN I_DEFN I_DEFN O O...,doc: 1100
139290,menjatuhkan pidana kepada terdakwa oleh karena...,O O O O O O O O O O O O B_PUNI I_PUNI I_PUNI I...,doc: 1100
139291,menetapkan masa penahanan yang telah dijalani ...,O O O O O O O O O O O O O O,doc: 1100
139292,menetapkan terdakwa tetap berada dalam tahanan ;,O O O O O O O,doc: 1100
139293,membebankan terdakwa untuk membayar biaya perk...,O O O O O O O O O O O O O O O O O O O,doc: 1100

### Menambahkan kolom Sentence

In [ ]:
new_df['sentence'] = new_df.index.map(lambda x: f'sentence: {x + 1:06}')
new_df

,text,text-tags,doc,sentence
0,"[putusan, nomor, 325, /, pid, ., b, /, 2015, /...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1,sentence: 000001
1,"[tempat, lahir, :, banyuwangi]","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1,sentence: 000002
2,"[umur, /, tanggal, lahir, :, 35, tahun, /, 2, ...","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1,sentence: 000003
3,"[jenis, kelamin, :, laki-laki]","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1,sentence: 000004
4,"[kebangsaan, :, indonesia]","[O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VERN,...",doc: 1,sentence: 000005
...,...,...,...,...
140389,"[menjatuhkan, pidana, kepada, terdakwa, oleh, ...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1100,sentence: 140390
140390,"[menetapkan, masa, penahanan, yang, telah, dij...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1100,sentence: 140391
140391,"[menetapkan, terdakwa, tetap, berada, dalam, t...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1100,sentence: 140392
140392,"[membebankan, terdakwa, untuk, membayar, biaya...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1100,sentence: 140393
140393,"[demikianlah, diputuskan, dalam, rapat, permus...","[O, O, O, B_VERN, I_VERN, I_VERN, I_VERN, I_VE...",doc: 1100,sentence: 140394

### Tokenisasi per kata

### Versi Baru

In [ ]:
tokens = []
tags = []
docs = []
sentences = []
for i, row in new_df.iterrows():
    for token, tag in zip(row['text'], row['text-tags']):
        tokens.append(token)
        tags.append(tag)
        docs.append(row['doc'])
        sentences.append(row['sentence'])
tokenized_df = pd.DataFrame({
    'text': tokens,
    'text-tags': tags,
    'doc': docs,
    'sentence': sentences
})
tokenized_df

             text text-tags        doc          sentence
0         putusan         O     doc: 1  sentence: 000001
1           nomor         O     doc: 1  sentence: 000001
2             325    B_VERN     doc: 1  sentence: 000001
3               /    I_VERN     doc: 1  sentence: 000001
4             pid    I_VERN     doc: 1  sentence: 000001
...           ...       ...        ...               ...
7662673  penuntut         O  doc: 1100  sentence: 140394
7662674      umum         O  doc: 1100  sentence: 140394
7662675       dan         O  doc: 1100  sentence: 140394
7662676  terdakwa         O  doc: 1100  sentence: 140394
7662677         .         O  doc: 1100  sentence: 140394

[7662678 rows x 4 columns]

### Versi Lama

In [ ]:
# tokens = []
# tags = []
# docs = []
# sentence = []

# for i, row in new_df_sentences.iterrows():
#     text = row['text'].split()  # Memisahkan teks berdasarkan spasi
#     text_tags = row['text-tags'].split()  # Memisahkan tag berdasarkan spasi

#     # Menambahkan token, tag, doc, dan sentences berdasarkan tokenisasi
#     for token, tag in zip(text, text_tags):
#         tokens.append(token)
#         tags.append(tag)
#         docs.append(row['doc'])
#         sentence.append(row['sentence'])

# # Membuat DataFrame dari hasil tokenisasi
# tokenized_df = pd.DataFrame({
#     'text': tokens,
#     'text-tags': tags,
#     'doc': docs,
#     'sentence': sentence
# })

# tokenized_df

## Menambahkan Kolom Prev dan Next

In [ ]:
tokenized_df['prev'] = tokenized_df['text'].shift(1)
tokenized_df['next'] = tokenized_df['text'].shift(-1)
tokenized_df['prev'].fillna('.', inplace=True)
tokenized_df['next'].fillna('.', inplace=True)

In [ ]:
tokenized_df

             text text-tags        doc          sentence      prev      next
0         putusan         O     doc: 1  sentence: 000001         .     nomor
1           nomor         O     doc: 1  sentence: 000001   putusan       325
2             325    B_VERN     doc: 1  sentence: 000001     nomor         /
3               /    I_VERN     doc: 1  sentence: 000001       325       pid
4             pid    I_VERN     doc: 1  sentence: 000001         /         .
...           ...       ...        ...               ...       ...       ...
7662673  penuntut         O  doc: 1100  sentence: 140394         .      umum
7662674      umum         O  doc: 1100  sentence: 140394  penuntut       dan
7662675       dan         O  doc: 1100  sentence: 140394      umum  terdakwa
7662676  terdakwa         O  doc: 1100  sentence: 140394       dan         .
7662677         .         O  doc: 1100  sentence: 140394  terdakwa         .

[7662678 rows x 6 columns]

In [ ]:
proces_data = tokenized_df.rename(columns={'text': 'word', 'text-tags': 'tag'}).reindex(columns=['doc','sentence', 'word', 'prev', 'next', 'tag'])
proces_data

               doc          sentence      word      prev      next     tag
0           doc: 1  sentence: 000001   putusan         .     nomor       O
1           doc: 1  sentence: 000001     nomor   putusan       325       O
2           doc: 1  sentence: 000001       325     nomor         /  B_VERN
3           doc: 1  sentence: 000001         /       325       pid  I_VERN
4           doc: 1  sentence: 000001       pid         /         .  I_VERN
...            ...               ...       ...       ...       ...     ...
7662673  doc: 1100  sentence: 140394  penuntut         .      umum       O
7662674  doc: 1100  sentence: 140394      umum  penuntut       dan       O
7662675  doc: 1100  sentence: 140394       dan      umum  terdakwa       O
7662676  doc: 1100  sentence: 140394  terdakwa       dan         .       O
7662677  doc: 1100  sentence: 140394         .  terdakwa         .       O

[7662678 rows x 6 columns]

In [ ]:
proces_data.to_csv('Dataset-Merge.csv', index=False)

## Catatan
gunakan pos tagging dengan flair