In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm
import pandas as pd
import gdown
import re

In [63]:
gdown.download(f'https://drive.google.com/uc?id=1-BypPfJHAVa_9tsh1aWjnAfJeqds4nJL', "Dataset Pidana Umum Sampang.csv", quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1-BypPfJHAVa_9tsh1aWjnAfJeqds4nJL
To: /content/Dataset Pidana Umum Sampang.csv
100%|██████████| 5.16M/5.16M [00:00<00:00, 128MB/s]

'Dataset Pidana Umum Sampang.csv'

In [64]:
df = pd.read_csv("Dataset Pidana Umum Sampang.csv")
df

,url_page,penuntut_umum,terdakwa,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,lembaga_peradilan,...,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,abstrak,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"SUHARTO, S.H.","DR. H. FAUZAN ADIMA, S.H.,M.Kn. Bin H. RIDHOI,...",189/Pid.B/2023/PN Spg,Pertama,Pidana Umum,Pencemaran Nama Baik,2024,10 Oktober 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Dr. H. FAUZAN A...,18 Januari 2024,18 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,189_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 189/Pid.B/2023/PN Spg\nDEMI KEA...
1,https://putusan3.mahkamahagung.go.id/direktori...,"1.Indah Asry Pinatasari, S.H. 2.HERONIKA SETIA...",AHMAD YASIN Bin. JAMIN (alm),221/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,15 Nopember 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa AHMAD YASIN Bin...,10 Januari 2024,10 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,221_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 221/Pid.B/2023/PN Spg\nDEMI KEA...
2,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY, S.H. 2.SUHARTO, S.H.",ROHIM BIN DULLOH,222/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,15 Nopember 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ROHIM Bin DULLO...,10 Januari 2024,10 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,222_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 222/Pid.B/2023/PN Spg\nDEMI KEA...
3,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY, S.H. 2.MOCH. HASAN, S.H.",MOH. ALIF FARIS HAKIKI bin. MUHAMMAD SYAFI'I,227/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,23 Nopember 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MOH. ALIF FARIS...,3 Januari 2024,3 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,227_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 227/Pid.B/2023/PN Spg\nDEMI KEA...
4,https://putusan3.mahkamahagung.go.id/direktori...,"ANANG SETIAWAN, S.H.",FAIZ BIN NU'AH,197/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,17 Oktober 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa FAIZ Bin NU?AH ...,3 Januari 2024,3 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,197_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 197/Pid.B/2023/PN Spg\nDEMI KEA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY,SH 2.TUNJUNG SUGHANDIKO,SH",1.H.IMAM WAHYUDI 2.R.SUHARTONO,247/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Penipuan,Penipuan,2022,17 Nopember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa I H. IMAM WAHYU...,3 Februari 2022,3 Februari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,247_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 247/Pid.B/2022/PN Spg \n \nDEM...
118,https://putusan3.mahkamahagung.go.id/direktori...,"1.MURDIYANTA SETYA BUDI,S.H 2.SUHARTO, SH",SYARIF HIDAYATULLAH Bin ASBIN,246/Pid.B/2021/PN Spg,Pertama,Pidana Umum,Kejahatan terhadap Nyawa,2022,17 Nopember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa SYARIF HIDAYATU...,3 Februari 2022,3 Februari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,246_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 246/Pid.Sus/2022/PN Spg \n \nD...
119,https://putusan3.mahkamahagung.go.id/direktori...,"1.MOCH. HASAN, S.H. 2.AKHMAD MISJOTO, S.H.",MUHAMMAT LUTFI,265/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Penadahan,PenadahanPenerbitandan Pencetakan,2022,6 Desember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MUHAMMAT LUTFI ...,27 Januari 2022,27 Januari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,265_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 265/Pid.Sus/2022/PN Spg \n \nD...
120,https://putusan3.mahkamahagung.go.id/direktori...,"1.EKO WINARNO.SH 2.HERONIKA SETIAWATY,SH",CONG KENEK Alias LONIN Bin alm MARUDEH,268/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2022,8 Desember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa CONG KENEK Alia...,25 Januari 2022,25 Januari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,268_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 268/Pid.B/2022/PN Spg \n \nDEM...
121,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY,SH 2.SUHARTO, SH",MARDAN Bin JU'I,261/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2022,30 Nopember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan Terdakwa MARDAN Bin JU?I ...,18 Januari 2022,18 Januari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,261_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 261/Pid.B/2022/PN Spg \n \nDEM...

In [65]:
df_200 = df.iloc[0:200]
df_200

,url_page,penuntut_umum,terdakwa,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,lembaga_peradilan,...,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,abstrak,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"SUHARTO, S.H.","DR. H. FAUZAN ADIMA, S.H.,M.Kn. Bin H. RIDHOI,...",189/Pid.B/2023/PN Spg,Pertama,Pidana Umum,Pencemaran Nama Baik,2024,10 Oktober 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Dr. H. FAUZAN A...,18 Januari 2024,18 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,189_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 189/Pid.B/2023/PN Spg\nDEMI KEA...
1,https://putusan3.mahkamahagung.go.id/direktori...,"1.Indah Asry Pinatasari, S.H. 2.HERONIKA SETIA...",AHMAD YASIN Bin. JAMIN (alm),221/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,15 Nopember 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa AHMAD YASIN Bin...,10 Januari 2024,10 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,221_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 221/Pid.B/2023/PN Spg\nDEMI KEA...
2,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY, S.H. 2.SUHARTO, S.H.",ROHIM BIN DULLOH,222/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,15 Nopember 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ROHIM Bin DULLO...,10 Januari 2024,10 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,222_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 222/Pid.B/2023/PN Spg\nDEMI KEA...
3,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY, S.H. 2.MOCH. HASAN, S.H.",MOH. ALIF FARIS HAKIKI bin. MUHAMMAD SYAFI'I,227/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,23 Nopember 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MOH. ALIF FARIS...,3 Januari 2024,3 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,227_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 227/Pid.B/2023/PN Spg\nDEMI KEA...
4,https://putusan3.mahkamahagung.go.id/direktori...,"ANANG SETIAWAN, S.H.",FAIZ BIN NU'AH,197/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,17 Oktober 2023,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa FAIZ Bin NU?AH ...,3 Januari 2024,3 Januari 2024,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,197_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 197/Pid.B/2023/PN Spg\nDEMI KEA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY,SH 2.TUNJUNG SUGHANDIKO,SH",1.H.IMAM WAHYUDI 2.R.SUHARTONO,247/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Penipuan,Penipuan,2022,17 Nopember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa I H. IMAM WAHYU...,3 Februari 2022,3 Februari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,247_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 247/Pid.B/2022/PN Spg \n \nDEM...
118,https://putusan3.mahkamahagung.go.id/direktori...,"1.MURDIYANTA SETYA BUDI,S.H 2.SUHARTO, SH",SYARIF HIDAYATULLAH Bin ASBIN,246/Pid.B/2021/PN Spg,Pertama,Pidana Umum,Kejahatan terhadap Nyawa,2022,17 Nopember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa SYARIF HIDAYATU...,3 Februari 2022,3 Februari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,246_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 246/Pid.Sus/2022/PN Spg \n \nD...
119,https://putusan3.mahkamahagung.go.id/direktori...,"1.MOCH. HASAN, S.H. 2.AKHMAD MISJOTO, S.H.",MUHAMMAT LUTFI,265/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Penadahan,PenadahanPenerbitandan Pencetakan,2022,6 Desember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MUHAMMAT LUTFI ...,27 Januari 2022,27 Januari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,265_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 265/Pid.Sus/2022/PN Spg \n \nD...
120,https://putusan3.mahkamahagung.go.id/direktori...,"1.EKO WINARNO.SH 2.HERONIKA SETIAWATY,SH",CONG KENEK Alias LONIN Bin alm MARUDEH,268/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2022,8 Desember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa CONG KENEK Alia...,25 Januari 2022,25 Januari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,268_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 268/Pid.B/2022/PN Spg \n \nDEM...
121,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY,SH 2.SUHARTO, SH",MARDAN Bin JU'I,261/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2022,30 Nopember 2021,PN SAMPANG,...,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan Terdakwa MARDAN Bin JU?I ...,18 Januari 2022,18 Januari 2022,—,NaN,https://putusan3.mahkamahagung.go.id/direktori...,261_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 261/Pid.B/2022/PN Spg \n \nDEM...

In [66]:
df_200.isnull().sum()

url_page                     0
penuntut_umum                0
terdakwa                     0
nomor                        0
tingkat_proses               0
klasifikasi                  0
kata_kunci                   0
tahun                        0
tanggal_register             0
lembaga_peradilan            0
jenis_lembaga_peradilan      0
hakim_ketua                  0
hakim_anggota                0
panitera                     0
amar                         0
amar_lainnya                 0
catatan_amar                 0
tanggal_musyawarah           0
tanggal_dibacakan            0
kaidah                       0
abstrak                    122
url_pdf                      0
nama_file                    0
content                      0
dtype: int64

In [67]:
df_200 = df_200.drop(["abstrak"], axis=1)

In [68]:
df_200

,url_page,penuntut_umum,terdakwa,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,lembaga_peradilan,...,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"SUHARTO, S.H.","DR. H. FAUZAN ADIMA, S.H.,M.Kn. Bin H. RIDHOI,...",189/Pid.B/2023/PN Spg,Pertama,Pidana Umum,Pencemaran Nama Baik,2024,10 Oktober 2023,PN SAMPANG,...,Panitera Pengganti Andy Risal Gunawan,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Dr. H. FAUZAN A...,18 Januari 2024,18 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,189_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 189/Pid.B/2023/PN Spg\nDEMI KEA...
1,https://putusan3.mahkamahagung.go.id/direktori...,"1.Indah Asry Pinatasari, S.H. 2.HERONIKA SETIA...",AHMAD YASIN Bin. JAMIN (alm),221/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,15 Nopember 2023,PN SAMPANG,...,Panitera Pengganti Muhammad Slamet,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa AHMAD YASIN Bin...,10 Januari 2024,10 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,221_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 221/Pid.B/2023/PN Spg\nDEMI KEA...
2,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY, S.H. 2.SUHARTO, S.H.",ROHIM BIN DULLOH,222/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,15 Nopember 2023,PN SAMPANG,...,Panitera Pengganti Andy Risal Gunawan,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ROHIM Bin DULLO...,10 Januari 2024,10 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,222_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 222/Pid.B/2023/PN Spg\nDEMI KEA...
3,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY, S.H. 2.MOCH. HASAN, S.H.",MOH. ALIF FARIS HAKIKI bin. MUHAMMAD SYAFI'I,227/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,23 Nopember 2023,PN SAMPANG,...,Panitera Pengganti: Sucipto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MOH. ALIF FARIS...,3 Januari 2024,3 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,227_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 227/Pid.B/2023/PN Spg\nDEMI KEA...
4,https://putusan3.mahkamahagung.go.id/direktori...,"ANANG SETIAWAN, S.H.",FAIZ BIN NU'AH,197/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,17 Oktober 2023,PN SAMPANG,...,Panitera Pengganti Sahwi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa FAIZ Bin NU?AH ...,3 Januari 2024,3 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,197_Pid.B_2023_PN_Spg.pdf,PUTUSAN\nNomor 197/Pid.B/2023/PN Spg\nDEMI KEA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY,SH 2.TUNJUNG SUGHANDIKO,SH",1.H.IMAM WAHYUDI 2.R.SUHARTONO,247/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Penipuan,Penipuan,2022,17 Nopember 2021,PN SAMPANG,...,Panitera Pengganti Sahwi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa I H. IMAM WAHYU...,3 Februari 2022,3 Februari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,247_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 247/Pid.B/2022/PN Spg \n \nDEM...
118,https://putusan3.mahkamahagung.go.id/direktori...,"1.MURDIYANTA SETYA BUDI,S.H 2.SUHARTO, SH",SYARIF HIDAYATULLAH Bin ASBIN,246/Pid.B/2021/PN Spg,Pertama,Pidana Umum,Kejahatan terhadap Nyawa,2022,17 Nopember 2021,PN SAMPANG,...,Panitera Pengganti Mohammad Tohir,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa SYARIF HIDAYATU...,3 Februari 2022,3 Februari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,246_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 246/Pid.Sus/2022/PN Spg \n \nD...
119,https://putusan3.mahkamahagung.go.id/direktori...,"1.MOCH. HASAN, S.H. 2.AKHMAD MISJOTO, S.H.",MUHAMMAT LUTFI,265/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Penadahan,PenadahanPenerbitandan Pencetakan,2022,6 Desember 2021,PN SAMPANG,...,Panitera Pengganti Imam Hanafi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MUHAMMAT LUTFI ...,27 Januari 2022,27 Januari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,265_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 265/Pid.Sus/2022/PN Spg \n \nD...
120,https://putusan3.mahkamahagung.go.id/direktori...,"1.EKO WINARNO.SH 2.HERONIKA SETIAWATY,SH",CONG KENEK Alias LONIN Bin alm MARUDEH,268/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2022,8 Desember 2021,PN SAMPANG,...,Panitera Pengganti Mohammad Tohir,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa CONG KENEK Alia...,25 Januari 2022,25 Januari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,268_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 268/Pid.B/2022/PN Spg \n \nDEM...
121,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY,SH 2.SUHARTO, SH",MARDAN Bin JU'I,261/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2022,30 Nopember 2021,PN SAMPANG,...,Panitera Pengganti Sahwi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan Terdakwa MARDAN Bin JU?I ...,18 Januari 2022,18 Januari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,261_Pid.B_2021_PN_Spg.pdf,PUTUSAN \nNomor 261/Pid.B/2022/PN Spg \n \nDEM...

In [69]:
df_200['content']

0      PUTUSAN\nNomor 189/Pid.B/2023/PN Spg\nDEMI KEA...
1      PUTUSAN\nNomor 221/Pid.B/2023/PN Spg\nDEMI KEA...
2      PUTUSAN\nNomor 222/Pid.B/2023/PN Spg\nDEMI KEA...
3      PUTUSAN\nNomor 227/Pid.B/2023/PN Spg\nDEMI KEA...
4      PUTUSAN\nNomor 197/Pid.B/2023/PN Spg\nDEMI KEA...
                             ...
117    PUTUSAN \nNomor 247/Pid.B/2022/PN Spg \n \nDEM...
118    PUTUSAN \nNomor 246/Pid.Sus/2022/PN Spg \n \nD...
119    PUTUSAN \nNomor 265/Pid.Sus/2022/PN Spg \n \nD...
120    PUTUSAN \nNomor 268/Pid.B/2022/PN Spg \n \nDEM...
121    PUTUSAN \nNomor 261/Pid.B/2022/PN Spg \n \nDEM...
Name: content, Length: 122, dtype: object

In [70]:
def clean_text(text):
  text = text.replace("\n", " ")
  text = text.replace("P U T U S A N", "PUTUSAN").replace("P E N E T A P A N", "PENETAPAN")
  text = text.replace('\uf0d8', '')
  text = re.sub(r'\b(\w)\s*\b', r'\1', text)
  text = re.sub(r'(Hal\.\s*\S+(?:\s*\S+)?\.?\s*)|(Halaman \d+(?:\.\d+)?\s*)|Putusan Nomor \S+\s*', '', text)
  text = re.sub(r'^[A-Za-z]+\.\s*', '', text)
  text = re.sub(r'-+', '', text)
  text = re.sub(r'\s+', ' ', text)
  text = re.sub(r'(pn)\.', r'\1 ', text) # Memperbaiki nomor putusan mengganti titik setelah PN dengan spasi
  text = re.sub(r'(\d+)\s*([a-zA-Z]+)\s*(\d+)', r'\1 \2 \3', text) # Memperbaiki format tanggal jika 1 angka di kasih 0
  text = re.sub(r'(\b\d\b)', lambda x: f'0{x.group(1)}', text)
  text = re.sub(r"(\d+)\.(\w)", r"\1. \2", text)
  text = re.sub(r'\b(jkt) (pst)\b', r'\1.\2', text)
  return text

df_200['content'] = df_200["content"].apply(clean_text)

In [71]:
df_200['content']

0      PUTUSAN Nomor 189/Pid.B/2023/PN Spg DEMI KEADI...
1      PUTUSAN Nomor 221/Pid.B/2023/PN Spg DEMI KEADI...
2      PUTUSAN Nomor 222/Pid.B/2023/PN Spg DEMI KEADI...
3      PUTUSAN Nomor 227/Pid.B/2023/PN Spg DEMI KEADI...
4      PUTUSAN Nomor 197/Pid.B/2023/PN Spg DEMI KEADI...
                             ...
117    PUTUSAN Nomor 247/Pid.B/2022/PN Spg DEMI KEADI...
118    PUTUSAN Nomor 246/Pid.Sus/2022/PN Spg DEMI KEA...
119    PUTUSAN Nomor 265/Pid.Sus/2022/PN Spg DEMI KEA...
120    PUTUSAN Nomor 268/Pid.B/2022/PN Spg DEMI KEADI...
121    PUTUSAN Nomor 261/Pid.B/2022/PN Spg DEMI KEADI...
Name: content, Length: 122, dtype: object

In [72]:
df_200

,url_page,penuntut_umum,terdakwa,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,lembaga_peradilan,...,panitera,amar,amar_lainnya,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,url_pdf,nama_file,content
0,https://putusan3.mahkamahagung.go.id/direktori...,"SUHARTO, S.H.","DR. H. FAUZAN ADIMA, S.H.,M.Kn. Bin H. RIDHOI,...",189/Pid.B/2023/PN Spg,Pertama,Pidana Umum,Pencemaran Nama Baik,2024,10 Oktober 2023,PN SAMPANG,...,Panitera Pengganti Andy Risal Gunawan,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa Dr. H. FAUZAN A...,18 Januari 2024,18 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,189_Pid.B_2023_PN_Spg.pdf,PUTUSAN Nomor 189/Pid.B/2023/PN Spg DEMI KEADI...
1,https://putusan3.mahkamahagung.go.id/direktori...,"1.Indah Asry Pinatasari, S.H. 2.HERONIKA SETIA...",AHMAD YASIN Bin. JAMIN (alm),221/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,15 Nopember 2023,PN SAMPANG,...,Panitera Pengganti Muhammad Slamet,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa AHMAD YASIN Bin...,10 Januari 2024,10 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,221_Pid.B_2023_PN_Spg.pdf,PUTUSAN Nomor 221/Pid.B/2023/PN Spg DEMI KEADI...
2,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY, S.H. 2.SUHARTO, S.H.",ROHIM BIN DULLOH,222/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,15 Nopember 2023,PN SAMPANG,...,Panitera Pengganti Andy Risal Gunawan,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa ROHIM Bin DULLO...,10 Januari 2024,10 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,222_Pid.B_2023_PN_Spg.pdf,PUTUSAN Nomor 222/Pid.B/2023/PN Spg DEMI KEADI...
3,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY, S.H. 2.MOCH. HASAN, S.H.",MOH. ALIF FARIS HAKIKI bin. MUHAMMAD SYAFI'I,227/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,23 Nopember 2023,PN SAMPANG,...,Panitera Pengganti: Sucipto,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MOH. ALIF FARIS...,3 Januari 2024,3 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,227_Pid.B_2023_PN_Spg.pdf,PUTUSAN Nomor 227/Pid.B/2023/PN Spg DEMI KEADI...
4,https://putusan3.mahkamahagung.go.id/direktori...,"ANANG SETIAWAN, S.H.",FAIZ BIN NU'AH,197/Pid.B/2023/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2024,17 Oktober 2023,PN SAMPANG,...,Panitera Pengganti Sahwi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa FAIZ Bin NU?AH ...,3 Januari 2024,3 Januari 2024,—,https://putusan3.mahkamahagung.go.id/direktori...,197_Pid.B_2023_PN_Spg.pdf,PUTUSAN Nomor 197/Pid.B/2023/PN Spg DEMI KEADI...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY,SH 2.TUNJUNG SUGHANDIKO,SH",1.H.IMAM WAHYUDI 2.R.SUHARTONO,247/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Penipuan,Penipuan,2022,17 Nopember 2021,PN SAMPANG,...,Panitera Pengganti Sahwi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa I H. IMAM WAHYU...,3 Februari 2022,3 Februari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,247_Pid.B_2021_PN_Spg.pdf,PUTUSAN Nomor 247/Pid.B/2022/PN Spg DEMI KEADI...
118,https://putusan3.mahkamahagung.go.id/direktori...,"1.MURDIYANTA SETYA BUDI,S.H 2.SUHARTO, SH",SYARIF HIDAYATULLAH Bin ASBIN,246/Pid.B/2021/PN Spg,Pertama,Pidana Umum,Kejahatan terhadap Nyawa,2022,17 Nopember 2021,PN SAMPANG,...,Panitera Pengganti Mohammad Tohir,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa SYARIF HIDAYATU...,3 Februari 2022,3 Februari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,246_Pid.B_2021_PN_Spg.pdf,PUTUSAN Nomor 246/Pid.Sus/2022/PN Spg DEMI KEA...
119,https://putusan3.mahkamahagung.go.id/direktori...,"1.MOCH. HASAN, S.H. 2.AKHMAD MISJOTO, S.H.",MUHAMMAT LUTFI,265/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Penadahan,PenadahanPenerbitandan Pencetakan,2022,6 Desember 2021,PN SAMPANG,...,Panitera Pengganti Imam Hanafi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa MUHAMMAT LUTFI ...,27 Januari 2022,27 Januari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,265_Pid.B_2021_PN_Spg.pdf,PUTUSAN Nomor 265/Pid.Sus/2022/PN Spg DEMI KEA...
120,https://putusan3.mahkamahagung.go.id/direktori...,"1.EKO WINARNO.SH 2.HERONIKA SETIAWATY,SH",CONG KENEK Alias LONIN Bin alm MARUDEH,268/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2022,8 Desember 2021,PN SAMPANG,...,Panitera Pengganti Mohammad Tohir,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI: Menyatakan Terdakwa CONG KENEK Alia...,25 Januari 2022,25 Januari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,268_Pid.B_2021_PN_Spg.pdf,PUTUSAN Nomor 268/Pid.B/2022/PN Spg DEMI KEADI...
121,https://putusan3.mahkamahagung.go.id/direktori...,"1.HERONIKA SETIAWATY,SH 2.SUHARTO, SH",MARDAN Bin JU'I,261/Pid.B/2021/PN Spg,Pertama,Pidana Umum \n Pidana Umum Pencurian,Pencurian,2022,30 Nopember 2021,PN SAMPANG,...,Panitera Pengganti Sahwi,Lain-lain,PIDANA PENJARA WAKTU TERTENTU,MENGADILI Menyatakan Terdakwa MARDAN Bin JU?I ...,18 Januari 2022,18 Januari 2022,—,https://putusan3.mahkamahagung.go.id/direktori...,261_Pid.B_2021_PN_Spg.pdf,PUTUSAN Nomor 261/Pid.B/2022/PN Spg DEMI KEADI...

In [73]:
df_200['content']

0      PUTUSAN Nomor 189/Pid.B/2023/PN Spg DEMI KEADI...
1      PUTUSAN Nomor 221/Pid.B/2023/PN Spg DEMI KEADI...
2      PUTUSAN Nomor 222/Pid.B/2023/PN Spg DEMI KEADI...
3      PUTUSAN Nomor 227/Pid.B/2023/PN Spg DEMI KEADI...
4      PUTUSAN Nomor 197/Pid.B/2023/PN Spg DEMI KEADI...
                             ...
117    PUTUSAN Nomor 247/Pid.B/2022/PN Spg DEMI KEADI...
118    PUTUSAN Nomor 246/Pid.Sus/2022/PN Spg DEMI KEA...
119    PUTUSAN Nomor 265/Pid.Sus/2022/PN Spg DEMI KEA...
120    PUTUSAN Nomor 268/Pid.B/2022/PN Spg DEMI KEADI...
121    PUTUSAN Nomor 261/Pid.B/2022/PN Spg DEMI KEADI...
Name: content, Length: 122, dtype: object

In [74]:
def find_similar_sentence(text, target_sentence):
  sentences = text.split(';')  # Pisahkan teks menjadi kalimat-kalimat
  if len(target_sentence.split()) > 1:
    # Gunakan TF-IDF untuk mewakili teks
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform(sentences + [target_sentence])

    # Hitung cosine similarity antara vektor target dan vektor kalimat
    similarity_scores = cosine_similarity(vectors[-1], vectors[:-1])[0]

    # Temukan kalimat dengan similarity tertinggi
    max_similarity_index = similarity_scores.argmax()

    if similarity_scores[max_similarity_index] > 0.0:  # Ubah ambang batas sesuai kebutuhan
        return sentences[max_similarity_index].strip()
    else:
        return None
  else:
    return target_sentence

In [220]:
df_1 = df_200.iloc[2]
df_1

url_page                   https://putusan3.mahkamahagung.go.id/direktori...
penuntut_umum                     1.HERONIKA SETIAWATY, S.H. 2.SUHARTO, S.H.
terdakwa                                                    ROHIM BIN DULLOH
nomor                                                  222/Pid.B/2023/PN Spg
tingkat_proses                                                       Pertama
klasifikasi                            Pidana Umum \n Pidana Umum  Pencurian
kata_kunci                                                         Pencurian
tahun                                                                   2024
tanggal_register                                            15 Nopember 2023
lembaga_peradilan                                                 PN SAMPANG
jenis_lembaga_peradilan                                                   PN
hakim_ketua                                  Hakim Ketua Ratna Mutia Rinanti
hakim_anggota              Hakim Anggota  Ivan Budi Santoso, Um.br Hakim ...
panitera                               Panitera Pengganti Andy Risal Gunawan
amar                                                               Lain-lain
amar_lainnya                                   PIDANA PENJARA WAKTU TERTENTU
catatan_amar               MENGADILI: Menyatakan Terdakwa ROHIM Bin DULLO...
tanggal_musyawarah                                           10 Januari 2024
tanggal_dibacakan                                            10 Januari 2024
kaidah                                                                     —
url_pdf                    https://putusan3.mahkamahagung.go.id/direktori...
nama_file                                          222_Pid.B_2023_PN_Spg.pdf
content                    PUTUSAN Nomor 222/Pid.B/2023/PN Spg DEMI KEADI...
Name: 2, dtype: object

In [236]:
def generate_label(data):
  label = {}
  nomor_putusan = data["nomor"].lower() # cek nomor putusan
  # cek terdakwa
  if any(char.isdigit() for char in data["terdakwa"]): # jika terdakwa lebih dari satu
    terdakwa = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', data["terdakwa"].lower().replace("(alm)", ''))
  else: # jika terdakwa hanya satu
    terdakwa = re.findall(r'(.*?)\s*(?=\d+\.|$)', data["terdakwa"].lower().replace("(alm)", ''))
  terdakwa_filtered = [item for item in terdakwa if item.strip()] # menghapus index kosong
  jenis_dakwaan = data["kata_kunci"].lower() # cek jenis dakwaan
  # pasal = [i.strip() for i in data["content"].lower().split(';') if re.search('melanggar pasal', i.strip())]
  pasal = re.findall(r'melanggar pasal\s+([^;]*)', data["content"].lower())
  tgl_putusan = re.sub(r'(\b\d\b)', lambda x: f'0{x.group(1)}', data["tanggal_dibacakan"].lower())
  hakim_ketua = data["hakim_ketua"].lower().replace("hakim ketua", '').strip()
  hakim_anggota = data["hakim_anggota"].lower().replace("hakim anggota", '').replace("br", '').strip().split(',')
  panitera = data["panitera"].lower().replace("panitera pengganti", "").replace(":", "").strip()
  penuntut_umum = re.findall(r'\d+\.(.*?)\s*(?=\d+\.|$)', data["penuntut_umum"].lower())
  amar_lainnya = data["amar_lainnya"].lower()
  catatan_amar = re.sub(r'(\w+)\s*(\d+\.)', r'\1 \2', re.sub(r'(pn)\.', r'\1 ', data["catatan_amar"].lower()))
  # tuntutan_hukuman = [i.strip() for i in data["content"].lower() if re.search('dikurang', i.strip())]
  tuntutan_hukuman = amar_lainnya if re.search(amar_lainnya, data["content"]) else re.sub(r'\d+\.', '', find_similar_sentence(catatan_amar, amar_lainnya)).strip()
  putusan_hukuman = amar_lainnya if re.search(amar_lainnya, data["content"]) else re.sub(r'\d+\.', '', find_similar_sentence(catatan_amar, amar_lainnya)).strip()
  print("nomor_putusan:", nomor_putusan)
  print("Nama terdakwa:", terdakwa_filtered)
  print("jenis_dakwaan:", jenis_dakwaan)
  print("pasal:", pasal)
  print("tgl_putusan:", tgl_putusan)
  print("hakim_ketua:", hakim_ketua)
  print("hakim_anggota:", hakim_anggota)
  print("panitera:", panitera)
  print("penuntut_umum:", penuntut_umum)
  print("amar_lainnya:", amar_lainnya)
  print("catatan_amar:", catatan_amar)
  print("tuntutan_hukuman:", tuntutan_hukuman)
  print("putusan_hukuman:", putusan_hukuman)

In [237]:
generate_label(df_200.iloc[1])

nomor_putusan: 221/pid.b/2023/pn spg
Nama terdakwa: ['ahmad yasin bin. jamin']
jenis_dakwaan: pencurian
pasal: ['363 ayat (01) ke 04,5kuhp']
tgl_putusan: 10 januari 2024
hakim_ketua: ratna mutia rinanti
hakim_anggota: ['agus eman', '    ivan budi santoso']
panitera: muhammad slamet
penuntut_umum: ['indah asry pinatasari, s.h.', 'heronika setiawaty, s.h.']
amar_lainnya: pidana penjara waktu tertentu
catatan_amar: mengadili: menyatakan terdakwa ahmad yasin bin jamin (alm) tersebut diatas, telah terbukti secara sah dan meyakinkan bersalah melakukan tindak pidana pencurian dalam keadaan memberatkan; menjatuhkan pidana terhadap terdakwa ahmad yasin bin jamin (alm) oleh karena itu dengan pidana penjara selama 2 (dua) tahun; menetapkan masa penangkapan dan penahanan yang telah dijalani terdakwa dikurangkan seluruhnya dari pidana yang dijatuhkan; menetapkan terdakwa tetap ditahan; menetapkan barang bukti berupa : surat keterangan dari adira finance tanggal 27 maret 223 dengan dilampirkan foto copy bpkb sepeda motor honda scoopy warna hitam-merah tahun 2022 no.pol: m-2918-no, dengan no.ka : mh1jm0114nk625815, no. sin : jm01e1624952 atas nama pemilik ari kurniawati. 2 (dua) buah kunci kontak sepeda motor; dikembalikan kepada saksi ari kurniawati 1 (satu) buah compact disc yang berisi video rekaman cctv sebanyak 6 buah dengan masing-masing berdurasi: 00 menit 46 detik: 01 menit 24 detik; 01 menit 40 detik; 00 menit 19 detik; 00 menit 21 detik; 00 menit 28 detik; dirampas untuk dimusnahkan 6.membebankan kepada terdakwa untuk membayar biaya perkara sejumlah rp5000,00 (lima ribu rupiah);
tuntutan_hukuman: menjatuhkan pidana terhadap terdakwa ahmad yasin bin jamin (alm) oleh karena itu dengan pidana penjara selama 2 (dua) tahun
putusan_hukuman: menjatuhkan pidana terhadap terdakwa ahmad yasin bin jamin (alm) oleh karena itu dengan pidana penjara selama 2 (dua) tahun

In [16]:
new_df

,doc,text,label
0,189_Pid.B_2023_PN_Spg.pdf,"[PUTUSAN, Nomor, 189/Pid.B/2023/PN, Spg, DEMI,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
1,221_Pid.B_2023_PN_Spg.pdf,"[PUTUSAN, Nomor, 221/Pid.B/2023/PN, Spg, DEMI,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2,222_Pid.B_2023_PN_Spg.pdf,"[PUTUSAN, Nomor, 222/Pid.B/2023/PN, Spg, DEMI,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,227_Pid.B_2023_PN_Spg.pdf,"[PUTUSAN, Nomor, 227/Pid.B/2023/PN, Spg, DEMI,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,197_Pid.B_2023_PN_Spg.pdf,"[PUTUSAN, Nomor, 197/Pid.B/2023/PN, Spg, DEMI,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...,...
117,247_Pid.B_2021_PN_Spg.pdf,"[PUTUSAN, Nomor, 247/Pid.B/2022/PN, Spg, DEMI,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
118,246_Pid.B_2021_PN_Spg.pdf,"[PUTUSAN, Nomor, 246/Pid.Sus/2022/PN, Spg, DEM...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
119,265_Pid.B_2021_PN_Spg.pdf,"[PUTUSAN, Nomor, 265/Pid.Sus/2022/PN, Spg, DEM...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
120,268_Pid.B_2021_PN_Spg.pdf,"[PUTUSAN, Nomor, 268/Pid.B/2022/PN, Spg, DEMI,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
121,261_Pid.B_2021_PN_Spg.pdf,"[PUTUSAN, Nomor, 261/Pid.B/2022/PN, Spg, DEMI,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [ ]:
import json
new_df.to_json('datasetcoba.json', orient='records')

In [ ]:
accuracy(count_label)

Dokumen Ke-1 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-2 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-3 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-4 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-5 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-6 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-7 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-8 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-9 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-10 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-11 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-12 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-13 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-14 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-15 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-16 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-17 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-18 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-19 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-20 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-21 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-22 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-23 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-24 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-25 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-26 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-27 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-28 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-29 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-30 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-31 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-32 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-33 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-34 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-35 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-36 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-37 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-38 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-39 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-40 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-41 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-42 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-43 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-44 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-45 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-46 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-47 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-48 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-49 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-50 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-51 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-52 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-53 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-54 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-55 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-56 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-57 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-58 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-59 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-60 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-61 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-62 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-63 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-64 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-65 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-66 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-67 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-68 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-69 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-70 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-71 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-72 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-73 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-74 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-75 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-76 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-77 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-78 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-79 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-80 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-81 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-82 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-83 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-84 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-85 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-86 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-87 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-88 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-89 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-90 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-91 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-92 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-93 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-94 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-95 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-96 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-97 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-98 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-99 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-100 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Dokumen Ke-101 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-102 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-103 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-104 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-105 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-106 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-107 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-108 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-109 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-110 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-111 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-112 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-113 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-114 => Data Terlebel : 1 ; Total Label : 10 ; Label : ['B_CRIA']
Dokumen Ke-115 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-116 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-117 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-118 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-119 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-120 => Data Terlebel : 0 ; Total Label : 9 ; Label : []
Dokumen Ke-121 => Data Terlebel : 1 ; Total Label : 9 ; Label : ['B_CRIA']
Dokumen Ke-122 => Data Terlebel : 0 ; Total Label : 10 ; Label : []
Accuracy : {label_in/sum_label * 100}

'Accuracy : 7.515473032714412'